### ISSUE TITLE
Feature: unify backend and client validation details

### ISSUE THREAD

**Issue by peterblazejewicz** [sahat/hackathon-starter#1013]
In the other project based on this one there was an issue with different or lacking validation on the client templates (view layer) while the content is validated on the backend layer.
Let me explain:
- the backend code validates password to be not empty and with minimum lenght of 8 characters:
https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L87
```js
if (!validator.isLength(req.body.password, { min: 8 })) validationErrors.push({ msg: 'Password must be at least 8 characters long' });
```
- the view layer that captures that user input do not specify minimum length with the `minlength` attribute:
https://github.com/sahat/hackathon-starter/blob/master/views/account/signup.pug#L15
```pug
input.form-control(type='password', name='password', id='password', placeholder='Password', autocomplete='new-password', required)
```
Some views have no that validation layer added at all:
https://github.com/sahat/hackathon-starter/blob/master/views/contact.pug
while the server still validates user input:
https://github.com/sahat/hackathon-starter/blob/master/controllers/contact.js#L25-L29

This results in the inconsistent UX for the users and it was missed in the updates to the view layer previously (including my own PRs).

Using built-in validation does not require the project to add additional validation with JavaScript. This would work with just built-in features of modern browsers.

Thanks!

/cc @YasharF

**Comment by YasharF** [comment]
> Using built-in validation does not require the project to add additional validation with JavaScript. This would work with just built-in features of modern browsers.

I haven't had a chance to look into it.  If it is just an extra parameter that is missing in the form-control statements, then this would be great.  If it requires adding client-side javascript, then we may want to hold off on it for now.  Historically, my plan has been to keep the front-end lightweight and as dumb as possible, while having the backend contain all of the logic.  Can you point me to some docs, or if it is just adding some extra parameters to the form-control statements, would you like to submit a PR?

**Comment by peterblazejewicz** [comment]
>  If it requires adding client-side javascript

Nope, fully based on the input fields attributes.

> Can you point me to some docs

https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation
So what'd be added is the client side validation - based on built-in form validation features in HTML5 (the docs clearly describes the difference). The backend validation (also described in the docs) is here to stay, no changes. 
The intent is to align client validation with backend, to not frustrate users ('Hey, you've just submitted a password which is too short', 'Hey, you've sent us a contact form without any data').

> Note that the server-side checks need to stay regardless of checks in the front-end since they serve as an extra security measure.

100% with this. That's not an intent of the change.

Yes, I could do the review and PR with changes
