### ISSUE TITLE
Can we have twitch authentication too?

### ISSUE THREAD

**Issue by iamisti** [sahat/hackathon-starter#1019]

**Comment by YasharF** [comment]
Besides, Authentication, are there other twitch APIs that would make sense to build an example for?

**Comment by iamisti** [comment]
not really. Maybe just a list of your followed channels. But really optional

**Comment by YasharF** [comment]
Twitch support added with https://github.com/sahat/hackathon-starter/commit/c8df1150075b6e32129a9974975529e2e7a2dc37 and https://github.com/sahat/hackathon-starter/commit/901140f3b8949ea79029bab1cf1bf706e8ef2a7c
