### ISSUE TITLE
Adding a React front end

### ISSUE THREAD

**Issue by redlinecodes** [sahat/hackathon-starter#1023]
Has anyone successfully added a React SSR front end to this? Any tips and/or pointers on it? How hard is it?

**Comment by niallobrien** [comment]
Honestly, just use Next.js. Hackathon Starter isn't designed for SPAs with SSR. Sure, you can build a React app to use with Hackathon Starter, but you'll end up throwing out all of the default views etc. If you were to use Hackathon Starter, you'd be best to use it purely as a backend API server (add JWT support etc.), and use Next.js as a separate frontend, but I feel that there's already far better solutions out there for this and this approach is not the goal of this project.

**Comment by redlinecodes** [comment]
@niallobrien thanks for the suggestions... what other solutions are out there that would be better suited.

**Comment by JurajJakubov** [comment]
And cant be this somehow remade for nextjs? Because in nextjs there is missing something like this.

**Comment by ertejaspatel** [comment]
Is it easy to utilize this starter pack just as API and create fron-end separately either with next.js or create react app or any other front-end?

**Comment by niallobrien** [comment]
It depends on you really. Something like StrapiJS might be better suited -
again it depends on you and your needs.

**Comment by JurajJakubov** [comment]
> Is it easy to utilize this starter pack just as API and create front-end separately either with next.js or create react app or any other front-end?

next.js is using its own API routes (in version 9+) which is try to remove express. Which is a little bit harder to remake. Anyway, if anybody did this. Please share it. Merry Christmas :)
