### ISSUE TITLE
View Cache

### ISSUE THREAD

**Issue by aharris02** [sahat/hackathon-starter#1030]
I noticed an issue with view cache and can't seem to find the source. When I make changes to the actual view files, the changes appear immediately. But when I reference an external file from the view, any changes made to that referenced file do not show up unless I rename it.

2 examples: 

1. In home.pug, I'm using ckeditor for a text editor. when I load the ckeditor library and configure it directly within edit.pug, the changes mostly work. but when I reference an external ckeditor config file as it's designed to work, any time I make a change, I have to increment the name to config[X].json in order for ckeditor to load the updated config file.
2. I made changes to main.css, and I had to rename the file to main2.css and update the reference in layout.pug in order for them to load.

This only occurs at the view layer.

I've tried clearing or disabling pug cache and express cache. I can't find any other places where it might be cached. Any thoughts or ideas for where else to look? Any help is appreciated.

**Comment by YasharF** [comment]
What do you mean by referencing an external file?  Can you provide a code sample?

**Comment by niallobrien** [comment]
I'm guessing that the referenced external file is being cached on its end.

**Comment by aharris02** [comment]
> What do you mean by referencing an external file? Can you provide a code sample?

Sure - in layout.pug, here's the reference to main.css:

```doctype html
html
  head
    link(rel='stylesheet', href='/css/main.css
```

I changed the large media max-width from whatever the default was to 1600px in main.css:
```.container {
  @media (min-width: 1200px) {
    .container {
      max-width: 1600px; } }```

And that chnage wouldn't appear until I renamed main.css -> main2.css and updated the code referencing main.css in layout.pug to request main2.css. 

- This is all on the server's local fs
- I didn't use Docker to deploy, in case that might matter
- I only notice this within .pug files

**Comment by niallobrien** [comment]
If you have Chrome's Dev Tools open, please make sure it's not caching the
CSS file. For reference, it's not an external CSS file as it's contained on
the same server as your app; it's a local CSS file.

**Comment by YasharF** [comment]
Many web browsers cache CSS files based on their own default settings.  You would need to do a hard refresh of the page in the browser to tell the browser to re-request the CSS files.

**Comment by aharris02** [comment]
All really good suggestions. 

We have tried hard refreshes, deleting all cache files and local storage related to the site, and switching to different browsers. It is definitely being cached server-side.

**Comment by YasharF** [comment]
You are also modifying main.css;  main.css is not a user-modifiable file and is a server "generated" file that gets overwritten.  This project uses node-sass, and the stylesheets are in SCSS files.  The server generates optimized CSS files using the SCSS files.  Add your style changes in /hackathon-starter/blob/master/public/css/main.scss

**Comment by aharris02** [comment]
Still learning node, and I just noticed main.css isn't included in the library by default. Your explanation for why makes perfect sense, so thanks for that. Will add my changes to main.scss and see if I still have that issue.

Here's the code for the other file I'm accessing:
`home.pug`
```
script.
  CKEDITOR.replace( 'editor1', { customConfig: '/ckeditor4/config11.js', extraPlugins: 'autogrow', removePlugins: 'resize' } );
```

Would node-sass impact the reference to `/public/ckeditor4/config.js` as well?

**Comment by YasharF** [comment]
Node-sass deals with scss files and generates css files.

There isn't a server-side caching of browser-side js files, but we do have a configuration to tell the browser how long to cache the js files for: https://github.com/sahat/hackathon-starter/blob/master/app.js#L119

A hard refresh on the browser should be sufficient.

**Comment by aharris02** [comment]
> we do have a configuration to tell the browser how long to cache the /public files for: https://github.com/sahat/hackathon-starter/blob/master/app.js#L119. A hard refresh on the browser should be sufficient for the browser to re-request and disregard this cache setting.

Got it. That worked for me. Both issues are resolved, closing this out. Thanks for the help!
