### ISSUE TITLE
Verify password functionality conditional logic is a bit off

### ISSUE THREAD

**Issue by mayeaux** [sahat/hackathon-starter#1031]
Currently I am using the verify email flow

However, I am running into an issue where for some reason this main block of logic is not being triggered:
https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L283

Therefore the app just hangs infinitely and then Heroku times out the request. I'm still debugging it but I think it would be great if there was an else block on that `if` statement where it will return an error to the frontend. Because like I said I'm still debugging what's causing this but it's happened 'in the wild' for me so I think that it would be useful for users/devs if this case was handled, thanks.

**Comment by mayeaux** [comment]
I traced it back to the fact that if you are logged in with a different account when you try your verification link it will just hang without sending an error. I can submit a PR for this if you'd like, thanks!

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/6c4d5e9622546db18c22293699152a5662dc1cf2

**Comment by mayeaux** [comment]
Yay! Love the project glad I could help in some way :)

**Comment by yanivm** [comment]
Cool. But maybe there's a typo there? `req.flash('errors', ...` should be `req.flash('error', ...` ?

**Comment by YasharF** [comment]
`errors` is correct since it needs to match with the view at https://github.com/sahat/hackathon-starter/blob/master/views/partials/flash.pug#L1

**Comment by YasharF** [comment]
It looks like there is a typo a few lines above that commit I posted, so I fixed that one with https://github.com/sahat/hackathon-starter/commit/ba606d910881042d3793aec0d3701802da7b3792
