### ISSUE TITLE
Not really an issue more of a question!

### ISSUE THREAD

**Issue by markmorris** [sahat/hackathon-starter#1032]
Sorry for the question here but, how easy would it be to use this for a web app and also electron? I'm a strong PHP dev and been getting into Node the last couple of years, ive built an app that shares the same front end as the web app, but i host it on apache and writing code twice for web and electron is a pain. I'm strugling to find suitable methods of doing this and being able to deploy the same source code straight to electron without seperating the code base.

**Comment by niallobrien** [comment]
Howdy, in such a scenario you'd really be better off building a REST or
GraphQL API backend and build a SPA (Single Page App) on the frontend to
consume that API; React, Vue, Angular, Svelte etc. That way the view
rendering would be done on the client side, such as a web browser, mobile
app, desktop app, heck - it could be a terminal app (no web views as such)
or a client running on your refrigerator or toaster.

In your scenario, all of your views reside on the server and all of the
rendering is happening on the server (the same way this repo works), which
may not suit an Electron app. But I don't see why you couldn't just have
the Electron app hit your website as Electron is basically a browser. Then
in your client-side JavaScript, you could have Electron specific code that
only loads and executes when it detects Electron or something. Or perhaps
bundle such JS with the Electron app itself (though it would be easier to
update your JS if it was always being loaded from your server). The main
problem will be that if there's no active network connection (to the
Internet), your Electron app will appear very broken (unless you work
around it somehow) as it won't be able to load any views. This could
normally be handled gracefully in a SPA as really, it just needs to fetch
data and react accordingly.

I hope that points you in the right direction?
Many thanks.
