### ISSUE TITLE
Add reCaptcha support to the contact us form

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#1043]
This feature would be for unregistered users for now.  There have been some spam submissions through the demo app making this feature seem to be a good idea.

**Comment by wilburforce83** [comment]
I've just found this awesome boilerplate! I am currently self-isolating with nothing better to do, so if @sahat is accepting PR's I'll add this when I get a second.

**Comment by YasharF** [comment]
PRs are welcome for this.  A couple of potential requirements:
- I think it would be reasonable to require it only for unknown users though https://github.com/sahat/hackathon-starter/blob/master/views/contact.pug#L9 .
- If I recall correctly for using reCaptcha the server needs to have an API key.  A potential issue with requiring an API key for a basic feature is that it may slow down devs that would like to get started quickly, especially in the context of a hackathon.  I'm not sure if there is a way to do a professional-looking captcha without an API key or if there is a way to define a fallback where the captcha is skipped if there is no valid API key.

**Comment by wilburforce83** [comment]
@YasharF thanks for the heads up on this. I've not used pug before o I'll do a little reading up on the templating first, but it should be easy enough to integrate something with a default switch to off.

I notice GA is added inside https://github.com/sahat/hackathon-starter/blob/37034e6724a656f912e61a7444cb1ea8588cab5b/views/layout.pug#L29 to keep google in one place I could add a var in here for reCAPTCHA which can be tested in contact.pug then load the recaptcha if its been included in the layout?

**Comment by YasharF** [comment]
It is not a layout component, the frontend needs to stay within contact.pug

**Comment by YasharF** [comment]
Support added by https://github.com/sahat/hackathon-starter/commit/ab05ce661c037daeeea06b8ee34a44db942fbd24
