### ISSUE TITLE
Does it make sense to add babel support to use new js features?

### ISSUE THREAD

**Issue by nimpla** [sahat/hackathon-starter#1046]
Does it make sense to add babel support to use new js features?

**Comment by YasharF** [comment]
No, I am highly against the use of Babel for the following reasons:
Pros: Its benefit is early access to the JS features which soon are going to be a part of NodeJS anyway.
Cons: It bloats the dependency tree:  More files to load into the server.  More time to spend to keep dependencies up to date.

The expense is significantly higher than the benefit that it brings.

**Comment by sahat** [comment]
Agreed @YasharF.
