### ISSUE TITLE
Twitter e-mail address

### ISSUE THREAD

**Issue by osmanraifgunes** [sahat/hackathon-starter#1047]
Twitter allows users to get e-mail addres : 

https://github.com/jaredhanson/passport-twitter/issues/67

**Comment by YasharF** [comment]
Twitter allows applications to submit a request for getting a user's email address if the application has a production published privacy policy and terms of service.  Considering that most developers that start with hackathon-starter, are ways away from being in production with proper privacy policy and terms of service, it is going to be problematic if we require that permission in the boilerplate.
