### ISSUE TITLE
Where do i finbd CSRF token,

### ISSUE THREAD

**Issue by davidnalbandian143** [sahat/hackathon-starter#1048]
Error: CSRF token mismatch
    at checkCsrf (C:\Users\RudraSimha\desktop\hackthon\node_modules\lusca\lib\csrf.js:151:18)
    at C:\Users\RudraSimha\desktop\hackthon\app.js:95:17
    at Layer.handle [as handle_request] (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:335:12)

**Comment by YasharF** [comment]
You need to pass it from the front-end/view to the backend similar to https://github.com/sahat/hackathon-starter/blob/master/views/contact.pug#L8

**Comment by davidnalbandian143** [comment]
Where do i put this vale "input(type='hidden', name='_csrf', value=_csrf)" in back end

**Comment by davidnalbandian143** [comment]
I have given this " value=_csrf " in front end , where do i place this in back end

**Comment by davidnalbandian143** [comment]
I am sending the same but still showing " csrf not match "

**Comment by YasharF** [comment]
It is automatically handled by a middleware in the backend.  You are getting the error because the backend middleware is checking for the token and is not getting the token with the submitted request from the user.

**Comment by YasharF** [comment]
The csrf token rotates with every request, so one way you can troubleshoot it is to follow it with some debug code.

In the app.js right about line 95 add a `console.log(req.body);`  That should dump the received form submission by the backend, and in there look for the value that is being returned as the _csrf value.  It should be a string of random characters.  If it is blank or just "csrf" then the frontend is not doing its job.

On the browser side, you can check the meta tag or if using Chrome console, type the command command `document.querySelector('meta[name="csrf-token"]').content`  That should tell you if the front end received the initial csrf token from the blackened in the first place.

The value in the browser before a submission should match what your debug console log prints out after the submission.

**Comment by davidnalbandian143** [comment]
Thank u so much , i will check it

**Comment by davidnalbandian143** [comment]
I am getting this in console log 
{
  _csrf: '_csrf',
  email: 'pralayasimha@yahoo.com',
  password: 'Test@!23',
  confirmpassword: 'Test@!23'
}

**Comment by davidnalbandian143** [comment]
document.querySelector('meta[name="csrf-token"]').content

This command in developers console showing    ""

**Comment by YasharF** [comment]
Has this issue been resolved?

**Comment by davidnalbandian143** [comment]
solved
