### ISSUE TITLE
I successfully integrated summer note to this app but not able to fetch data 

### ISSUE THREAD

**Issue by davidnalbandian143** [sahat/hackathon-starter#1057]
I added summernote to my application for blog but i am getting HTML tags to the front end. I applied styles and fonts to text in the editor. I successfully saved it in data base but not able render fonts and text in front end. Instead i am getting text with bunch of html code.

**Comment by YasharF** [comment]
hackathon-stater is using pug for the frontend rendering.  I would suggest searching in pug documentation or issues for how to do what you are trying to achieve.
