### ISSUE TITLE
How to apply csrf token to certain forms only?

### ISSUE THREAD

**Issue by davidnalbandian** [sahat/hackathon-starter#1061]
When i apply csrf plugin in app.js and it will applying to all forms. If i remove them it is showing error.
I want to send csrf token either through ajax or completely remove for that particular form. How can i achieve that

**Comment by YasharF** [comment]
You will need to make the appropriate customization on the server-side for your ajax handler.  Not sure if you have already done so or not, but I highly recommend reading about CSRF, implementation and token handling: https://owasp.org/www-community/attacks/csrf
