### ISSUE TITLE
 [Feature request] Btc payment would be a nice feature

### ISSUE THREAD

**Issue by manibharathytu** [sahat/hackathon-starter#1066]
Basic :

Show btc address and QR code in the UI for the user to pay. Configuration in env file is just the btc address.

Advanced :

1) A way for the payment to be associated to particular user. This may be in implemented in any of the following ways.

- Have btc address of user as user property and whenever a pyament to the site's address from any of the user's adress, it can be known that is the user. This is insecure (but simple) still. One person can give another person's address. 
 
- User btc address verification (like email verification or some credit card verification), some random minimal amount can be asked to be sent by the user (or sent by the server) 

- A random 4 or 5 digit number can be a user property. For eg: if 1234 is the user's random number, then the last 4 digts of the user's transaction should be that random number. If he has to pay 0.01 btc, he will send 0.01001234. So that later it can be identified that its particular user.

- Different wallets for every users. This way users dont face any friction like wallet address verification or random number payment. But this will be a hassle for the site owner since he have to manage so many wallets unless he automated it to send to his main wallet whenever any wallet recieves any.

2)  Payment history. Automatically scan transactions to the site wallet and find the user payments and show it in the payment history page.

**Comment by YasharF** [comment]
Referencing some prior discussions: https://github.com/sahat/hackathon-starter/pull/308

**Comment by YasharF** [comment]
Won't be able to add it to the project if it requires a copy of the blockchain to be stored on the server.  If I understood your request correctly, that might be required.  If not, feel free to propose a PR.

**Comment by YasharF** [comment]
Showing QR code, or transaction management does not fall under the current intended scope of the project.
