### ISSUE TITLE
[Feature Request] Basic CRUD page

### ISSUE THREAD

**Issue by manibharathytu** [sahat/hackathon-starter#1067]
So that projects can start just by chaging parameter in the basic crud page.

Like home, api examples etc, there can be crud tab. In which user can create entries, delete entries, modify entries, view entries. This data should be user specific. Only logged in user can do these operations. Each entry may have X number of fields.

Example : Student details. Every enty is for a particular student. The fields can be name, marks, class etc.

**Comment by YasharF** [comment]
If I understood your request correctly, this is going to add a significant amount of logic to the project, and its use case might be too application-specific to be a part of the base boilerplate project.

**Comment by manibharathytu** [comment]
"this is going to add a significant amount of logic to the project,"

A db model file and a controller file would be needed. And the 3 or 4 route mapping lines in app.js is needed that's all. Not sure if thats too much.


"its use case might be too application-specific to be a part of the base boilerplate project."

https://ng-boilerplate.mdbootstrap.com/projects
Checkout the 'projects' and 'table' tabs in this angular boiler plate. Something like that would be cool. 

I think crud page is a basic boilerplate feature. A crud page is needed for even a simplest webapp (except full static sites). 
When I was searching for node express boiler plate, signup/login and crud was what I was expecting.
I actually cloned this project expecting it to have one. As much as I got delighted by the overwhelming login options, I was disappointed that it didn't have a basic crud page. Then I had to code the schema and controller from scratch.
If it was already there with params with place holders, I could just change it to my application data names (may be add some more fields by copy pasting if needed more or remove some fields if its not needed) and voila my app is ready!

**Comment by YasharF** [comment]
Can you describe your user stories for the "crud page"?  Are you just looking for the same functionality as the Table tab in the angular boilerplate example?  What I see there is a predefined data table entry page where the user can fill the table; no user management; no permissions; no data sharing.

Since this is a hackathon-starter project, can help with some example use cases in the context of a hackathon?

Thanks

**Comment by manibharathytu** [comment]
Thanks for the reply.

"Are you just looking for the same functionality as the Table tab in the angular boilerplate example?"
Yes. Exactly.

" What I see there is a predefined data table entry page where the user can fill the table; no user management; no permissions; no data sharing."
User management is there. You can add/remove/edit table entries and it is done on your account. I'm not sure about permissions and data sharing since thats not something I needed.

"Can you describe your user stories for the "crud page"?"
For the app I'm doing right now, users will login and they can create bots*. Every bot will have some fields like api_key(str), api_secret (str), order_size (int), order_interval(int), buy_or_sell_first (bool) etc etc.
To abstract it, its a table data on a user level. Users can create,delete,update,view those  entries.

*its a bot that manages their trading account. Buying, selling etc based on the parameters they set in my webapp.

"Since this is a hackathon-starter project, can you help with some example use cases in the context of a hackathon?"
Actually I've never been in a hackathon, I'm looking at this project like a boiler plate to start a webapp. Anyways some usecases I can think of are :- 
social app - where users can post stuff and they can view it going into their profile. Can edit and delete posts
note taking app - user can add his text notes, view/edit/delete at anytime later.
todo app - add/remove tasks, set task status as completed/ongoing

**Comment by Nishant-Bhosale** [comment]
What type of entries should the user be able to create?
