### ISSUE TITLE
Migrate from twit to twitter-lite

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#1071]
twit isn't actively maintained.

**Comment by ricardo93borges** [comment]
Hi

I want to help with this issue, could you assign me this issue, please?

**Comment by YasharF** [comment]
You can just submit a PR for it.

**Comment by YasharF** [comment]
@KhushalPShah Are you getting the error before making any changes?  If so, make sure you have your twitter API credentials set properly.  Take a look at the readme on how to obtain the api credentials from twitter.

Cheers!

**Comment by YasharF** [comment]
Fixed by https://github.com/sahat/hackathon-starter/commit/a58a59755a947bbac6ea2faa7add0a89ba468fca
