### ISSUE TITLE
Remove mLab instructions from "1-Step Deployment with Heroku" documentation 

### ISSUE THREAD

**Issue by hugeprestigellc** [sahat/hackathon-starter#1072]
The mLab team has chosen to discontinue the mLab add-on for Heroku. The mLab MongoDB add-on will be removed from all Heroku apps on November 10, 2020. Applications will lose access to their databases if action isn't taken before this date.

I think the documentation needs to be updated to remove all references to the mLab add-on for Heroku in particular. In just a few months the "1-Step Deployment with Heroku" instructions will not work. Perhaps the documentation could be changed to something like "Quick Deployment with Heroku" and combined with the steps to connect to a MongoDB Atlas account.

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/b4898f2cd3af8c9a35fb126f5656bec1604e465c
