### ISSUE TITLE
Add Cookie Consent and a privacy policy

### ISSUE THREAD

**Issue by mshd** [sahat/hackathon-starter#1079]
Wouldn't it be nice to include a cookie consent plugin and a privacy policy generator. So you can immediately publish the website.

**Comment by YasharF** [comment]
Todo: Finding a ToS and a Privacy Policy that is free to use (aka CC0 license, etc), and is fairly generic and permissive.

**Comment by dnafication** [comment]
Is [this](https://www.freeprivacypolicy.com/free-cookie-consent/) something we can use?

**Comment by YasharF** [comment]
@dnafication I tried to grab a terms of service doc from the free cookie consent site you posted, but it wasn't so free since hackathon-starter has features like account creation.  We need to find another source for a free to use generic ToS and Privacy Policy (CC0 license, etc).

**Comment by sahajkedia** [comment]
Hi, I would like to work on this issue. 
Using https://www.termsofusegenerator.net/ I see that I need to give an email id and an address for generating the privacy policy and terms of use. Please guide me on which address or email to give.

P.S. Nice project idea.
