### ISSUE TITLE
WSL 2 does not support 127.0.0.1 for twitter login

### ISSUE THREAD

**Issue by codewired** [sahat/hackathon-starter#1081]
Twitter call back URL on WSL 2 does not work when you use 127.0.0.1
This worked for me => http://localhost:8080/auth/twitter/callback

**Comment by YasharF** [comment]
I have to check, but I think I also got WSL2 to work with the LAN address aka 192.168.x.x instead of 127.0.0.1 as well.

**Comment by YasharF** [comment]
Going to close this issue.  Hopefully, Microsoft will have a better solution for dealing with WSL2 in the near future.
