### ISSUE TITLE
Sendgrid and nodemailer: verified Sender Identity

### ISSUE THREAD

**Issue by Barno** [sahat/hackathon-starter#1083]
Hi, If I try to use sendgird I receive this error:
```response: '550 The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements',```

My identity is verified.
I tried to use Sengrid's code (apiKey) and I'm able to send email.

**Comment by YasharF** [comment]
If I am reading the error correctly, it is not your identity that needs to be verified, but the address in the "From" filed needs to match the configs that you put in the sendgrid's dashboard on their website.

**Comment by Barno** [comment]
Thanks, I change the address at "From" field, and it works. Thanks for your time
