### ISSUE TITLE
Refactor sendMail transporter calls

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#1102]
In the current implementation, we have a blob for error checking and retry every time that the app has code for sending emails.  This issue code is seen at:
https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L354
https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L439
https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L536

Note that the flash messages and console log messages vary between the above three examples.

Ideally, we want to refactor this into a reusable function and make each controller more compact and readable.  In the case of the above examples, this function can stay in controllers/users.js to make it easier to find and avoid confusing newer developers.

**Comment by nesarazui** [comment]
Hi, I would love to give this a try, could you please assign this to me? Thanks!

**Comment by YasharF** [comment]
Can you submit a PR in the next few days?  Thanks!

**Comment by KhushalPShah** [comment]
@YasharF 
If I get this correctly,
We need a common function for handling the error ? (i.e. the catch block )

If not, can you please provide some more details on this?

**Comment by bkyogesh28** [comment]
@YasharF  I went through the contact site. The recaptcha has an error stating wrong RECAPTCHA_SITE_KEY whic belongs to the owner....

**Comment by YasharF** [comment]
@bkyogesh28 this github issue is for refactoring sendMail transporter calls.  If you have found a bug or need support, please create a new github issue with the details.  Thank you!

**Comment by nesarazui** [comment]
@YasharF, just submitted a pull request here: https://github.com/sahat/hackathon-starter/pull/1105
Please let me know if any other changes are required. Thanks!
