### ISSUE TITLE
401,404,500 pages

### ISSUE THREAD

**Issue by Athira2199** [sahat/hackathon-starter#1121]
All sites usually have 401,404,500. It would be great to have the same in this boiler plate too.

**Comment by YasharF** [comment]
Feel free to submit a PR.

Thanks!

**Comment by Athira2199** [comment]
Great will do that !

**Comment by Homerm54** [comment]
Hi. I'll glad to add the 401 and 500 pages.

**Comment by Jassi10000** [comment]
@Athira2199  Can I work on this ? Pls assign me
