### ISSUE TITLE
File upload support 

### ISSUE THREAD

**Issue by Athira2199** [sahat/hackathon-starter#1122]
Some hackathons may require file upload support. Hence it will be great if we could add file upload routes also in this repository.

**Comment by YasharF** [comment]
Already supported: https://github.com/sahat/hackathon-starter/blob/master/app.js#L173

**Comment by Athira2199** [comment]
Currently it is local device, I was suggesting something like cloud storage.

**Comment by YasharF** [comment]
If you are looking for cloud storage integration, the basis for Google Drive integration is at https://github.com/sahat/hackathon-starter/blob/master/app.js#L179 .  You can modify the related controller to perform various functions including file uploads.

Cheers :)
