### ISSUE TITLE
Missing Form Data on POST Route

### ISSUE THREAD

**Issue by jonboone1** [sahat/hackathon-starter#1128]
Hi there,

I am assuming this is an issue with me not understanding CSRF well enough, but I am having an issue with creating a new form within this framework. I implemented a basic form on a new page, made sure to include the hidden form field in my form, and when I finally post it the only data I get in my req.body is the csrf field. Below is my code and my output.

**my-board.pug**
` form(method="POST")
    input(type='hidden', name='_csrf', value=_csrf)
    .form-group
        label(for='challenge') Challenge
        input#challenge.form-control(type='text' placeholder='Type your challenge here' required)        
    .form-group
        label(for='status') Challenge Status
        input#status.form-control(type='text' placeholder='Not complete' required)                      
    button.btn.btn-primary(type='submit') Submit`

**Controller**
`exports.postChallenge = (req, res, next) => {
    console.log(req.body);
}`

**Route in app.js**
`app.post('/my-board', adminController.postChallenge);`

**Entire output from the controller**
`{ _csrf: 'TcgTgzBVCdJ3sxFFMvRwsfaHoi1Ib9squxSs0=' }`

Can you help me understand what I'm doing wrong?

**Comment by YasharF** [comment]
It is hard to read my-board.pug in its current formatting.  Perhaps there is an indentation issue that is causing the input fields to go out of the scope of the submit button.

**Comment by jonboone1** [comment]
My mistake!! I actually just realized I didn't put names for each form field. My apologies :(
