### ISSUE TITLE
GitHub Login

### ISSUE THREAD

**Issue by codewired** [sahat/hackathon-starter#1132]
For a newly created GitHub account , the 'Keep my email address private' check box under email in personal settings is checked by default. This causes the profile._json.email to return a null value and thus bypasses the existing email user check for existing GitHub email in MongoDB. This causes a **Server Error** for mongoose duplicate key insertion but the good news is that you can still extract the user email from profile.email which is an array of objects [{value: example@example.com}]. And from what i have seen so far, this array always contains one email, which is the primary one for the users account.

**Comment by YasharF** [comment]
Would you be able to help by submitting a PR for this?

**Comment by codewired** [comment]
Sounds good. Will make a PR within the next 24 hours. Cheers.
