### ISSUE TITLE
Add Courier for notifications

### ISSUE THREAD

**Issue by tk26** [sahat/hackathon-starter#1137]
Courier (https://www.courier.com/) is One API to design and deliver notifications across multiple channels.

While working on an app where there's a need to send a notification, typically a notification could have to be sent as an Email, SMS or Push.

IMHO it'd be super useful to have a way of designing a notification quickly, and configuring it to be sent across one or more channels - for instance, send it as an email with SendGrid, send as an SMS with Twilio or as a Push.

Courier can help achieve this process in a matter of seconds with almost no code, which can help hackers focus on their idea than having to spend their valuable time in building notification modules.

If you think this makes a solid use-case, I'd ❤️ to contribute by integrating Courier's Node.js SDK (https://github.com/trycourier/courier-node)

Disclaimer: I work at Courier as a core Product engineer.

PS: I absolutely love this project - I've used this at hackathons and also for interview exercises :) (https://github.com/tk26/ExpenseTracker and https://github.com/tk26/pied-piper/)

**Comment by sahat** [comment]
I am closing this issue, @tk26 if you are still interested in adding a Courier integration, I would be happy to review and merge it.
