### ISSUE TITLE
Update Bootstrap to 5.X version

### ISSUE THREAD

**Issue by writingdeveloper** [sahat/hackathon-starter#1156]
I found that Bootstrap has been updated to 5.X version.

And it seems that it has various advantages. For example, from now bootstrap doesn't use jQuery.

Is there any plans to update boostrap 5.X version?

**Comment by 0proboy0** [comment]
+1

**Comment by sahat** [comment]
Hi @writingdeveloper, yes I have started migrating to Bootstrap 5 in one of my local branches. Unfortunately, cannot give you a specific ETA due to busy schedule.

**Comment by writingdeveloper** [comment]
@kitarp29

If you are interested in updating bootstrap 5.x, I think you can work on it.

**Comment by sahat** [comment]
https://github.com/sahat/hackathon-starter/commit/b8e1c8c5e3f5b84dfa03a7f2b1e87bf6c311aeff#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R27
