### ISSUE TITLE
VSCode intellisense tips/setup for the hackhaton-starter

### ISSUE THREAD

**Issue by Nikita-schetko** [sahat/hackathon-starter#1190]
Thank you for the perfect boilerplate for quick nodejs apps!
Is there any bestpracticies, tips how to setup intellisense/code tips for this project in VSCode? 
I used to work a lot with typescript, and really missing code hints feature here; 

Maybe, we can include some JSDoc data for package to make it add some developer experience ?

**Comment by YasharF** [comment]
I suspect you can just use one of the copilot extensions in VS Code.  Does that help?
