### ISSUE TITLE
add joi for req validation

### ISSUE THREAD

**Issue by erfuuan** [sahat/hackathon-starter#1198]
Hello everyone
I am a Junior Nodejs developer and i found this project in github
I can add Joi for request validation data .
is it good?
can someone help me about contribute?

**Comment by s1ckn3zz1337** [comment]
I would rather use AVJ as it‘s faster than joi…

https://ajv.js.org<https://ajv.js.org/>


Am 16.09.2022 um 21:35 schrieb erfan ***@***.***>:

﻿

Hello everyone
I am a Junior Nodejs developer and i found this project in github
I can add Joi for request validation data .
is it good?
can someone help me about contribute?

**Comment by erfuuan** [comment]
It's true, now that I looked at npm, I noticed that it has a higher number of installs
Does the person in charge of this project agree with adding AJV?

**Comment by erfuuan** [comment]
@sahat can you help me :))
I have some good ideas for tidying up the code

**Comment by mehulbaid** [comment]
@erfuuan I have done this before with joi. add me too.

**Comment by YasharF** [comment]
Closing this issue due to lack of use cases.

**Comment by erfuuan** [comment]
> Closing this issue due to lack of use cases.

Hello, is it possible to reopen this issue? I can assist you in improving the code.
