### ISSUE TITLE
Broken logos

### ISSUE THREAD

**Issue by mstomar698** [sahat/hackathon-starter#1200]
Logos in README.md are broken. (Not visible)
![hackthon-starter-repo](https://user-images.githubusercontent.com/89572392/193091091-beae706f-e7dc-44ac-93c6-eb33326a4b22.jpg)
![hcktsrt-repo](https://user-images.githubusercontent.com/89572392/193091129-9ea30899-4994-4341-ad29-d755f9c4b16f.jpg)

Can Change It!!

**Comment by umadhatri** [comment]
Can I work on this issue?

**Comment by intincrab** [comment]
@201B153 hey can you check my PR ( Broken logos #1204) I made the changes in the logo 
but I have no idea what to put as the logo in 'Dependency Status' and 'devDependencies Status' 
can you tell me so that I can make the changes required 
also can you lable this as a hacktoberfest PR

**Comment by plakxj** [comment]
收到！
