### ISSUE TITLE
Secure Env Not Used for ENV Keys

### ISSUE THREAD

**Issue by mehulbaid** [sahat/hackathon-starter#1210]
In ref to #1127 , Sendgrid keys are exposed publically.

I can fix this.

**Comment by mehulbaid** [comment]
@sahat - Please prioritise this.

**Comment by renovX** [comment]
can i solve this issue? Thank you

**Comment by mehulbaid** [comment]
I already am on it

**Comment by YasharF** [comment]
Can you elaborate more on what you mean by "Sendgrid keys are exposed publically" ?

**Comment by YasharF** [comment]
Going to close this issue due to no response.  The original issue "Sendgrid keys are exposed publically" is invalid.

**Comment by YasharF** [comment]
https://github.com/sahat/hackathon-starter/commit/80af16175880763cfdd0a0ebc44298842a7b0fbf
