### ISSUE TITLE
Node 20

### ISSUE THREAD

**Issue by vimark1** [sahat/hackathon-starter#1255]
Node 18 goes into maintenance next month, October 2023 See https://endoflife.date/nodejs

Should we move to the next node LTS 20?

Everything already works on node 20, but some tidy ups to use node 20 through out and npm 9 would be ideal

**Comment by YasharF** [comment]
What do you mean by tidy ups to use node 20?

**Comment by Vansh17555555** [comment]
he might be referring to the libraries like dotenv which are not really needed in the node 20

**Comment by PanduruIonut** [comment]
Hello, can i be assigned  to this issue ?

**Comment by YasharF** [comment]
This issue is not valid.  Closing
