### ISSUE TITLE
mongoose connection 

### ISSUE THREAD

**Issue by abrehan2** [sahat/hackathon-starter#1260]
I will add a file in the config folder which is used to connect mongoDB. Thanks.

**Comment by Soumya-9641** [comment]
Can you assign this issue?

**Comment by Aditya7842** [comment]
Hey, I am new to GitHub and I wanted to know what in particular you wanted to do in this repo. If you want to write a code for making a connection of the mongoose to the mongoDB. Then I am up for it. So, If this is the problem then assign this issue to me.

**Comment by YasharF** [comment]
Marking as spam and invalid and closing.
