### ISSUE TITLE
Implement Passport Serialization and Deserialization

### ISSUE THREAD

**Issue by Ryrahul** [sahat/hackathon-starter#1263]
### Description:
Add `passport.serializeUser` and `passport.deserializeUser` functions for user session management and authentication state persistence.

### Context:
The project currently lacks session management, hindering user authentication. Implementing these functions is crucial for secure authentication.

### Expected Outcome:
With these functions, user sessions will be managed securely, ensuring seamless authentication and user state persistence.

**Comment by Vansh17555555** [comment]
sir can you please assign me this issue to work on?

**Comment by Ryrahul** [comment]
Let's wait for the maintainer to have a look at the issue. I'm definitely interested in working on it, and once the maintainer provides their input, we can collaboratively work on finding the best solution. I appreciate your eagerness to contribute, and I'll be sure to keep you updated once we have more direction from the maintainer. Thank you for your understanding and patience!

**Comment by Ryrahul** [comment]
@YasharF  Can you have a look at it once

**Comment by Vansh17555555** [comment]
@Ryrahul thanks man,I really appreciate your cooperation

**Comment by YasharF** [comment]
Closing the issue as invalid.  The serializeUser and deserializeUser was added more than 7 years ago.
