### ISSUE TITLE
Will make navbar remain on top on scrolling

### ISSUE THREAD

**Issue by mohammedasimahmed** [sahat/hackathon-starter#1268]
The navbar leaves the view space when I scroll down , I want to fix this , @YasharF could you please assign me this issue

**Comment by Pratik1603** [comment]
Please assign this to me

**Comment by vaxad** [comment]
you can assign this to me!

**Comment by legendary0911** [comment]
can you assign it to me ?

**Comment by YasharF** [comment]
We don't need this at this point
