### ISSUE TITLE
Destroying the cookies after logout of user

### ISSUE THREAD

**Issue by ShubhamMore6688** [sahat/hackathon-starter#1273]
![photo_2023-10-05_19-14-44](https://github.com/sahat/hackathon-starter/assets/94038708/e1d172f2-6ece-4849-bd0c-3fbf830d41dd)

I want to contribute in this issue, Please assign this to me.

**Comment by AkshitGuptaIITR** [comment]
I want to contribute.

**Comment by YasharF** [comment]
There is no guarantee that the client would follow thru and delete the cookie.  The cookie needs to be managed from the server side which is already implemented.
