### ISSUE TITLE
Adding OAUTH 2.0 

### ISSUE THREAD

**Issue by AKsHaT123456A** [sahat/hackathon-starter#1278]
Adding Sign in with google functionality

**Comment by mukul018** [comment]
I can do it.
Please assign this issue to me.

**Comment by CodeAnk2829** [comment]
Hey @AKsHaT123456A, I've done authentiacation with different stragegies (like google, facebook etc) and I'd love to work on this issue if it would be assigned to me.

**Comment by YasharF** [comment]
Closing and marking as spam.
