### ISSUE TITLE
Critical dependency error during install: formidable <3.2.4

### ISSUE THREAD

**Issue by stephfoxy** [sahat/hackathon-starter#1296]
On install via npm I got a critical vulnerability for formidable <3.2.4

Error msg:
formidable  <3.2.4
Severity: critical
Formidable arbitrary file upload - https://github.com/advisories/GHSA-8cp3-66vr-3r4c
No fix available
node_modules/formidable
  superagent  0.4.0 - 8.1.2
  Depends on vulnerable versions of formidable
  node_modules/superagent
    supertest  *
    Depends on vulnerable versions of superagent
    node_modules/supertest

Looks like the team maintaining Formidable don't agree with the vulnerability rating and are trying to get it reviewed, but the current flagging may present issues for others trying to install also.

**Comment by Anurag0218** [comment]
is this issue still open? is anyone working on it? If not, can I take it up?
