### ISSUE TITLE
CSRF issue

### ISSUE THREAD

**Issue by cjuhong** [sahat/hackathon-starter#163]
the form:

form#gravatarForm(action='/upload', method='POST', style='display: none;')
    input#gravatarUpload(type='file', name='gravatar')

ajax post:
$("form#gravatarForm").submit(function(event){
        event.preventDefault();
        var formData = new FormData($(this)[0]);
        $.ajax({
          url: '/upload',
          type: 'POST',
          data: formData,
          mimeType:"multipart/form-data",
          headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
          async: false,
          cache: false,
          contentType: false,
          processData: false,
          success: function (returndata) {
            alert(returndata);
          }
        });
        return false;
      });

//submit post
      $('#gravatarUpload').change(function(){
        $("form#gravatarForm").submit();
      });

I got message: 
POST http://10.8.17.62:3001/upload 403 (Forbidden) ????

**Comment by agaezcode** [comment]
@jinaymehta25, as @sahat say: *...you must place it before CSRF middleware.*

```javascript
//1st Upload route together with blog update route
app.post('/blog/update/:id', upload.single( 'file' ), blogController.postUpdate );

//2nd CSRF middleware.
app.use((req, res, next) => {
  if (req.path === '/upload/') {
    next();
  } else {
    lusca.csrf()(req, res, next);
  }
});
```
