### ISSUE TITLE
express-session message

### ISSUE THREAD

**Issue by jshemas** [sahat/hackathon-starter#169]
I keep seeing these messages when I start my server.

`express-session deprecated undefined resave option; provide resave option app.js:83:9`
`express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:83:9`

This can be fixed by adding `"resave": true/false` and `"saveUninitialized": true/false` to app.js where you define session. (Not sure if these should be true or false)

More info can be found here: http://stackoverflow.com/questions/24477035/express-4-0-express-session-with-odd-warning-message

**Comment by paul-xiao** [comment]
Thanks, works for me
