### ISSUE TITLE
Notes for Hackathon Starter 3.0

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#179]
I will start the list for the *possible* upcoming changes. 

Feel free to add or remove anything. Everything below is open for discussion.

- ~~Bootstrap 3.3~~
- **More** API examples.
 - ~~ordr.in~~ https://hackfood.ordr.in/
 - ~~Paypal (?) https://developer.paypal.com/docs/api/~~
- ~~Bring some of the  [SailsJS](http://sailsjs.org/#/documentation/concepts/Testing) and Google's Web Starter Kit features~~.
- ~~Cleanup `app.js`~~.

**Comment by vladimiry** [comment]
What about using bower + gulp to manage web dependencies? In two steps: 1) "bower install" 2) copy needed files from bower_components to ['public/fonts', 'public/css/lib', 'public/js/lib'] After adding "bower install && gulp install" to package.json "postinstall" dependencies of all layers could be installed by one command "npm install". I use this approach on top of current version of "hackathon-starter", so "lib" and "fonts" folders are empty initially.

It also would be great to switch between DB types, at least mongo <--> postgres. But I understand that it's not easy to do without using complex ORM module, that able using general API to handle NoSQL and SQL databases as well. Actually I have replaced Mongo by Postgres (via Sequelize) in my last "hackathon-starter" based project, but Sequelize does not support NoSQL databases.

**Comment by sahat** [comment]
@vladimiry Bower and Gulp has already been considered. @dstroot created a project similar to Hackathon Starter called [Skeleton](https://github.com/dstroot/skeleton) using Gulp, Bower and etc. I use both Bower and Gulp for my other projects, howerver, for Hackathon Starter I want the barrier to getting started to be at minimum.

I knew someone who tried to create an abstraction layer of some sorts for Node.js that works seamlessly with Postgres, MySQL, MongoDB, and others, so that you can just plug it in and it magically works with all databases. It was very difficult and I don't think that project was every finished. I am fine with MongoDB because it is a popular choice among Node developers, just like MySQL is popupar among PHP devlopers and Postgres among Python developers.

**Comment by loris** [comment]
@vladimiry @sahat Sails.js ORM, [Waterline](https://github.com/balderdashy/waterline) is a pretty popular one, and do support both SQL and NoSQL databases (`An adapter-based ORM for Node.js with support for mysql, mongo, postgres, redis, and more`)

**Comment by vladimiry** [comment]
@Ioris I've tried Waterline, it is very limited, and it seems that the authors have no plans to solve numerous issues. For example there is still no support for arrays (honest/true arrays, for Postgres for example) https://github.com/balderdashy/sails-postgresql/issues/36 So IMO at this time it is only suitable for the most simple tasks.
