### ISSUE TITLE
Any chance you will do a version of this using koajs?

### ISSUE THREAD

**Issue by debonair** [sahat/hackathon-starter#216]
are you likely to do a version of this using koajs.com

**Comment by sahat** [comment]
I have tried Koa.js when I was working on my OAuth 2.0 blog post and I did not like it at all. Most of the packages are too immature at the moment and many wrappers simply do not exist yet, so you end up "thunkifying" modules to make them work with generators.
I just don't like either idea of a) creating and maintaing a separate wrapper to work with Koa.js or b) having to thunkify a module to work with generators.

Until majority transitions to ES6 generators-based flow (which could take a long time), I don't see what is so great about Koa.
