### ISSUE TITLE
.populate() new attributes in the user model

### ISSUE THREAD

**Issue by DaddyWarbucks** [sahat/hackathon-starter#217]
I have added some new attributes to the user model. For example: 

    account: { type : mongoose.Schema.ObjectId, ref : 'Account' },

I am using an external API that reads/writes from the same MongoDB as the app itself. On a GET request to that API, I have set up the user model, and all other models, to populate(). But, I never use this API for actually creating the user, and setting the user to the locals in templates. I CRUD the "account" ID via this API. But the population of this ID is not respected.

I have tried a adding

    .populate('account');

a few different places in the user.js controller and in the app.js to no avail. Could you guide me where I could use this function to populate any of these parameters and make them accessible in the templates.

As always, thank you for any help!!

**Comment by sahat** [comment]
Hey @DaddyWarbucks this question is more suited for StackOverflow with `#mongodb #mongoose #node.js`. My experience with Mongoose is very limitied. Whenever I need something more complicated than just a single Mongoose model I ask a question on SO if I cannot figure it out by reading Mongoose Docs.

I don't know if this helps but take a look at my ShowTrackr's source code to see `populate` [in-action](https://github.com/sahat/tvshow-tracker/blob/68a3a464e756e5a659a4ce3e139c415cab83fa5b/server.js#L357) with 2 Mongoose schemas.

**Comment by sahat** [comment]
I am going to close this issue as it is not directly related to hackathon starter but more to Mongoose library.

Did you figure out how to solve your problem with `populate()` by any chance?

**Comment by DaddyWarbucks** [comment]
I kinda put it on the backburner. I have not figured it out yet, but thank you very much for your response! I appreciate the help.
