### ISSUE TITLE
Facebook/Twitter login not functioning

### ISSUE THREAD

**Issue by ole-magnus** [sahat/hackathon-starter#22]
I am trying to add login with Facebook and Twitter. Regular login with e-mail and password works fine. However, when I try to login with Facebook, it asks for permission (from Facebook), and I am redirected to the main page ("/") without getting logged in. The text in the upper right corner still tells me I am able of logging in. I've been scanning through the whole code base, but I am not able of locating the error. I am providing correct clientId and clientSecret. The callbackUrl is set to http:myIP:3000 both in the facebook-console and in the secret.js-file. The same scenario occurs with Twitter-login.

Any idea where my error might be? Thanks!

**Comment by mattspaulding** [comment]
Solved it for me 4 years later lol.
