### ISSUE TITLE
How would I install google recaptcha in the Hackathon-starter framework

### ISSUE THREAD

**Issue by ricksturgeon** [sahat/hackathon-starter#223]
HI:

I have been trying to get google Recaptcha to install in the framework. I realize this is not an issue but an additional functionality request. But it looks very simple but I can not get it to work. Attached is the url that describes how to install in Jade, but not working for me. I am not sure what to put in the form and what to put in the template. Thanks for the help.  https://www.npmjs.com/package/recaptcha
Rick

**Comment by sahat** [comment]
@ricksturgeon You should ask this question on StackOverflow. I haven't worked with Node.js captcha modules so can't help you without digging deeper into recaptacha.

**Comment by ricksturgeon** [comment]
I got nocaptcha the latest Google working in your framework. I required several files to be changed. Are you interested in the code to potentially add to your frameworks. Very effective in stopping robots creating users. ?

**Comment by sahat** [comment]
Thanks, but I don't see much point in adding *captcha* to a project that was meant to be a boilerplate / starting point for your projects.
