### ISSUE TITLE
All emails are converted to lowercase

### ISSUE THREAD

**Issue by aharelick** [sahat/hackathon-starter#225]
In commit 27336914afb5fc7700e9cc194123999ff3de8801 the User model started to store all emails as lowercase to comply with the gravatar api. Unfortunately, because the passport authentication is case sensitive you cannot log back in if you create an email with an uppercase letter. To replicate the error: 
1. Create an email that is not entirely lowercase i.e. 'Upper@gmail.com'
2. Log out and attempt to log back in with 'Upper@gmail.com'
3. You should get an error telling you that the email does not exist, so the natural reaction is then to create an account. 
4. Signup again with the same email. Passport will happily take your email because the one you are trying to register is 'Upper...' but the db has 'upper...' stored. However, when mongo forces it to lowercase you will get a db error.

**Comment by joshuaforliberty** [comment]
passport.use(new LocalStrategy({ usernameField: 'email' }, function(email, password, done) {
  email = email.toLowerCase();
  ...

**Comment by sahat** [comment]
Sorry, I haven't had a chance to look into this issue until today. @joshuaforliberty's workaround is pretty good. You should see this change on `master` now.
