### ISSUE TITLE
code in main.js not loading??

### ISSUE THREAD

**Issue by DavidAwad** [sahat/hackathon-starter#226]
All I've done is attempt to run some code on load of the root directory. Main.js looks like this

```javascript
$(document).ready(function() {

  // Place JavaScript code here...
  $.getJSON('/').then(function(data) {
    $('.arrayHere').html('<p>hello</p>');
    console.log( "hello there");
  })
  
});

```

**Comment by sahat** [comment]
The code in `main.js` should be loading just fine, the problem is with your `$.getJSON` part not hackathon starter.
