### ISSUE TITLE
Revert Sass to LESS

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#233]
I will be reverting styles back to LESS due to so many annoyances related to `node-sass` module.

1. `gcc` version incompatiblity. #228 
2. Incompatiblity with the latest version of io.js.
3. Having to split themes into multiple files because you need to load Sass variables in the right order.
![screenshot 2015-02-23 19 56 13](https://cloud.githubusercontent.com/assets/544954/6342999/1748f964-bb96-11e4-9b97-b8a0b0f71a92.png)
4. Requires you have gcc or Visual Studio or Xcode to compile native C++ code.

I assume many hackers, myself included, prefer to live on the bleeding edge, e.g. running the latest version of io.js. If you were to download hackathon starter right now you wouldn't even be able to get started.  

![screenshot 2015-02-23 19 59 30](https://cloud.githubusercontent.com/assets/544954/6343032/9760e1b6-bb96-11e4-8834-57bf13c235f2.png)

I have never had any of the above issues with LESS. I still love Sass but not that much that it becomes is a stopping point.

**Comment by geggleto** [comment]
+1

**Comment by fonzarely** [comment]
+1

**Comment by gabooh** [comment]
Those are much less of a problem now that node v4 is out.
