### ISSUE TITLE
Login using command line post (building RESTful API)

### ISSUE THREAD

**Issue by claymcleod** [sahat/hackathon-starter#235]
Hello all,

The issue I'm having is with the ability to login with a simple post request. Whenever I do the following request:

```
curl --data "email=hello@gmail.com&password=world" http://localhost:3000/login
```

I get a CSRF token mismatch. After doing a little research on this, I determined that this is the expected behavior for forms loaded in a web browser, but not for logging in such as in a RESTful api. My question is, is the correct solution to remove csrf? I have never worked on an API like this, so I'm not sure if it's possible to get a csrf token from the command line or where that token is stored (a cookie?). 

Side note: When I add a csrf token given to my web browser and passed through as a hidden field, the request works fine.

**Comment by sahat** [comment]
For curl calls you should turn off CSRF. If you are planning to build a single page app using one of many popular JS frameworks you could render the initial "main" page on the server and store the csrf token somewhere in `<head>` which I think is already the case:
```jade
meta(name='csrf-token', content=_csrf)
```

I am not too familiar with CSRF protection in the context of REST API and single page apps. I have only worked with token-based authentication where CSRF is not an issue.
