### ISSUE TITLE
What is the logging strategy using Hackathon Starter?

### ISSUE THREAD

**Issue by charles-cai** [sahat/hackathon-starter#236]
Hi @sahat, thanks for the great starter kit. Just wondering what will be the production logging strategy you would recommend? I want my site to save all activities to log files and I'll back up those logs to a safe location for various analytics later. Please advise.

**Comment by sahat** [comment]
Hey @charles-cai, I've heard great thing about [bunyan](https://github.com/trentm/node-bunyan), although I haven't used it myself yet.
