### ISSUE TITLE
Q: How do I change the default route (on successful login) from /api?

### ISSUE THREAD

**Issue by matthewjcable** [sahat/hackathon-starter#237]
I give up.   For the life of me (please excuse the node/express/etc newbie question) I cannot figure out where the default route is being set, and redirected to upon successful login?   At least upon login with e-mail and password, the site is redirecting to '/api'.   Where do I change that to a different route? For example '/'.

readying the facepalm...

**Comment by PgPedroGabriel** [comment]
In file config/passport.js has all login features. When a login is successfull passport return done.
If you are using the localStrategy in controllers/user.js u can see the function exports.postLogin on line 24, and inside of the scope you have passport.authenticate('local', function..... when passport return the done it can be a error or not, when error the return next(err) when don not has error and has a User finded req.logIn is executed, and 
```javascript
res.redirect(req.session.returnTo || '/');
```
is executed!
