### ISSUE TITLE
error: RPC failed; result=22, HTTP code = 400

### ISSUE THREAD

**Issue by od0** [sahat/hackathon-starter#239]
Getting a new issue when I try to run through the simple setup. I'm able to clone and run locally but can't deploy to Heroku. It may be something I'm doing wrong or misconfigured, but I've had success in the past deploying this template. Still love what you've done with this, just posting this in case others are having issues.

Setup (no errors):

$ git clone --depth=1 https://github.com/sahat/hackathon-starter.git myproject
$ cd myproject
$ git remote rm origin
$ npm install
$ heroku create
$ heroku addons:add mongolab

Then, pushing to heroku results in the following errors:

$git push heroku master
Counting objects: 177, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (169/169), done.
Writing objects: 100% (177/177), 902.75 KiB | 0 bytes/s, done.
Total 177 (delta 6), reused 177 (delta 6)
error: RPC failed; result=22, HTTP code = 400
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

**Comment by od0** [comment]
Sorry, false alarm - had a RTFM issue

**Comment by anupamsmaurya** [comment]
I am facing the same problem with the same project. Can you please share what solved your problem
