### ISSUE TITLE
user object in jade templates

### ISSUE THREAD

**Issue by rstormsf** [sahat/hackathon-starter#249]
It's not an issue, but would really love to see some information on how does `user` object gets into jade templates from controller without passing it as an object?

I see those lines in [app.js](https://github.com/sahat/hackathon-starter/blob/master/app.js#L82-L84):
```js
app.use(function(req, res, next) {
  res.locals.user = req.user;

  next();
});
```
but how do we get `req.user` ? where does it come from?

PS. Please join [Gitter](https://gitter.im)

**Comment by PgPedroGabriel** [comment]
Hackaton use passport.js to authenticate users, and by default the object that passport return is req.user (you can change this sending a option to passport);

(Look this link) [http://toon.io/understanding-passportjs-authentication-flow/]

**Comment by rstormsf** [comment]
thank you very much for pointing me to the right direction.
@PgPedroGabriel

**Comment by sahat** [comment]
Yeah as @PgPedroGabriel mentioned it is provided by the Pasport middleware when you initialize it.

```js
app.use(passport.initialize());
app.use(passport.session());
```
