### ISSUE TITLE
Please specify bootstrap version that you use in the project.

### ISSUE THREAD

**Issue by rstormsf** [sahat/hackathon-starter#251]
glyphicons-halflings-regular.woff doesn't look like it's there, but in BT3 it's included by default. I also wan't able  to identify the current version of BT.

**Comment by sahat** [comment]
You are correct I have not included glyphicons in favor of font-awesome. I should probably remove the `glyphicons.less` so it doesn't look like a "bug".

As for the version you can assume it's the latest one (3.3.2). I update `package.json` versions almost every week and JS/CSS dependencies whenever they become available.

**Comment by rstormsf** [comment]
ahhh, I see. so u update `package.json` and manually move assets to `vendor`'s folder?

**Comment by sahat** [comment]
Yeah that's what I did.

**Comment by sahat** [comment]
I went ahead and updated Bootstrap to 3.3.4 and Font-awesome to 4.3.0. While at it I added a short comment with the version number to `bootstrap.less`.
