### ISSUE TITLE
Modern theme link with :focus state just disappears

### ISSUE THREAD

**Issue by peterblazejewicz** [sahat/hackathon-starter#258]
The reason of this, is that  in modern theme the link in :focus state has the same @gray-dark color by default as background of footer component (the one missing is *GitHub Project* link):
![image](https://cloud.githubusercontent.com/assets/14539/6988457/ebb7a694-da51-11e4-9a7f-8bb852714690.png)
https://github.com/sahat/hackathon-starter/blob/master/public/css/themes/modern.less#L24
https://github.com/sahat/hackathon-starter/blob/master/public/css/themes/modern.less#L26-L28
https://github.com/sahat/hackathon-starter/blob/master/public/css/vendor/bootstrap/scaffolding.less#L54
https://github.com/sahat/hackathon-starter/blob/master/public/css/themes/modern.less#L40

The fix by adding :focus state:
https://github.com/sahat/hackathon-starter/blob/master/public/css/themes/modern.less#L26-L28

Can I make PR?

**Comment by sahat** [comment]
Hey @peterblazejewicz, sure I would appreciate the PR.
