### ISSUE TITLE
Mongo Db environment variable is named MONGOLAB_URI in heroku

### ISSUE THREAD

**Issue by sternert** [sahat/hackathon-starter#263]
Application unable to start because of this with default settings, adding MONGODB to heroku variable works or possibly adding check for MONGOLAB_URI in secrets.js.

**Comment by adammendoza** [comment]
Something internally is not using the MongoDB setting form the secrets.js

**Comment by sahat** [comment]
I will keep it as is since @adammendoza mentioned that he had a similar issue even with MONGOLAB_URI in secrets.js. Plus, what if someone is using Compose (MongoHQ) instead of MongoLab.
