### ISSUE TITLE
Error: CSRF token missing

### ISSUE THREAD

**Issue by alexleventer** [sahat/hackathon-starter#265]
Getting the following message when trying to use the Twilio API:
`Error: CSRF token missing`

**Comment by sahat** [comment]
Works fine here @alexleventer. I was even able to print the CSRF token out.

![screen shot 2015-04-24 at 5 08 03 pm](https://cloud.githubusercontent.com/assets/544954/7330509/8d165924-eaa4-11e4-9e90-adc1fc777dc3.png)
