### ISSUE TITLE
Can't render LESS code? 

### ISSUE THREAD

**Issue by DavidAwad** [sahat/hackathon-starter#266]
I downloaded and ran the code, it's running the server but when I try to render `home.jade` I get an error. What is the code responsible for compiling the LESS code? 

I can't get it to render unless i take out this line.  

I get the same error for `!= js('application')`

```jade
TypeError: /Users/david/Desktop/db-proj/views/layout.jade:8
    6|     meta(name='viewport', content='width=device-width, initial-scale=1.0')
    7|     title #{title} - Hackathon Starter
  > 8|     != css('main')
    9|   body
    10|     include partials/header
    11|

undefined is not a function

```

**Comment by sahat** [comment]
@DavidAwad LESS and JS compilation is handled by connect-assets (https://github.com/adunkman/connect-assets). Unless there have been breaking changes in connect-assets it should work correctly.

**Comment by sahat** [comment]
Just tested with the latest version of connect-assets 4.7.0 and works fine here.

**Comment by DavidAwad** [comment]
Got it. Thanks!
