### ISSUE TITLE
Google login - no email address

### ISSUE THREAD

**Issue by latitudehopper** [sahat/hackathon-starter#267]
It seems as if something may have changed with Google? It allows me to log in with Google but it will not populate the email box in the user profile. Is is that the email item returned is now an object?

**Comment by latitudehopper** [comment]
It seems as if changing the code in passport.js to

User.findOne({ google: profile.id }, function(err, existingUser) {
      if (existingUser) return done(null, existingUser);
      User.findOne({ email: profile.emails[0].value }, function(err, existingEmailUser) {
        if (existingEmailUser) {
          req.flash('errors', { msg: 'There is already an account using this email address. Sign in to that account and link it with Google manually from Account Settings.' });
          done(err);
        } else {
          var user = new User();
          user.email = profile.emails[0].value
          user.google = profile.id;
          user.tokens.push({ kind: 'google', accessToken: accessToken });
          user.profile.name = profile.displayName;
          user.profile.gender = profile._json.gender;
          user.profile.picture = profile._json.picture;
          user.save(function(err) {
            done(err, user);
          });
        }
      });

Works

**Comment by sahat** [comment]
Thanks, there must have been a change in passport-google-oauth package that changed the way you retrieve profile email. Should be fixed now.
