### ISSUE TITLE
is there any guide to configure secrets.js on AWS EC2 Instance?

### ISSUE THREAD

**Issue by chinmayrane** [sahat/hackathon-starter#269]
For other PaaS, It could be done through their Custom dashboards. For AWS EC2 However, I couldn't find any such help. 

Do I have to manually do a export NODE_ENV_XXX = YYYYY 

Or any startup bash script would also help!

Thanks and Cheers! :+1:

**Comment by sahat** [comment]
I don't have any experience with EC2, but I would imagine yes you would need to set it manually since EC2 is the most barebone infrastructure you can get. Perhaps create a script that runs on start-up which would export environment variables for you automatically.

**Comment by chinmayrane** [comment]
Thanks @sahat. 

Solved it using export `XXX_KEY == ActualKey` and then using,
XXX_Key in Secrets and using it everywhere. Standard Process, no hassles. :+1:

**Comment by sahat** [comment]
Cool, glad it worked!
