### ISSUE TITLE
how are express locals made available in public/js scripts?

### ISSUE THREAD

**Issue by gpolyn** [sahat/hackathon-starter#270]
How can express response locals to be read in client code? 

**public/js/blah.js**
```javascript
$(document).ready(function() {                                                                                                                                                                
   // read variables set here
});
```
...here I load the script in the page, using the connect-assets shorthand

**views/some-view.jade**
```
extends layout                                                                                                                                                                               
   !=js('blah')
  block content
  ...
```

**Comment by fonzarely** [comment]
Why not adding your code in main.js ?
Or you can add  this line in application.js : 
//= require blah.js

**Comment by gpolyn** [comment]
Oh, I just omitted that necessary step from my shown setup...

connect-assets seems to detach public/js from access to local variables in
the express.js response object, which are, of course, available in
hackathon-starters jade templates.

The point of the issue I'm raising is to confirm that there is not some
obvious thing I'm missing, that allows public/js scripts access to the
express response object.

**Comment by sahat** [comment]
@gpolyn You are correct, when you reference an external script, you cannot use local variables like you do in Jade templates and that has nothing to do with connect-assets. You have 2 options that I can think of:

1. Inline JS code inside Jade templates. That's what I had to use when I was first starting out with Node.js and web development in general. https://github.com/sahat/csc322/blob/master/views/profile.jade
2. From Jade, add `data-` attribute to your HTML elements with variable content, then read it from `blah.js`, e.g:
```js
 var example =  $('.container').data('example');
```

There could be other ways, but these are the only two ways that I know of for what you are trying to achieve.

**Comment by gpolyn** [comment]
@sahat thank your for confirming (and thank you for this resource!)

With respect to your comment...

*Inline JS code inside Jade templates. That's what I had to use when I was first starting out with Node.js and web development in general.*

...if you're implying that more mature approaches rely *only* on client-server http interface to exchange data, not sure I agree.
