### ISSUE TITLE
Adjusting app.js

### ISSUE THREAD

**Issue by mrmayfield** [sahat/hackathon-starter#275]
Hey, could I suggest initializing the express application before requiring the controllers in app.js? And then exporting the express application directly after initializing it to make it available to the controllers and other parts of the code? With the current way the app is initialized and exported it's automatically unavailable to be used by other scripts in the application. I can write this up if you'd like.

**Comment by sahat** [comment]
Hey @mrmayfield, I really don't to overcomplicate things more than necessary. Current approach is sufficient for most tasks, if you need to pass `app` to your controllers you are welcome to fork it and change it for your particular needs. After all, this is just a boilerplate project, and it would be impossible to satisfy everyone. What may seem like a good idea to you by implementing this change, someone else (especially Node beginners) will find it confusing, as I can clearly remember the pain of trying to understand the app flow with all those `module.exports` and passing `app` object around multiple files.

**Comment by mrmayfield** [comment]
Hey that's fine. If you're going for clarity and readability for a hackathon-starter, then it may be better but totally your call. I will probably fork it and change it for personal use :) thanks again for the app!
