### ISSUE TITLE
Jade vs. other templating engines

### ISSUE THREAD

**Issue by LeungEnterprises** [sahat/hackathon-starter#280]
I cloned this repo for a personal project and was wondering if some performance benefits could be realized by using a templating engine other than Jade (i.e. Handlebars)

Would there be a significant performance increase, or am I better off using Jade?

Thanks.
Nathan

**Comment by sahat** [comment]
@LeungEnterprises There isn't a significant performance increase. Also even if Handlebars is slightly faster, consider what you will be giving up from Jade. You will be writing a lot of Handlebars helpers which Jade can do out of the box.

**Comment by LeungEnterprises** [comment]
Thanks for the quick answer!
