### ISSUE TITLE
Error while pushing to heroku

### ISSUE THREAD

**Issue by anupamsmaurya** [sahat/hackathon-starter#282]
While deploying the app to heroku I am getting the following error

Counting objects: 166, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (163/163), done.
Writing objects: 100% (166/166), 609.68 KiB | 0 bytes/s, done.
Total 166 (delta 1), reused 166 (delta 1)
error: RPC failed; result=22, HTTP code = 400
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

I have already verified my heroku account and followed the steps given by you. Please help. 
git version 2.0.4

**Comment by sahat** [comment]
Did you download this repo and `git init` from scratch or did you `git clone` it?

For former there shouldn't be any problem if you are doing everything from scratch, but for later try the following steps.

There could be two reasons:

1) `git push heroku` is trying to push repo to **my** heroku app at *git remote set-url heroku git@heroku.com:hackathonstarter*. So try changing the git remote url to your repo:

```
git remote set-url heroku git@heroku.com:yourreponame.git
```

If that doesn't work, try the following command:

```
git fetch --unshallow
```

Let me know if that works for you, if it does, tell me which solution has worked for you so I could update the README.

**Comment by sahat** [comment]
Did you run `heroku login` and ` heroku keys:add`?

**Comment by anupamsmaurya** [comment]
Yes I did `heroku login`, `heroku create` and `heroku addons:create mongolab`

**Comment by sahat** [comment]
You mentioned everything but `heroku keys:add`. That's the only reason I know of that could give you permission denied error.

**Comment by anupamsmaurya** [comment]
remote: -----> Compressing... done, 29.4MB
remote: -----> Launching... done, v5
remote:        https://cakefull.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To git@heroku.com:cakefull.git
 ! [remote rejected] master -> master (shallow update not allowed)
error: failed to push some refs to 'git@heroku.com:cakefull.git'

**Comment by anupamsmaurya** [comment]
Using the first solution `git remote set-url heroku git@heroku.com:testapp.git` and then `heroku keys:add` seems to solve that problem. But now while pushing I get the following error at the end
remote: -----> Compressing... done, 29.6MB
remote: -----> Launching... done, v6
remote:        https://testapp.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To git@heroku.com:testapp.git
 ! [remote rejected] master -> master (shallow update not allowed)
error: failed to push some refs to 'git@heroku.com:testapp.git'

**Comment by sahat** [comment]
Have you tried following the instructions here? http://stackoverflow.com/questions/28983842/remote-rejected-shallow-update-not-allowed-after-changing-git-remote-url

If it is the case then I will need to update the README and remove `git clone --depth` from the getting started section.

**Comment by anupamsmaurya** [comment]
Ok finally its working now. I followed [this post](http://stackoverflow.com/a/29748753/456135)
1. Deleted .git directory
2. `git init`
3. `heroku login`, `heroku create` and `heroku addons:create mongolab` 
4.  `git remote set-url heroku git@heroku.com:testapp.git`
5. `heroku keys:add`
6.  did a dummy commit `git commit -m 'initial commit'`
7.  Finally `git push heroku master`

Thanks for your help and the wonderful artical

**Comment by sahat** [comment]
Ok, glad you got it working.
