### ISSUE TITLE
Algolia integration

### ISSUE THREAD

**Issue by Shipow** [sahat/hackathon-starter#284]
Hello Sahat,
I'm big fan of this project and learned everything I know about node/express using it.
I'm working as a designer at Algolia where we are building a search engine API. I think it could be a useful integration for a lot of project but I wanted to have your feeling about that. If so, I can make a PR very soon.

Here is small sideproject I've built using your code + algolia: http://realtime-search.com

What do you think?

**Comment by sahat** [comment]
Hi @Shipow, thank you for the kind words and your suggestion, however I am not looking to add new APIs at this moment. It's already slow as hell to start the express app, so I will need to figure out a way on how to cut down the loading times somehow.
