### ISSUE TITLE
JS Recipes broken link

### ISSUE THREAD

**Issue by rstormsf** [sahat/hackathon-starter#285]
I've noticed that JS Recipes link from README.md is broken http://jsrecipes.org/
Is this one correct one? http://sahatyalkabov.com/jsrecipes/#!/

**Comment by sahat** [comment]
Yes that domain has expired, but the site is still on GitHub and can be accessed with that URL you posted. I will update the README.

**Comment by rstormsf** [comment]
that's all I wanted to confirm. Thank you @sahat
