### ISSUE TITLE
Goolge Oauth

### ISSUE THREAD

**Issue by rstormsf** [sahat/hackathon-starter#286]
500 InternalOAuthError: failed to fetch user profile

:-( I followed the instructions and it just doesn't work :-(

**Comment by rstormsf** [comment]
For some reason it ONLY works with your Client Keys :-(

**Comment by sahat** [comment]
Did you set it up on google developers console correctly?

![screenshot 2015-06-19 17 55 53](https://cloud.githubusercontent.com/assets/544954/8265333/7bb4e108-16ac-11e5-927f-1180dda20927.png)

**Comment by rstormsf** [comment]
Yeap, tried it many times. 
When I click sign in, I get the auth window from google to accept that my app wants permissions, then I get error message that it can't fetch user profile. Tried creating another app in Google Console and getting new keys - the same thing :-( Feels like I'm missing some step. I copy/paste Client ID and Client Secret

**Comment by sahat** [comment]
Have you enabled Google+ in the API section of Google Console?

**Comment by fgaudenzi** [comment]
The Google+ API enabled fixs the problem, at least for me that i had the same issue.

**Comment by sahat** [comment]
Alright, I will update the README to make it more clear that you need to enable Google+ API.

**Comment by rstormsf** [comment]
thanks! works now
