### ISSUE TITLE
WebStorm IDE

### ISSUE THREAD

**Issue by rstormsf** [sahat/hackathon-starter#287]
What is the version of nodejs you are using to succesfully put a breakpoint on start?
I've tried a few version and can't get it working
I'm using WebStorm 10.0.4
I've tried 
stable -> 0.12 (-> v0.12.4) (default)
iojs -> iojs-v2.3 (-> iojs-v2.3.0) (default)
from `nvm`

**Comment by rstormsf** [comment]
I was just able to do it, but it took sooo much time :-(

**Comment by sahat** [comment]
Ok, closing the issue then.
