### ISSUE TITLE
js dependencies in parent directories

### ISSUE THREAD

**Issue by chrisvdb** [sahat/hackathon-starter#298]
I'm trying to use NPM for package management for both backend and frontend dependencies. I was trying to refer to the node_modules directory by doing something like

//= require ../../node_modules/async/lib/async

in public/js/application.js but unfortunately that does not seem to work. Any idea why?

I use the following workaround now, but it's not as elegant as I'd like it to be:

public/js$: ln -s ../../node_modules

**Comment by sahat** [comment]
My guess is that you can only reference files in the **public** directory or some other directory specified by the static middleware in Express. You may want to ask this question in https://github.com/adunkman/connect-assets.

**Comment by chrisvdb** [comment]
Ok, so the solution was to add the node_modules directory to the path initialization of connect-assets.

```
app.use(connectAssets({
  paths: [path.join(__dirname, 'public/css'), path.join(__dirname, 'public/js'), path.join(__dirname, 'node_modules'), path.join(__dirname, 'bower_components')]
}));
```

Maybe it would be a good idea to do this in hackathon-starter so front-end dependencies like boostrap and jquery can also be managed by NPM like all the back-end dependencies?

**Comment by sahat** [comment]
Thanks, that's good to know for future reference. As for your suggestion, unfortunately NPM does not have a lot of front-end libs, and I don't want to introduce Bower to the project.

Also, from a newbie perspective, I think it's a lot more straightforward to keep things separated: **public/js** for front-end packages, **node_modules** for back-end packages.
