### ISSUE TITLE
Linkedin Documentation Issues

### ISSUE THREAD

**Issue by xjackk** [sahat/hackathon-starter#299]
Just a small issue with the LinkedIn API. There has been some changes.

The default scope no longer requires you to have `r_emailaddress` and `r_network`

`r_fullprofile` has been depreciated. `r_basicprofile` is the updated version and it is the only thing required.

`r_emailaddress` is now optional 

![](http://i.imgur.com/l4DG2Lp.png)

^ Just fix here.

![](http://i.imgur.com/3CPzc1t.png)

^ Showing the new Default Permissions.

~ Cheers

**Comment by sahat** [comment]
Thanks I have updated the README.
