### ISSUE TITLE
image from google ouath

### ISSUE THREAD

**Issue by fgaudenzi** [sahat/hackathon-starter#301]
Hi Everybody,
Google+ response may be changed, indeed if you want to get the profile picture of the user when she logs with google credentials the passport.js file should be changed  around line 281 as  user.profile.picture = profile._json.image.url;
and as well around line 259 it should be
user.profile.picture = user.profile.picture || profile._json.image.url;

Cheers,
Filippo

**Comment by sahat** [comment]
Thanks I will take a look at it and fix it.
