### ISSUE TITLE
Pipeline javascript delivered twice

### ISSUE THREAD

**Issue by fenwick67** [sahat/hackathon-starter#304]
The javascript referenced in `public/js/application.js` is being served twice for me, once as separate files, and another time as the concatenated `application.js`.

This causes the bootstrap user dropdown to break, and will probably cause other problems.

I'm running the vanilla app on Heroku: http://quiet-shore-5131.herokuapp.com/

**Comment by sahat** [comment]
Thanks for reporting the issue. Connect-assets has changed some of its API for specifying assets paths. Should be fixed now.
