### ISSUE TITLE
Making it work for single page web application

### ISSUE THREAD

**Issue by djyadav** [sahat/hackathon-starter#305]
Can anybody help me how should I work around to get js and css files dynamically depending on the routes from front end only, in the development and production environment as well.

I am using jquery on the front end and planning to use some router package like as sammy.js or something else to make it single page. So, Will need to fetch the css and js files depening on the route.

**Comment by sahat** [comment]
@djyadav You should ask this type of question/discussion on StackOverflow or Hackathon Starter's Gitter chatroom. If it's not an issue or a bug with the project, it does not belong in Github issues.
