### ISSUE TITLE
Update passport-github and passport-instagram to 1.0.0

### ISSUE THREAD

**Issue by jaredhanson** [sahat/hackathon-starter#309]
Older versions of these two strategies depend on Passport core 0.1.x, causing outdated versions of req.login to be added to the HttpRequest prototype. This interferes with newer versions of Passport that have different internals.

**Comment by jaredhanson** [comment]
Let me know if this fixes the issue you mentioned [here](https://github.com/jaredhanson/passport/issues/400#issuecomment-133995617)

**Comment by sahat** [comment]
Thanks :+1:. That solved the problem.
