### ISSUE TITLE
NPM Install dysfunctional

### ISSUE THREAD

**Issue by mroknich** [sahat/hackathon-starter#313]
Following the getting started guide, after running node app.js, I get the following error: 
Error: Cannot find module './lib/express'

I thought maybe npm had missed a module and installed it manually, but found that there were numerous modules that followed. 

In other words, npm install ./lib/express results in another "Cannot find..." error. 

Thoughts?

**Comment by chinmayrane** [comment]
Please Check this. http://stackoverflow.com/a/20052517 :bowtie: 

Should help,
Cheers.

**Comment by mroknich** [comment]
Tried it. Didn't get the job done. npm install still results in errors and node app.js results in missing modules.

**Comment by sahat** [comment]
@mroknich Have you had this issue with any other project? I think this is something to do with your NPM setup. If Express package was indeed missing you should see the following:

```
Error: Cannot find module 'express'
```

And not:

```
Error: Cannot find module './lib/express'
```

**Comment by mroknich** [comment]
I think you're right. Running npm on the command line results in 

-bash: /usr/local/bin/npm: No such file or directory

**Comment by mroknich** [comment]
Followup...

an npm install results in the following, then it seems like it's pulling modules down correctly.

> kerberos@0.0.12 install /Users/matthewroknich/Documents/myproject/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/kerberos.node

> kerberos@0.0.12 install /Users/matthewroknich/Documents/myproject/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/kerberos.node
async@1.4.2 node_modules/async

bcrypt-nodejs@0.0.3 node_modules/bcrypt-nodejs

lusca@1.3.0 node_modules/lusca

**Comment by mroknich** [comment]
Running node app.js

Express server listening on port 3000 in development mode
MongoDB Connection Error. Please make sure that MongoDB is running.

/Users/matthewroknich/Documents/myproject/node_modules/connect-mongo/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

**Comment by sahat** [comment]
```
MongoDB Connection Error. Please make sure that MongoDB is running.
```
