### ISSUE TITLE
Add info on how to run tests

### ISSUE THREAD

**Issue by gianpaj** [sahat/hackathon-starter#315]
You have to run your tests using the `mocha` command instead of the `node` executable.

1. Install [mocha](http://mochajs.org/)

        npm install mocha -g

2. Run mocha form your project's root directory

        mocha

**Comment by sahat** [comment]
You can run tests via `npm test` and you do not need to install mocha globally.

**Comment by gianpaj** [comment]
I think you're right. I'm not sure why that didn't work for me the first time and returned a stacktrace.

**Comment by sahat** [comment]
@gianpaj That's probably because MongoDB was not running. I need to change that, unit tests shouldn't rely on the database in the first place.
