### ISSUE TITLE
Remove connect-assets, Switch to Sass, Node.js 4.0

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#317]
## Sass

This project used to have Sass stylesheets at some point but I had to revert it back to Less CSS due to io.js breaking [node-sass](https://www.npmjs.com/package/node-sass) compatibility with every release. Now that Node.js 4.0 is finally out, I think this is less of an issue.

Interestingly enough, according to this [blog post](http://ashleynolan.co.uk/blog/frontend-tooling-survey-2015-results) (9/9/2015), Sass is currently a preferred choice for the CSS preprocessor.

![](http://ashleynolan.co.uk/assets/img/blog/tooling-survey/2015/q1.jpg)

## Connect Assets

This leads us to connect-assets. I understand its usefulness, but it is also painfully slow and significantly affects start-up time for the application. This becomes an issue when you have to wait 3-5 seconds for your app to restart after making any changes. I would prefer to include `sass` middleware directly and not worry about automatic minification and concatenation of JS files. While you should always try to minify your assets and reduce number of requests for production-running apps, that's not an issue at all for smaller / hackathon projects.

I am opening this GitHub issue so we could discuss the changes proposed above, but if you like the changes then comment below with +1(:+1:).

**Comment by macleodsawyer** [comment]
+1 Let's do it!

**Comment by reesretuta** [comment]
:+1:

**Comment by chrisvdb** [comment]
- sass: +1
- connect-assets: the increased startup time is somewhat annoying but I would definitely miss the convenience...

**Comment by sahat** [comment]
**Load time with connect-assets**
<img width="70" alt="screenshot 2015-09-25 18 03 37" src="https://cloud.githubusercontent.com/assets/544954/10114976/d378a5f0-63af-11e5-9e2f-6693495ef87c.png">

**Load time without connect-assets**
<img width="58" alt="screenshot 2015-09-25 18 03 27" src="https://cloud.githubusercontent.com/assets/544954/10114977/d38b8300-63af-11e5-929d-34ed9b459896.png">

I would imagine the load time will again go up slightly after I add LESS or Sass stand-alone middleware, but still that's a pretty significant difference.

**Comment by sahat** [comment]
More or less consistent ~1600ms with the Sass middleware. Around ~1800ms when comping Sass files for the first time.

<img width="72" alt="screenshot 2015-09-25 18 22 43" src="https://cloud.githubusercontent.com/assets/544954/10115106/8b1c38fa-63b2-11e5-885a-f1311fc466c8.png">
