### ISSUE TITLE
Why do I keep getting this message when I try to sign in with facebook?

### ISSUE THREAD

**Issue by wyattbiker** [sahat/hackathon-starter#325]
"There is already an account using this email address. Sign in to that account and link it with Facebook manually from Account Settings."

Is something stuck in the cache?

**Comment by raunaqrox** [comment]
This happens if you have already connected with the same email on another social account like twitter or google.

**Comment by sahat** [comment]
@raunaqrox is correct. Another way to quickly fix this, for local development purposes, is to drop all your users from your local mongodb database:

```
db.users.drop()
```

This will remove all existing accounts in the database, so you can try to create and link your accounts again.

**Comment by flashsnake-so** [comment]
It also can happen when email does not successfully store in the user object.  It happened to me after changing the Facebook app id and secret to my personal Facebook app id.  I am still having trouble to get the public info even though the app request "email", "public_profiles" permission.
