### ISSUE TITLE
Change Ip localhost

### ISSUE THREAD

**Issue by jaider2523** [sahat/hackathon-starter#328]
Hi, how to do for change de ip localhost un this app, i need ser for an another ip...

Thaks for tour help.

**Comment by KevinBusse** [comment]
The app isn't bound to localhost, but instead listens to all enabled network adapters.
Also see [app.listen documentation](http://expressjs.com/api.html#app.listen)

    app.listen(app.get('port'), function() {
      console.log('Express server listening on port %d in %s mode', app.get('port'), app.get('env'));
    });

Everything else regarding to localhost can be found in config/secrets.js if you are referring to callback urls for api integrations.

**Comment by jaider2523** [comment]
Thanks Kevin !!!!.

**Comment by sahat** [comment]
Thanks for helping out @KevinBusse. Closing this issue.
