### ISSUE TITLE
`npm install` fails at bitcore if openssl not found

### ISSUE THREAD

**Issue by malcolmocean** [sahat/hackathon-starter#333]
```bash
checking for SSL... no
configure: error: openssl  not found.
make V=1
make: *** No targets specified and no makefile found.  Stop.
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v2.1.1
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node@1.0.0 install: `./bin/install`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the bitcore-node@1.0.0 install script.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
```

Everything worked fine when I removed the `bitcore` and `bitcore-explorers` deps.

**Comment by sahat** [comment]
I always install this OpenSSL library on Windows, which is why I haven't run into this issue.
http://slproweb.com/products/Win32OpenSSL.html

I may consider removing the *Bitcore example* if it is a blocker for people trying to get hackathon starter up and running.

**Comment by malcolmocean** [comment]
Yeah, or you could just make it an optional dep? Though that might be more if statements than you want. I ran into a few other vaguer issues getting rolling too, but they didn't seem worth writing home about. Mix  of npm-related stuff and google-oauth-related stuff (in order for it to work, you need to enable the Google+ API now, which was non-obvious) (also I wanted to use google APIs, which meant storing not just the access token but also the refresh token).

All in all was pleased to be able to get rolling this quickly though!

**Comment by sahat** [comment]
Definitely no for conditional dependency loading. I would rather remove it entirely than explain why there is a conditional statement to load a package.

Not sure if you read it, but there are instructions in the README on how to obtain API keys. Google instructions do mention that you need to enable Google+ API.
https://github.com/sahat/hackathon-starter#obtaining-api-keys

<img width="502" alt="screenshot 2015-11-09 13 18 39" src="https://cloud.githubusercontent.com/assets/544954/11042327/6a46eb16-86e4-11e5-8d78-2245ff93592e.png">

**Comment by malcolmocean** [comment]
Makes sense. Ahh, yeah, must have missed that.
