### ISSUE TITLE
Error: The `libsass` binding was not found

### ISSUE THREAD

**Issue by qpbp** [sahat/hackathon-starter#334]
Error reproduced when try to start server. Version of node.js is 5.0.0
```javascript
Error: The `libsass` binding was not found in /home/user/Projects/project/node_modules/node-sass-middleware/node_modules/node-sass/vendor/linux-x64-46/binding.node
```

**Comment by sahat** [comment]
Which OS are you running? If Mac, did you install Xcode + Command Line Tools, if Windows did you install Visual Studio? 

Need C++ compiler to compile a few certain node modules.

**Comment by qpbp** [comment]
I use the Linux Mint 17.2. What tools i need on Linux?

**Comment by sahat** [comment]
If it's like Linux then it should be `sudo apt-get install build-essential`.

**Comment by sahat** [comment]
It is documented in the README: https://github.com/sahat/hackathon-starter#prerequisites

**Comment by gfung** [comment]
I'm hitting this same problem in debian 8.3 and i have build-essentials installed as well as g++ to latest and yet i'm still hitting this error. I'm running nodejs lts (4.3.1). I have also tried rebuilding node-sass as suggested but to no avail.

**Comment by sahat** [comment]
@gfung can you post the entire logs from your Terminal when you run `npm install`? First, remove node_modules, try running `npm install` again, and then post all output here. It may have failed to install node-sass but still continued installing other npm modules as if nothing's happened.
