### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by austntatious** [sahat/hackathon-starter#343]
I'm having issues displaying hackathon-starter through nginx on an AWS EC2 instance.  The main issue is that the css is not displaying for some reason, and I continually get a 502 Bad Gateway error when hitting the domain name.

My Nginx configurations are the following -

server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name example.com www.example.com;

  location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://127.0.0.1:3000/;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect off;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_cache one;
        proxy_cache_key sfs$request_uri$scheme;
    }
}

**Comment by austntatious** [comment]
I've fixed the css problem running the node app as root acutally.  But I'm still receiving a WebSocket 400 Error on the client, which I'm assuming may still have to do with Nginx.  

Here's what the browser is reading:

WebSocket connection to 'ws://dispatch.nucleus.technology/socket.io/?EIO=3&transport=websocket&sid=B64mYIUw5eDKMe3JAAAM' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by niallobrien** [comment]
I think this issue should be closed as it's likely an Nginx config issue and not an issue with this repo.

**Comment by Nixhatter** [comment]
I was getting the same issue, but the problem stemmed from how I was starting the node project. I was using ```pm2 start app.js --watch``` 
where the watch command restarts on file change. This makes it restart every time I view the site in the browser. Removing the watch flag made it work with nginx, no problem.

For reference, here's my nginx config file:
```
server {
    listen 80;
    server_name subdomain.domain.com;

    location / {
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        Host $http_host;
        proxy_pass              http://127.0.0.1:3000;
    }
}
```
