### ISSUE TITLE
Missing public profile and email after switching to another Facebook App ID and Secret

### ISSUE THREAD

**Issue by flashsnake-so** [sahat/hackathon-starter#348]
After switching the Facebook App ID and secret to a new Facebook app just created.  The first name, last name, email and other information are not stored in the database.  I added myself and other developers as the administrator role that the app should work with getting Facebook app submission approval.  I also added these permission in passport setting:

```js
app.get('/auth/facebook', passport.authenticate('facebook', { scope: ['email', 'user_location', 'public_profile', 'publish_actions'] }));
```
I would like to know how the sample Facebook App should be setup.

Thanks,

**Comment by flashsnake-so** [comment]
I could see the callback was triggered in the log

```sh
GET / 200 555.312 ms - -
GET /login 200 121.888 ms - -
GET /auth/facebook 302 6.434 ms - 0
GET /auth/facebook/callback?code=AQClSc9AA83QtJjHPim4fGpBFkDpL2zZnmQSA9jbIRD5CdSUQOZKANXWHdVjFOfdpLJLFHUP7E88NUNW4ExEkD5Ks-mzOjRpKoKVf5Ljz_RGwQ6hh445LjW_O_NWIIzOH9Vnlp1delkSJYY1R5Gca1koJOc5h3vePGrbfEfAUeoO9t-pTkW52FGof_IFjwVSRa9DFY8tsjFuaVGsC0wipqjf1KLU3ZzO4AfneW6MLW_ORhijuwSTBNCjSnGnCdk25U0kCvEjVqEw0umwtccj6dJrwXHELJcB4y4tgaq25clr9H2pWrr70U-nmAACRhxyS1E 302 281.416 ms - 82
GET /api/facebook 200 363.986 ms - -
```

**Comment by flashsnake-so** [comment]
It is related to this thread:
https://github.com/mkdynamic/omniauth-facebook/issues/61

Need to modify the api.js to:
```js
    getMe: function(done) {
      graph.get(req.user.facebook + "?fields=name,email,first_name,last_name,gender", function(err, me) {
        done(err, me);
      });
    },
```

**Comment by sahat** [comment]
Hi @flashsnake-so,


Thanks, I was aware of the Graph API changes because I also maintain an authentication library [Satellizer](https://github.com/sahat/satellizer), but forgot to update it here in this project.
