### ISSUE TITLE
passport login

### ISSUE THREAD

**Issue by sundyxfan** [sahat/hackathon-starter#351]
Using email, and passport landing, first landing, and then re-enter the home do not need to visit, implementation of the withdrawal operation, then again to enter the page need to login, the process passport-local, do the what? How is the process? Why did the first landing again into the landing is not required?

**Comment by niallobrien** [comment]
Unfortunately, I cannot make sense of your comment.

**Comment by sahat** [comment]
@sundyxfan I also could not understand what you meant.
