### ISSUE TITLE
npm install - eats all available memory

### ISSUE THREAD

**Issue by uptownhr** [sahat/hackathon-starter#352]
I know this isn't really a bug related to hackathon-starter but I wanted to mention that `npm install` is not possible on a fresh Digital Ocean install. If using their 512mb size VM, the system runs out of memory during the npm install and essentially just crashes.

**Comment by sahat** [comment]
That's strange. I have never seen deployment fail due to out of memory issues. I have personally tried deploying this project to Heroku, OpenShift, Nodejitsu in the past, however, don't know much about Digital Ocean. I have only ever used their One-Click Install WordPress package.

The best I can recommend is to cut down on some APIs - remove them from package.json and from controllers/api.js. Hackathon Starter does use a lot of npm modules, but again, never have I experienced an out of memory issue.

**Comment by uptownhr** [comment]
I just tested again on a fresh Ubuntu 14.04.3 x64, with 512 MB ram ($5 plan).

Steps
1. Start droplet
2. SSH
3. `curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -`
4. `apt-get install -y nodejs`
5. apt-get install git -y
6. apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
7. echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
8. apt-get install -y mongodb-org

At this point `free -m` shows Total 490, Used 429, Free, 60

9. `git clone https://github.com/sahat/hackathon-starter.git`
10. `cd hackathon-starter`
11. `npm install`
12. Goes through loadDep ...
13. Starts extracting ... and stops at source-map -> gunz.
Outputs "killed"

I check `free -m` again, and now 399 is free. Checking for npm log and as the process was killed, none was created. node_modules directory is empty but contains a .staging directory with the downloads

14. I try and run `npm install` again.
15. Again goes through the loadDep and extraction but goes further to pre-install ... and stops at domutils
16. I tried to run npm install again, but it assumes all packages are now installed and finishes.
17. However, when attempting to run `node app.js`, get an error,
```
/root/hackathon-starter/node_modules/node-sass/lib/extensions.js:158
    throw new Error([
    ^

Error: The `libsass` binding was not found in /root/hackathon-starter/node_modules/node-sass/vendor/linux-x64-47/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/root/hackathon-starter/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/root/hackathon-starter/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/hackathon-starter/node_modules/node-sass-middleware/middleware.js:3:12)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/hackathon-starter/app.js:21:12)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

18. I run `npm rebuild node-sass`
19. `node app.js`, application finally runs and listening on port 3000 in development mode is displayed. 

Again I know this isn't a hackathon-starter project issue but I wish there is a way to address this. Maybe I should bring this up with the npm guys.

**Comment by sahat** [comment]
This could be related to node.js version. Do you know which version  is Digital Ocean using?

The only time I saw that error is when I installed npm dependencies via `npm install` using Node.js 4.2, and then reverted back to Node.js 0.10 using [**n**](https://github.com/tj/n) version manager.

But I suppose it could also be because node-sass was not installed properly, as you are saying due to the install process being killed.

**Comment by flashsnake-so** [comment]
I am seeing the same error when deploying this project to AWS Elastic Beanstalk.
