### ISSUE TITLE
css not loading

### ISSUE THREAD

**Issue by dogmatic69** [sahat/hackathon-starter#356]
I have tried to set up this project in docker. got it mostly working apart from the CSS.

/css/main.css wont load, its being generated correctly. I have made sure all the permissions are the same as the other files also

If I cat the file into something else, say tmp.css I can load the file in a browser (localhost/css/tmp.css)

I then delete the main.css and issue 'mv tmp.css main.css' and try the app again, with no css loaded still

In google chrome I am just getting `ERR_CONNECTION_RESET` when trying to open main.css directly

If I try and load a made up file name I get an error like 'Cannot GET /css/asdfasd.css' in the browser

**Comment by sahat** [comment]
Sounds like a docker container issue with permissions. This is outside of my scope to help you unfortunately. So feel free to close the issue, and/or post the solution if you ever figure it out.
