### ISSUE TITLE
Fork with additional features

### ISSUE THREAD

**Issue by niallobrien** [sahat/hackathon-starter#357]
Hi all, just letting you know that I've done some work on a fork to add additional features.

So far I've:
- Added MVC structure
- Moved routes to config/routes.js
- Added Webpack & Gulp asset pipeline
- Added Pjax
- Added CORS support

Please let me know what you think, or if you have any requests - I've more features on the way.

https://github.com/niallobrien/briskjs

**Comment by sahat** [comment]
Thanks for sharing @niallobrien, but this is not the right place for it. I would like to keep it as a place for bugs and issues with the project.

I am glad however to see the project still going strong and people still fork it to make their own custom project boilerplate.
