### ISSUE TITLE
How to use mongoose data in express render

### ISSUE THREAD

**Issue by elkebirmed** [sahat/hackathon-starter#358]
I need to pass the user name as a title to the rendered jade page in this [line](https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L122)

**Comment by elkebirmed** [comment]
Solved: `req.user.name` FACE_PALM :open_mouth: :

**Comment by sahat** [comment]
Yep, as you have discovered, there is an Express middleware that adds user object to `locals` for easy access inside templates, so you don't have to pass it yourself every single time.

```js
app.use(function(req, res, next) {
  res.locals.user = req.user;
  next();
});
```

**Comment by elkebirmed** [comment]
Thank you @sahat
