### ISSUE TITLE
Update Guide

### ISSUE THREAD

**Issue by isabasan** [sahat/hackathon-starter#371]
A guide may be good for updating from an old version to latest version for live projects or under development projects.

**Comment by sahat** [comment]
@isabasan Which part of the guide are you referring to?

**Comment by isabasan** [comment]
I didn't refer to any part of current readme.md.

I mean that, "updating guide" may be good. It will be a new part.

**Comment by sahat** [comment]
Nah, I don't think we need an update guide. If this was a library or a framework, sure. But this is just a boilerplate project. The idea is that you **fork it**, customize it anyway you like: don't like Jade? Swap it with Handlebars. Don't need all OAuth providers? Just remove them and keep only what you need. And etc.

Most of the updates that I do are minor - readme fixes, code cleanup, adding new API once in a while. None which justified having an upgrade guide.

**Comment by isabasan** [comment]
Ok. Thanks for your attention.

**Comment by niallobrien** [comment]
For the record, with regards to updating an existing repo, so long as you make incremental changes, I've found that I can easily merge in the latest changes.
