### ISSUE TITLE
Problem with user authenfication

### ISSUE THREAD

**Issue by skatch** [sahat/hackathon-starter#373]
Hi sahat,

Thank you for this boilerplate. I am trying to use it for my new app so I modify some things. 
I have got an issue when I try to log in as a user, sometimes it works with sucessful message sometimes it doesn't work with no message. When it's not working I try to login again and then it works.
Do you have any clue why? I haven't done some modification to your user authentification system.

Thanks in advance

**Comment by sahat** [comment]
@skatch Can you provide additional information? Perhaps a video screencast that can consistently reproduce the issue? If it's not reproducible, there is no way for me to know why it is happening or how to fix it.
