### ISSUE TITLE
Package.json parsing error

### ISSUE THREAD

**Issue by chromonav** [sahat/hackathon-starter#375]
Hi,
Could not install package error because of error parsing json
![544](https://cloud.githubusercontent.com/assets/5052568/12985983/0ae0d3b8-d11b-11e5-95cf-932cd937da8e.PNG)
Windows 10

**Comment by sahat** [comment]
What is node-express-mongoose? Is this even about hackathon starter? The *package.json* in this project is fine, I don't see any missing commas that would throw JSON parsing error.

**Comment by chromonav** [comment]
oh i am sorry. different lib
