### ISSUE TITLE
I'm just asking about adding pjax to this web app (HOW TO????!)

### ISSUE THREAD

**Issue by elkebirmed** [sahat/hackathon-starter#376]
This is my question on [StackOverFlow](http://stackoverflow.com/questions/35348160/jquery-pjax-is-not-working-on-express)

can you help me @sahat ?!!

**Comment by sahat** [comment]
Please keep these issues relevant to the project. Your question is general enough that anyone can help you with that on StackOverflow. If you have something specific you want to ask me, send me an email and I will try to reply.

**Comment by elkebirmed** [comment]
Ok, but what about a little help on StackOverFlow, come on, just give me a small idea
