### ISSUE TITLE
Bower for assets dependencies

### ISSUE THREAD

**Issue by paulodiovani** [sahat/hackathon-starter#379]
I think it will be much easier to let Bower install assets dependencies, like:

- jQuery
- Bootstrap
- FontAwesome

What do you think?

**Comment by niallobrien** [comment]
I disagree. NPM is much better.

**Comment by paulodiovani** [comment]
I think bower is better for front/assets, since it forbids conflicting versions, allow to install on different folder and may also deal with dependencies outside the registry (any github repository, any cdn or any downloadable archive can be a valid bower module).

But anyway,
The problem I see here is that the assets are being commited to the repository.

**Comment by sahat** [comment]
This has already been discussed in https://github.com/sahat/hackathon-starter/issues/179. I am all in favor of having the least amount of abstractions. Consider this: you just started this thread, but we already have a disagreement as to what's better: bower or npm. @niallobrien prefers npm, and @paulodiovani prefers bower.

It's fine to disagree with the current approach of committing assets to the repository, but you can't argue about the fact that it is very simple and easy to understand and requires minimum mental overhead - clone the repository, run `npm install`, run the app; everything just works out of the box. 

Hackathon Starter has over 1,800 forks, everyone is free to modify it any way they see fit, and I highly encourage you to do that. My goal for Hackathon Starter is to make it stupid simple and extremely easy to get started with. In this case that means no bower, no gulpfile, no webpack, no babel.

**Comment by paulodiovani** [comment]
I see your point @sahat.
And since Hackathon Starter is intended to be a start place for easy extending make much sense to keep complexity out.

I'm closing the Issue.
Thanks.

**Comment by sahat** [comment]
:+1:
