### ISSUE TITLE
Profile Update Bug

### ISSUE THREAD

**Issue by Octales** [sahat/hackathon-starter#393]
First off, Thank You ! for this wonderful repo . Even though I just starting using JavaScript <= 1 month, I wanted to learn by doing and decided to use your repo. The thing is I found myself struggling with the Profile Page. When you update the Name the email becomes useless and you can't login with the name either since it wants to validate the email on the login page.
I deleted user.email = req.body.email || ''; and the email form from the profile update page and "fixed this issue". Another thing that is bothering me and i can't wrap my head around it is that i want to make all profile fields unique and i can't manage to make them unique. Also I would like to replace the Email Password Login with Username, Password and the Email should be inside the Profile Page. 

Thank you in advance for any Pro tips that you will provide!

**Comment by sahat** [comment]
Hi @Octales,


1) Could you clarify how email field becomes useless when you update the name? Hackathon Starter does not use your name for login, but rather your email.

2) Making all fields unique means no user can have the same name, the same location, the same gender, the same website. Not sure how that is useful, but uniqueness can be enforced in the User schema via `unique: true`.

3) If you want to use username, remove this object usernameFrield in passport.js config:
https://github.com/sahat/hackathon-starter/blob/master/config/passport.js#L80

Of course you will also need to update all fields from `email` to `username`. For more information check out passport.js examples. Those examples use username field by default.

**Comment by Octales** [comment]
1) Sorry i meant that if you delete the email from the profile page you can never log back into the account. In the current setup an email should always be provided and never left undefined.
2) Again sorry for the bad writing, i only wanted a unique field added such as a Nickname and i tried the unique:true part but got some errors and thought that i needed more configuration added to the Schema or somewhere else.
3)Thank you for the clear solution on how to replace the email with the username.

Keep up the good work and once again thank you for sharing your amazing startup project.

Cheers !

**Comment by Octales** [comment]
Hey man, I have added a Username and kept the email form but i can't properly mitigate the flash errors i get when both fields are duplicated and not unique ... I can't manage to code a function that validates Username, Email, Password and Profile Information that contains Nickname and ProjectName that are unique now. I get this error or crash when i try to enter an already existing Username,Email,Nickname etc. 
MongoError: E11000 duplicate key error index: test.users.$profile.name_1 dup key: { : "" }

I copied the previous validation function http://pastebin.com/i1ArsDwY and it works fine if I get only one individual unique error. Thank you for any support you can provide.

**Comment by sahat** [comment]
@Octales I just update the controller file. I think this may be what you are looking for?

```js
if (err) {
  if (err.code === 11000) {
    req.flash('errors', { msg: 'The email address you have entered is already associated with an account.' });
    return res.redirect('/account');
  } else {
    return next(err);
  }
}
```
