### ISSUE TITLE
Intercom integration

### ISSUE THREAD

**Issue by maithreya** [sahat/hackathon-starter#399]
Hey i am wondering would you be able to do intercom integration as its getting super popular and makes perfect sense for what you are trying to do

**Comment by sahat** [comment]
I am not familiar with Intercom. What can you do with their API?

**Comment by maithreya** [comment]
Its a really cool product to understand your user. I know you have built this for hackathons but i am using it in production. Check them out www.itercom.io

**Comment by sahat** [comment]
Sounds interesting, but non-essential for Hackathon Starter. There was a similar PR in the past to add a commercial analytics/user tracking product integration which I had to politely decline.
