### ISSUE TITLE
bower setup

### ISSUE THREAD

**Issue by twilly86** [sahat/hackathon-starter#411]
I was able to get bower working with this project using a postinstall task in package.json.

Would you be interested if I created a pull request for this?  

I wanted to ping you first to see if it's the right move.

**Comment by niallobrien** [comment]
Personally, I no longer use Bower for frontend assets and the community at large are slowly migrating to npm.

**Comment by sahat** [comment]
Previous discussions: https://github.com/sahat/hackathon-starter/issues/379 and https://github.com/sahat/hackathon-starter/issues/179. I am not planning to add Bower to this project.

Besides, modern workflow using React (universal apps in particular) and Angular typically use npm for package dependencies these days.
