### ISSUE TITLE
Forgot Password Account Disabled 500 Error

### ISSUE THREAD

**Issue by ajmueller** [sahat/hackathon-starter#412]
When you submit a Forgot Password request [the Forgot Password page](http://hackathonstarter.herokuapp.com/forgot) for a valid email address, you get this error:

![screen shot 2016-03-19 at 12 48 38 pm](https://cloud.githubusercontent.com/assets/1442179/13900977/eb3ba7ae-edd0-11e5-930c-8bc8cb16fe9a.png)

It would appear that this could be related to #410.

**Comment by sahat** [comment]
I'll close this issue and continue the conversation in #410. You are right, it is the same issue.
