### ISSUE TITLE
Add localisation support

### ISSUE THREAD

**Issue by Doogiemuc** [sahat/hackathon-starter#414]
Your starter templat is really great!  Just one more suggestion: You should add support for locasiation. For example via this very small little library: https://github.com/martinandert/counterpart
Or the larger more advanced  jade-i18n  or even larger  i18next.com  library.

**Comment by sahat** [comment]
Hi @Doogiemuc, adding i18n is unfortunately a big task requiring big changes in the project. Every string and paragraph will need to be tokenized. I am not sure it's worth the effort or complexity for most of users. I don't have any data, but I would wager most people only ever use one language, even if it's the language other than English.

In short, my original focus for this project is intended for hackathons/small projects, and at this stage i18n is unnecessary complexity that most people don't need.
