### ISSUE TITLE
IDE Hang

### ISSUE THREAD

**Issue by rhettl** [sahat/hackathon-starter#417]
Hey, 

This is likely not directly a sahat/hackathon-starter problem, but I cannot open this in Webstorm v11.0 on Mac 10.11.3.

First I used terminal to `git clone --depth 1` the repo and `npm installed` from the created project root. Then I opened the project and at the indexing phase of webstorm's startup, it froze. I worked on other things for 2 hours to give it time just in case it took a REALLY LONG TIME to load -- no luck.

So I forced quit webstorm,  deleted `./node_modules/` from the terminal, and started webstorm again. This time everything was fine, but I didn't have `./node_modules/`. I ran an `npm install` from the terminal and 1/3 of the way through install, the bar froze, as did webstorm. I let it sit for another hour or so, just in case.

```
$ node --version
v4.2.2
~
$ npm --version
3.4.0
```

Thanks

**Comment by rhettl** [comment]
Update: 

For some reason, it now hangs without `./node_modules/` too.

My first instinct is that @sahat/hackathon-starter is unrelated and it is a Webstorm issue, but this doesn't happen on any other project, created on the machine or cloned, with git or without.

I updated to Webstorm 2016.1 and followed the steps [here](https://www.jetbrains.com/help/phpstorm/2016.1/cleaning-system-cache.html?origin=old_help) to clear cache which might prevent proper indexing, but the issue still persists. 

Thanks for any advise

**Comment by sahat** [comment]
Not sure why you are having that issue. I am running both IntelliJ 15 and WebStorm 2016.1 and I have never had IDE hang on any of the projects.

Closing this issue since there is nothing actionable. I would investigate the problem further on your end. Try resetting your Webstorm settings.
