### ISSUE TITLE
Deploying to Heroku - Mongoose or Mongodb bug?

### ISSUE THREAD

**Issue by miguelcarvajal** [sahat/hackathon-starter#42]
Nice app, great work. I am learning a lot of Express, Javascript and Node.js with your Hackathon Starter Boilerplate. But I have an issue that I don't know if it is my problem or some bug in the code. When I deploy to Heroku everything seems to be cool, but then the app crashed: http://calm-shelf-8699.herokuapp.com/

```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

When I do run `nodeman` or `foreman` in Localhost I don't have any problem and the App works just perfectly. Doing some research trough inspecting the `heroku logs` I've found the message `MongoDB Connection Error. Please make sure MongoDB is running`. So I don't know if my problem is in the app.js file or is in the Heroku environment or that I don't know enough code to set the Mongolab conection. 

Thanks for the great work @sahat!

**Comment by adekola** [comment]
Hi Sahat. 

Thanks for making available such an amazing boilerplate for Nodejs Applications.
I have set up the project on my local machine (which works perfectly) and deployed to Heroku as well. However, the heroku deployment fails even though I have MongoLab set up with the MONGOLAB_URI pointing to the db connection string on my MongoLab account.

Still, I get an application error each time I attempt to access the application.

What could I be doing wrong?

Looking forward to your response.

Thanks.
