### ISSUE TITLE
Add Trello authentication

### ISSUE THREAD

**Issue by tillda** [sahat/hackathon-starter#420]
It would be nice to add Trello OAuth capabilities. You can do all sorts of interresting things with their API.

**Comment by sahat** [comment]
@tillda Would you like to submit a PR? If you are, then just add Trello authorization, similar to how Foursquare and Pinterest are implemented. In other words, users will be asked to sign-in with Trello when they visit Trello API example, but there won't be an additional Passport strategy for signing in. There is plenty of other sign-in options already.

**Comment by sahat** [comment]
@tillda Would you be interested or should I close this issue?

**Comment by sahat** [comment]
Closing this issue since I haven't heard back from you in a while.
