### ISSUE TITLE
Action on err in last function of a waterfall

### ISSUE THREAD

**Issue by postjohannes** [sahat/hackathon-starter#421]
In the UserCtrl you use waterfall. In the last function there is if(err) but err is not the same as the err returned by eg Mongo.save. The err here contents is err.message = 'success'. This is the value returned bij the for-last function (in case when using SendGrid). Just pass null in staid of the Object err.

**Comment by sahat** [comment]
@postjohannes Which line in particular are you referring to that returns `err.message = 'success'`?

**Comment by postjohannes** [comment]
At line 317 and 395 the err Object is passed to done()  ( done(err, 'done'); ) But the err Object is: { err.message: 'success' }.
So the err Object in the next entry off the waterfall is not null, and het response is never reached.

**Comment by sahat** [comment]
@postjohannes Why would nodemailer set error object to `message: 'success'? According to https://github.com/nodemailer/nodemailer#tldr-usage-example, `sendMail` callback returns an error object as the first argument. I understand `'done'` string is irrelevant but it doesn't explain why `err` is not null instead.

I tested password reset flow just now and everything works as expected.
