### ISSUE TITLE
ES2015

### ISSUE THREAD

**Issue by misund** [sahat/hackathon-starter#422]
It would be nice to be able to use ES2015 syntax in cloned projects

**Comment by sahat** [comment]
Hi @misund, thanks for the effort, but I am not ready to migrate this project to ES6 yet. For the same reason I do not want to add Gulp and Webpack, I see Babel as an extra overhead. Node.js 4.x and 5.x already support a lot of ES6 features, so if anything I will use that directly.

ES6 is also more than just changing `var` to `let`/`const`. I would have to go through every line and re-write it in a "ES6 way", e.g. changing `async.waterfall` to promises, using destructuring operator, named parameters, template strings and a lot other nice features.

I myself write ES6 and ES7 code using Babel on a daily basis, but I really like the simplicity of Hackathon Starter in that you don't need a bunch of tools and packages just to get started. AFAIK, it still works with Node.js 0.10 and 0.12.
