### ISSUE TITLE
Facebook login is not updating user name

### ISSUE THREAD

**Issue by spotitdata** [sahat/hackathon-starter#431]
At present facebook login is not taking profile name : please update as below:

$ diff passport.js passport.js.old 
77,78c77
<           user.profile.name = profile.name.givenName + ' ' + profile.name.familyName;
---
>           user.profile.name = user.profile.name || profile.displayName;
102,103c101
<           user.profile.name = profile.name.givenName + ' ' + profile.name.familyName;
---
>           user.profile.name = profile.displayName;

And thanks for such a great work

**Comment by sahat** [comment]
Thanks for reporting this issue. I have already [updated](https://github.com/sahat/boilerplate/blob/master/generators/authentication/modules/facebook/facebook-strategy-mongodb.js) that part of the code in my other project, but never got a chance to do it in the Hackathon Starter.
