### ISSUE TITLE
Aviary error in Live Demo

### ISSUE THREAD

**Issue by mritterhoff** [sahat/hackathon-starter#434]
When I go to http://hackathonstarter.herokuapp.com/api/aviary and click "Edit Photo" I receive the following popup: 
![image](https://cloud.githubusercontent.com/assets/7176906/14724898/c3a1830a-07cd-11e6-80f9-3f0ca37eafa7.png)
"There was a problem loading your image provided by URI to the 'url' config key. It is not reachable by the public (and our service at http://featherservices.avairy.com/)"

There's also a javascript error "Uncaught SyntaxError: Unexpected token :"

I understand this is a demo, and so I'm uncertain if this is expected behavior. If it is, some warning on the page to explain this might be useful.

**Comment by sahat** [comment]
Hi @mritterhoff, that's definitely not an expected behavior. What's normal though is for APIs to change or even shutdown completely, e.g. Mandrill shuts down free tier mail service. With so many different APIs used in the hackathon starter, I usually get notified that something is broken when someone reports it.

**Comment by sahat** [comment]
Ah, there is your answer:

> Where can I find the Aviary SDK?
January 18, 2016 16:08
Adobe Creative SDK   Common Questions
The Aviary SDK is now the Image Editing component in the Adobe Creative SDK. Visit creativesdk.adobe.com to access the latest Image Editing SDK and brand new SDK components by Adobe, offering features like store to Creative Cloud and publish to Behance.
If you’re updating an existing Aviary SDK integration to the Creative SDK, please visit our Migration Guide here.
