### ISSUE TITLE
ES6: Yes / No? [Poll closed]

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#439]
Now that [Node.js 6.0.0 is released](https://nodejs.org/en/blog/announcements/v6-release/?release), what do you all think about the idea of rewriting this project in ES6? (#422)

I am trying to get an idea of how many people still prefer writing ES5 code, and how many of you would rather work with ES6?

![capture](https://cloud.githubusercontent.com/assets/544954/14838884/d3fd286a-0bf3-11e6-9465-4bcdf04914f8.PNG)

**Comment by uptownhr** [comment]
yes

**Comment by chidoneto** [comment]
[image: :-1:] = *No, please keep ES5*

**Comment by w1f7UBC** [comment]
Yes

**Comment by RobinsonKameron** [comment]
Sí

In light,

Kameron Robinson
B.S. Information Systems, UMBC 16’
Ka12@umbc.edu
667-203-5897

**Comment by prashcr** [comment]
Would love to help out, if needed.

**Comment by Octales** [comment]
Would be nice if you kept ES5 while having fun with ES6 or 7 :)

**Comment by sahat** [comment]
@Octales If we move forward with ES6, I will keep ES5 version around in a separate branch (unmaintained).

**Comment by Octales** [comment]
I agree, I'm willing to move to ES6 but I'm sure there will be some people that might still want to play around with ES5 even unmaintained, just add it the readme and move !

**Comment by prashcr** [comment]
A point that came to mind.

I'm against transpiling server side code (build process adds too much complexity, hinders debugging since stack traces don't correspond to source anymore).  
  
We should aim to support the latest stable Node.js natively. This will help: http://node.green/

**Comment by sahat** [comment]
@prashcr Absolutely. The only reason why I proposed this change is because of Node.js 6.0 release. That's also why #422 was closed.

**Comment by Octales** [comment]
If hackathon-starter didn't exist, I would not be around learning JS at all. Thank you for all your hard work, I'm sure the ES6 version will be way more awesome :)  Keep up the good work :+1:

**Comment by sahat** [comment]
@Octales Thank you. I understand how you feel. This project was built when I had less than a year of JavaScript experience, hence the focus on simplicity. The more experienced you become in a particular subject, the harder it becomes to connect with that "beginner's mindset".

---

On a related note, there will be something even better than Hackathon Starter **next month**. Imagine you could add Gulp, Webpack or simply use NPM scripts for compiling Sass, LESS, PostCSS. How about adding AngularJS or React + Redux + Hot Reload + Server-side rendering? Don't like Jade, then go ahead and use Handlebars or Nunjucks. Don't like MonogDB, then choose one of the relational databases - PostgreSQL, MySQL, SQLite. How about a CSS framework? You are free to choose between Bootstrap, Foundation frameworks or a completely unstyled design. Want unit tests? Choose Mocha or Jasmine. So, while you could create a "Hackathon Starter" (without API examples) boilerplate using this tool, it is so much more than that!

**Comment by kyawagwin** [comment]
Yes

**Comment by whitef0x0** [comment]
Yes

**Comment by maluramichael** [comment]
Yes

**Comment by firebotQL** [comment]
Yes

**Comment by leodido** [comment]
Yes.
And glad to help.

**Comment by Rhymond** [comment]
Yes

**Comment by chidoneto** [comment]
In that case, I'd say Yes!

Thanks for your contribution.
     --Carlos

**Comment by sahat** [comment]
Should I use [AirBnb's ES6 style guide](https://github.com/airbnb/javascript) or is there something better out there?

**Comment by prashcr** [comment]
This is also worth a look. No eslint/jshint required.
And there are CLI tools for auto-formatting
https://github.com/feross/standard

**Comment by Gum-Joe** [comment]
@sahat You might want to have a look at mohebifar/lebab - it converts ES5 code to ES6 code. I tried it with `app.js` and all the `require()` statements were converted to `import x from x`, except the one where  it was in the form of `require('x')(y)`. Quite accurate.

**Comment by prashcr** [comment]
@Gum-Joe  We don't want to convert `require()` to `import x from x` though. Node.js doesn't support `import` yet. It does however let you choose which features to convert, so it looks promising.

**Comment by niallobrien** [comment]
@sahat Care to share some info on this new project?

**Comment by Gum-Joe** [comment]
I would say yes to es6

**Comment by niallobrien** [comment]
Should we just start to slowly refactor? What features of es6 will we use? Classes, promises or generators etc.?

**Comment by Gum-Joe** [comment]
Should I open a pull request to start refactoring? I can probably use lebab to convert most of the code, but I will need help after that, so that I can understand the code and how it works.

**Comment by sahat** [comment]
Ok, I started off with converting [**app.js**](https://github.com/sahat/hackathon-starter/blob/es6/app.js) on `es6` branch. I am using AirBnb's style guide with a few exceptions. I may add more exceptions to the list.

#### .eslintrc
```json
{
  "extends": "airbnb",
  "rules": {
    "comma-dangle": 0,
    "no-console": 0,
    "no-param-reassign": 0,
    "max-len": 0
  }
}
```

As I've previously mentioned I am currently working on another project which I am planning to release in a few weeks, so if someone could help out with converting the remaining code to ES6, I'd appreciate it! 

Go ahead and send a pull request against the `es6` branch. I will review and merge it there first. Please try to not to make too many changes not related to ES6. Also be careful with async + callbacks vs native ES6 promises - which one makes code easier to read? If it's the former, then it should be left alone as is. But if promises can simplify the code, then it should be used over caolan's async library. If you are going to refactor the following code using something like ES6 destructuring, try to keep in mind "will this change make code simpler or more complicated to read?"

```js
var artist = {
      name: results.artistInfo.artist.name,
      image: results.artistInfo.artist.image.slice(-1)[0]['#text'],
      tags: results.artistInfo.artist.tags.tag,
      bio: results.artistInfo.artist.bio.summary,
      stats: results.artistInfo.artist.stats,
      similar: results.artistInfo.artist.similar.artist,
      topAlbums: results.artistTopAlbums,
      topTracks: results.artistTopTracks
    };
```

**Tip:** Keep newbies in mind who may be just starting out with Node.js or JavaScript for the first time!

Thanks,
Sahat

**Comment by prashcr** [comment]
I'm working on `api.js`, will submit PR in a day or two.  
  
If you're using Sublime Text, converting functions to arrow functions is as easy as  
Find What: `function\(([^\)]*)\)`
Replace With: `\($1\) =>`  
  
Another issue I realized with destructuring, apart from readability, is with regards to node-style callback error-handling. It was pretty tempting to do this in a lot of cases:  
```
(err, { books, authors }) => ...
```
Instead of 
```
(err, results) => ...
```  
  
However, in the event of an error, you'd get
```
Uncaught TypeError: Cannot match against 'undefined' or 'null'.(…)
```
as JS eagerly evaluates function arguments

**Comment by sahat** [comment]
#### :white_check_mark:  [**`ES6`**](https://github.com/sahat/hackathon-starter/tree/es6) branch is ready to be merged and I would love some feedback on it.

Many thanks to @vanshady and @prashcr for the pull requests. I made a few slight changes across all files in proposed PRs. Unit tests have been updated and Travis-CI builds should be passing.

**Comment by niallobrien** [comment]
Awesome stuff. Have any of you guys played with ES6 generators?

**Comment by Gum-Joe** [comment]
@niallobrien Have a look at [https://davidwalsh.name/es6-generators](https://davidwalsh.name/es6-generators): it explains what generator functions are and how to use them.
