### ISSUE TITLE
Error with dependence 'node-sass-middleware'

### ISSUE THREAD

**Issue by ChrisVent** [sahat/hackathon-starter#447]
I had to include in 'package.json' dependence 'node-sass' because when running the application in version '0.10.44' of Node throwing error reliance 'node-sass-middleware', and installing (" node-sass ":" ^ 3.6.0 "), the error is solved.

The error :

```
fs.js: 666
   binding.readdir return (pathModule._makeLong (path));
                  ^
Error: ENOENT, no such file or directory'/home/chrisvent/Github/hackathon-starter/node_modules/node-sass-middleware/node_modules/node-sass/vendor'
```

**Comment by ChrisVent** [comment]
#446 Fixed In second commit

**Comment by sahat** [comment]
@chris-ramon Isn't node-sass installed as a dependency of node-sass-middleware? https://github.com/sass/node-sass-middleware/blob/master/package.json#L34

**Comment by chris-ramon** [comment]
@sahat I think you meant @ChrisVent instead. :smiley:

**Comment by sahat** [comment]
Sorry! That's what you get for blindly trusting Github's autocomplete feature.
