### ISSUE TITLE
GitHub API example broken locally

### ISSUE THREAD

**Issue by dawsonbotsford** [sahat/hackathon-starter#449]
The GitHub API example works in the herokuapp example, but not when I install it locally. The rest of the app appears to be functioning well. My database is up and running and logging the users properly. I began repeated testing by first authenticating with GitHub alone and then attempting to follow the API example link.

At first, I thought the issue was the default API keys, but after swapping those for actual keys for a personal  app registered through GitHub, there was no luck. 

![Imgur](http://i.imgur.com/6kKqQtf.png)

----
[sist](https://github.com/dawsonbotsford/sist) output:

### OS
Darwin  
x64  

### shell  
`uname`: Darwin
`echo $SHELL`: /bin/zsh
`echo $TERM`: xterm-256color
`echo $TERM_PROGRAM`: iTerm.app

### node  
`npm -v`: 3.8.6
`node --version`: v5.11.0

Time created: Tue May 03 2016 03:24:09 GMT-0600 (MDT)

**Comment by jonathanlurie** [comment]
Hi,
yes, I have exactly the same on my local config. Everything is working fine (mongo users, link with other API), but the Github link gives this error 500.

**Comment by dawsonbotsford** [comment]
@jonathanlurie Would you put in [sist](https://github.com/dawsonbotsford/sist) output to your comment for ease of debugging? Glad it's not just me 👍

**Comment by jonathanlurie** [comment]
Sure, here my config:  

### shell  
`uname`: Darwin
`echo $SHELL`: /bin/bash
`echo $TERM`: xterm-256color
`echo $TERM_PROGRAM`: Apple_Terminal

### node  
`npm -v`: 3.7.3
`node --version`: v5.9.0

**Comment by dawsonbotsford** [comment]
Searching into this with no luck. Here's what I've found so far:

On line 169 of [controller/api.js](https://github.com/sahat/hackathon-starter/blob/master/controllers/api.js), this line `var repo = github.getRepo('sahat', 'requirejs-library');` is called. It returns a `github-api` [repository object](http://michael.github.io/github/docs/1.1.0/Repository.html). This object certainly does **not** have a `show` function, as seen in the previous link.

Yet the `repository` object we try to use on line 170 of `api.js` needs to give the jade view access to the repository data like `html_url` and `name` as seen on line 28 of [/views/api/github.jade](https://github.com/sahat/hackathon-starter/blob/master/views/api/github.jade)

Does version 1.0.0 vs 1.1.0 matter for the npm module [github-api](https://github.com/michael/github#readme)? It looks like **no the version does not matter**. I tested this by upgrading from 1.0.0 to 1.1.0 with no changes in this error.

**Comment by dawsonbotsford** [comment]
Fixed, the `show` function is actaully `getDetails`! PR coming in a few minutes 👍

**Comment by jonathanlurie** [comment]
thanks for the fix @dawsonbotsford , I will try that on my side! 👍
