### ISSUE TITLE
Environment variables not loaded

### ISSUE THREAD

**Issue by tobkle** [sahat/hackathon-starter#457]
Had the problem, that after changing .env.example to .env, that the environment variables weren't set any more. According to https://www.npmjs.com/package/dotenv the config function has to initialize. It looks like it is done if you send an initial path in your .env.example, but not, if you remove that line. 

In app.js line 11 is lacking the config() call:
```javascript
var dotenv = require('dotenv');
```
IMHO should be replaced by:
```javascript
var dotenv = require('dotenv').config();
```

Otherwise .env variables aren't loaded.

**Comment by sahat** [comment]
#### Config
Alias: **load**

config will read your .env file, parse the contents, and assign it to process.env. You can additionally, pass options to config.
