### ISSUE TITLE
docker-compose howto

### ISSUE THREAD

**Issue by MikeMichel** [sahat/hackathon-starter#464]
Hi, i just did a docker-compose howto for hackathon-starter https://goo.gl/5Ltyhj . I also found that thread where you rejected a docker.compose.yml file for this repo. While i understand your reasons you might want to consider to add at least a few lines in the readme howto start it with docker-compose as it is the fastet way to start hackathon-starter and get started fast is the main reason of this project, right? 

cheers

**Comment by wilson-shippable** [comment]
Docker has become the standard approach to bringing up servers both locally on various operating systems and in clouds. So it's appropriate that apps have a sample Dockerfile if only to show that the app has been dockerized. I started a tutorial at https://wilsonmar.github.io/docker-setup/  Let me know if that helps, and what updates it should have.

**Comment by wilsonmar** [comment]
Docker has become the standard approach to bringing up servers both locally on various operating systems and in clouds. So it's appropriate that apps have a sample Dockerfile if only to show that the app has been dockerized. I started a tutorial at https://wilsonmar.github.io/docker-setup/ Let me know if that helps, and what updates it should have.

**Comment by DracoBlue** [comment]
:+1:

**Comment by niallobrien** [comment]
If you guys feel that some of this information should be within the documentation, could you please open a PR? Thanks in advance.

**Comment by YasharF** [comment]
The docker-compose.yml that is now in the project is working.  Thank you for the input.
