### ISSUE TITLE
Reset Password failure

### ISSUE THREAD

**Issue by dawsonbotsford** [sahat/hackathon-starter#492]
When using the live version, password recovery is failing for me. I'm in OSX Chrome and visiting `http://hackathonstarter.herokuapp.com/forgot`

I created an account ~1 month ago and tried to perform a password recovery.

![Imgur](http://i.imgur.com/6QftiBo.png)

**Comment by dawsonbotsford** [comment]
Looks like this was intentional with the SendGrid API keys.

**Comment by sahat** [comment]
Yes, sorry I ran out of fake accounts, you will need to supply your own account keys.
