### ISSUE TITLE
Failing es6 reserved words

### ISSUE THREAD

**Issue by dawsonbotsford** [sahat/hackathon-starter#493]
use of reserved words outside of strict mode causes failure of running `npm start` on my system. PR made

[sist](https://github.com/dawsonbotsford/sist) output:

### OS
Darwin  
x64  

### shell  
`uname`: Darwin
`echo $SHELL`: /bin/zsh
`echo $TERM`: xterm-256color
`echo $TERM_PROGRAM`: iTerm.app

### node  
`npm -v`: 3.8.6
`node --version`: v5.11.0

Time created: Mon May 30 2016 20:29:34 GMT-0400 (EDT)

**Comment by sahat** [comment]
I have set the minimum required Node.js version to 6.0. Is there a particular reason why you cannot upgrade to 6.x?

**Comment by dawsonbotsford** [comment]
There's no reason why I cannot upgrade, I choose not to. I run 5.* in my dev to try to target the most users. And literally that's the only thing that needed changed and now you support 5.*!

It may also pass now on 4.*, not sure.

**Comment by dawsonbotsford** [comment]
If you want to keep this repo popular, you need to make it easy for the most users. And from what I can tell using it already, this **one line** of code change now allows it work on 5.*!
