### ISSUE TITLE
Database size - Sessions

### ISSUE THREAD

**Issue by PierreBresson** [sahat/hackathon-starter#497]
Hi there,

On mLab, I can see "sessions" getting bigger and bigger, very quickly. Any possibility to delete it automatically every once in a while so it don't become too big?

![image](https://cloud.githubusercontent.com/assets/8709134/15775560/d0306696-2982-11e6-963d-ce2c20590e59.png)

Regards :)

**Comment by macleodsawyer** [comment]
+1

**Comment by sahat** [comment]
I don't really know to be honest. You should raise this issue with [connect-mongo](https://github.com/kcbanner/connect-mongo).

**Comment by PierreBresson** [comment]
@sahat : thanks to your the guidance, I found a way to fix my problem :

```
app.use(session({
  cookie: { maxAge: 600000 },
  ...
  saveUninitialized: false,
  ...
  store: new MongoStore({
    url: process.env.MONGODB_URI || process.env.MONGOLAB_URI,
    clear_interval: 3600,
   ...
  })
}));
```
