### ISSUE TITLE
Pinterest API example have invalid redirect URL

### ISSUE THREAD

**Issue by deksden** [sahat/hackathon-starter#504]
.env.example, last line:
PINTEREST_REDIRECT_URL=https://localhost:3000/auth/pinterest/callback

should be http instead of https

Not sure if i should make PR for this one-line fix.

**Comment by sahat** [comment]
Thanks, I will fix it right in GitHub since it's such a small issue.

**Comment by sahat** [comment]
Oh wait, I remember now why it needs to be HTTPs. It's an unfortunate requirement by Pinterest API: https://github.com/sahat/hackathon-starter/pull/390

**Comment by deksden** [comment]
@sahat : Hmm. Strange! Redirecting to http did work for me. 

Tested one more time and i m pretty sure: httpS redirect DID NOT work for me on localhost (pretty reasonable) firing error, but changing RedirectURL in .env.example to plain http did work. I m able to place a pin, so API is working.

Ideas:

1) Actually, when registering app you should specify https, but maybe providing redirectURL to API can be http - please test on your side!

2) maybe this point can be added as a note to readme, Pinterest API page or so on?

**Comment by sahat** [comment]
Yeah I can confirm neither approach worked for me.

1) Can't use `http://` on Pinterest
<img width="577" alt="screenshot 2016-06-20 11 24 14" src="https://cloud.githubusercontent.com/assets/544954/16199991/a2109e84-36d9-11e6-9e4b-db880331644e.png">

2) Can't use `http://` in .env:
```js
{"status": "failure", "code": 7, "host": "coreapp-ngapi-prod-0a0181b3", "generated_at": "Mon, 20 Jun 2016 15:23:20 +0000", "message": "You are not permitted to access that resource.", "data": "The provided redirect_uri http://localhost:3000/auth/pinterest/callback does not match any of the registered redirect URIs."}
```

I am going to keep things as is since Pinterest obviously wants everyone to use https.

**Comment by nacimgoura** [comment]
Same problem with pinterest and https.
