### ISSUE TITLE
Using dotenv-safe module instead plain dotenv 

### ISSUE THREAD

**Issue by deksden** [sahat/hackathon-starter#508]
AFAIK, app will not work without some API keys from .env, so its more logical to use dotenv-safe module (we have .examples already!):

https://github.com/rolodato/dotenv-safe

> dotenv-safe: Identical to dotenv, but ensures that all necessary environment variables are defined after reading from .env. These needed variables are read from .env.example, which should be committed along with your project.

**Comment by sahat** [comment]
I gave dotenv-safe a shot, but ran into some issues, which could be by design. Simply swapping dotenv with dotenv-safe didn't work - error is thrown due to missing env vars. Renaming .env.example to .env also fails because it expects .env.example to exist. So if I understand correctly it expects you to have 2 files - `.env` and `.env.example`?

**Comment by deksden** [comment]
Yes. .env.example is a template for .env file, and you can create .env file via duplicating -example and renaming. 

Also dotenv-safe use .env.example as a schema for validating .env file (sure, you can apply some options to tweak validation - see readme). 

Normally you commit only .env.example, and add .env to .gitignore.

**Comment by sahat** [comment]
TBH, I don't really like the idea of having two .env files - one as a template and another as an actual file used for loading keys, neither of which will be used in production. `.env.example` already provides all the keys out of the box.

People usually do not read the README instructions in general, it is another reason why I am hesitant to add an extra step that requires duplicating`.env.example` to `.env`.

If the `.env.example` file was similar to this (https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/sample.env) then yeah that would probably make more sense to use dotenv-safe.

**Comment by deksden** [comment]
Sure) 
You project is ok to disclosure keys, os its "by design". Average project use "closed keys" policy, so - its just one way to handle stuff.
