### ISSUE TITLE
npm install error on secp256k1

### ISSUE THREAD

**Issue by mattbajorek** [sahat/hackathon-starter#518]
I have updated my node and npm versions however when I run npm install, the secp256k1 dependency will not install.

**Comment by sahat** [comment]
@mattbajorek Could you post full error log from the Terminal?

**Comment by mattbajorek** [comment]
[npm-debug.txt](https://github.com/sahat/hackathon-starter/files/355771/npm-debug.txt)

**Comment by sahat** [comment]
Looks like a problem with your environment. No issues here, on Mac or Windows.

**Comment by sahat** [comment]
Travis failing build has been resolved via https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.

You should make sure you have installed the build tools for your OS.
