### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by Octales** [sahat/hackathon-starter#519]
Hi Sahat,

First of all I want to thank you for creating so much beautiful boilerplate's likes Hackathon and Satelizer  from which I got the chance to learn so much great stuff !!! :+1: 

After working on a project using Hackathon-starter/es6, i decided it was time secure and check everything. While doing this I stumbled upon JWT route protection and was wondering if Hackathon is bullet proof with Cookies and it's session Middleware and Headers technique vs sessionless JWT? Should i add nginx for static files while also adding additional production headers like hsts etc in lusca or session cookie httpOnly secure, what do you suggest ? 

On my project i changed everything to work only on SSL but I still don't feel ready to launch until I'm fully confident that nothing can breach my app ! Hope you have the time to give me a short hint about what to expect by using Hackathon-starter for Production.

**Comment by sahat** [comment]
Hi @Octales, I am not a security expert, but with Hackathon Starter out of the box you should be okay. It uses lusca module for XFRAME, XSS and CSRF protection. The last one is relevant to your question about cookies. You may also want to look into `helmet` package that comes with additional security features. For https only cookies that depends on if you have a domain with SSL certificate. If you do, you should also setup auto-redirect domain http to https in the Express middleware or at the Nginx level.

**Comment by Octales** [comment]
Hey @sahat, thank you for clearing those steps out . One other thing I noticed you didn't touch the Json Web Token subject [https://www.npmjs.com/package/jsonwebtoken](JWT) or [https://www.npmjs.com/package/passport-http-jwt-bearer](Passport-JWT-Bearer) are you againts Tokens for user validations and authorization ?

**Comment by sahat** [comment]
@Octales if you are not planning to use single-page app architecture, stick with cookies and sessions. If you are going to use React/Angular then JWT will make more sense to use. Although if you are going to use React with server-side rendering you are going to end up using JWT with cookies instead of localStorage/sessionStorage.
