### ISSUE TITLE
Jade has been renamed to Pug

### ISSUE THREAD

**Issue by shubhamoli** [sahat/hackathon-starter#525]
Since Jade had been renamed to Pug, so the extension of all of the files inside views/ directory needed to be renamed ***.pug**

PR for the same has been submitted #524

**Comment by masonhensley** [comment]
Reference and background info for the uninformed. This was news to me: https://github.com/pugjs/pug

Thanks shubhamoli

**Comment by wilsonmar** [comment]
waiting for pug 2.0 to become final, it's still in beta at the moment.

**Comment by shubhamoli** [comment]
Yeah, ethically we should wait till pug 2.0 becomes final.

**Comment by sahat** [comment]
Resolved in 935f13df7c1b67f9d61ef60abc01330b1cf57756 and explained in https://github.com/sahat/hackathon-starter/pull/524#issuecomment-241288655.
