### ISSUE TITLE
Windows 10 x64 Install Error

### ISSUE THREAD

**Issue by Noppadet** [sahat/hackathon-starter#526]
**Using the Readme steps (git pull, npm install), there are a bunch of warnings like this:** 

E:\Personal\MyProject\node_modules\secp256k1\build\secp256k1.vcxproj]
e:\personal\MyProject\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(599): warning C4244: '=': convers
ion from 'uint64_t' to 'uint32_t', possible loss of data (compiling source file ..\src\secp256k1-src\src\secp256k1.c) [
E:\Personal\MyProject\node_modules\secp256k1\build\secp256k1.vcxproj]
e:\personal\MyProject\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(600): warning C4244: '=': convers
ion from 'uint64_t' to 'uint32_t', possible loss of data (compiling source file ..\src\secp256k1-src\src\secp256k1.c) [
E:\Personal\MyProject\node_modules\secp256k1\build\secp256k1.vcxproj]
e:\personal\MyProject\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(602): warning C4244: '=': convers
ion from 'uint64_t' to 'uint32_t', possible loss of data (compiling source file ..\src\secp256k1-src\src\secp256k1.c) [
E:\Personal\MyProject\node_modules\secp256k1\build\secp256k1.vcxproj]
e:\personal\MyProject\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(603): warning C4244: '=': convers
ion from 'uint64_t' to 'uint32_t', possible loss of data (compiling source file ..\src\secp256k1-src\src\secp256k1.c) [
E:\Personal\MyProject\node_modules\secp256k1\build\secp256k1.vcxproj]

**Then this:**

LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [E:\Personal\MyProject\node_modu
les\secp256k1\build\secp256k1.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Personal\MyProject\node_modules\secp256k1
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.0.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.0.1 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Personal\MyProject\node_modules\secp256k1\npm-debug.log
hackathon-starter@4.0.1 E:\Personal\MyProject
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! secp256k1@3.0.1 install: `npm run rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.0.1 install script 'npm run rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Personal\MyProject\npm-debug.log
npm ERR! code 1

**Log**
[npm-debug.txt](https://github.com/sahat/hackathon-starter/files/367914/npm-debug.txt)

No luck with npm run rebuild or node-gyp rebuild.

**Comment by Noppadet** [comment]
Fix: I created a C:\OpenSSL-Win64\lib file, and extracted libeay32.lib from here in there: http://www.indyproject.org/Sockets/fpc/OpenSSLforWin64.en.aspx

**Comment by Noppadet** [comment]
Final fix: I had to "npm install node-sass" to get the vendor folder in the node-sass node_modules folder for the project.

**Comment by sahat** [comment]
@Noppadet Do you have Visual Studio or Visual C++ Tools installed?

**Comment by sahat** [comment]
Additionally, you can download WinSSL binaries from https://slproweb.com/products/Win32OpenSSL.html but I don't recall any NPM requiring it.

**Comment by Noppadet** [comment]
@sahat I have VS 2015 Pro installed yes. It looks like the problem module is secp256k1 which may be related to sort of Bitcoin api? I haven't had a chance to delve into everything yet.

**Comment by sahat** [comment]
I found this in BitGo's package.json, but it is an optional dependency:

```js
"optionalDependencies": {
    "secp256k1": "3.0.1"
}
```

It is either trying to install an optional dependency or some other package is installing secp256k1.
