### ISSUE TITLE
Security and DDOS Check !

### ISSUE THREAD

**Issue by Octales** [sahat/hackathon-starter#527]
Some modules are outdated including Express 4.14.0 since pls do 

```
npm install nsp
then
nsp check --output summary
```

also `npm ls node-sass` which uses node-sass-middleware has some errors with bindings in Node 6.*

I know some are not worth looking at since the author of the modules needs to update his own module like  `node-sass-middleware` or `jade>transformer>uglify` which has not been updated in 4 months but for `express` or `hawk` etc we got to support latest modules and provide securer and ddosless starterapps. 

I'm inclined to dump the old session, only accept TLS and use https://www.npmjs.com/package/passport-jwt-cookiecombo for the authentication process. I want to be able to further authorize a user interaction after they login and this seems like the best logical approach for me.

I hope you are having a great day Sahat because things are starting to get interesting :D 

Reading a book called [Secure your node js app](https://pragprog.com/book/kdnodesec/secure-your-node-js-web-application) which teaches you different way at looking at server and app security and how to check that everything is running at it's best. Will further test the master repo and hopefully start to commit more the project.

Cheers !

**Comment by sahat** [comment]
Hi @Octales,

For some of these dependencies the best thing to do is to send a pull request and hope the author merges it. Other than that, not much you can do outside of forking it and using your own packages.

I just discovered this [security checklist](https://github.com/FallibleInc/security-guide-for-developers/blob/master/security-checklist.md) which may be worthwhile to read through it.
