### ISSUE TITLE
How about a wiki?

### ISSUE THREAD

**Issue by AdityaAnand1** [sahat/hackathon-starter#529]
The README.md is a little cumbersome.

• Putting the release logs (at the very bottom of the README) in a separate CHANGELOG.md would be more appropriate.
• I think the main README should only contain basic setup instructions (like in most projects), and we could have Wiki pages for things like common errors, obtaining API keys, explaining project structure and all the other sections.

Just a suggestion :)

**Comment by sahat** [comment]
This has been brought up 2 years ago in https://github.com/sahat/hackathon-starter/issues/183. I still feel about it the same way.

I know some people may find this long README format to be cumbersome and annoying to navigate, but for others:

<img width="342" alt="screenshot 2016-07-21 23 54 02" src="https://cloud.githubusercontent.com/assets/544954/17048933/721bfe0c-4f9e-11e6-9593-733a35cc874a.png">

Thanks, I really appreciate the suggestion though.
