### ISSUE TITLE
Auto-fill Contact Form

### ISSUE THREAD

**Issue by wilsonmar** [sahat/hackathon-starter#530]
When a user is signed in via Twitter or whatever, the system has the user's name and email address. So how about automatically populating that information rather than making the user fill out what the system already knows?

![screen shot 2016-07-22 at 2 29 39 am](https://cloud.githubusercontent.com/assets/300046/17051157/5f51370e-4fb4-11e6-8a78-a0d6d4a09621.png)

**Comment by sahat** [comment]
This has been suggested before in this PR https://github.com/sahat/hackathon-starter/pull/372. I am going to leave that functionality for a user if they so desire.
