### ISSUE TITLE
Testimonials and Sites built with the Hackathon Starter

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#532]
- TODO: Add to README.

**Comment by wilsonmar** [comment]
How can users of this be informed of hackathons such as:
http://integratecon.com/hackathon/
associated with API world in the San Jose Convention Center Sep 12-14

**Comment by sahat** [comment]
I think it's the other way around, how can hackathon attendees be informed about Hackathon Starter. 😉 @wilsonmar 

If someone is thinking of attending a hackathon, chances are they would check something like MLH.io or Hacker League for upcoming hackathons in their area.

**Comment by mencargo** [comment]
A tiny suggestion, mark your repo as JavaScript instead of CSS (and megaboilerplate also), for github searches.
