### ISSUE TITLE
Map GIS APIs

### ISSUE THREAD

**Issue by wilsonmar** [sahat/hackathon-starter#535]
Visibly absent from the list of APIs are map APIs from Goggle, Bing, etc.

Or am I missing something?

**Comment by sahat** [comment]
It would be awesome to have Google Maps API example with JS SDK. Unfortunately I am quite busy with other projects at the moment, but pull requests are welcome.

**Comment by wilsonmar** [comment]
are you going to add the Google Map icon in  
http://hackathonstarter-sahat.rhcloud.com/api

**Comment by wilsonmar** [comment]
The one I paid you to show me

**Comment by RobinsonKameron** [comment]
What kind of example would we want?
