### ISSUE TITLE
Page where people can sign up for Slack

### ISSUE THREAD

**Issue by wilsonmar** [sahat/hackathon-starter#536]
Slack doesn’t allow people to sign up directly. Instead, the Slack channel’s admin needs to invite them manually.

Here's a way:
https://blog.stamplay.com/launch-your-community-with-a-fully-automated-slack-signup-page/

**Comment by sahat** [comment]
We use Gitter instead of Slack as the official chat channel. https://gitter.im/sahat/hackathon-starter
