### ISSUE TITLE
secp256k1 dependency

### ISSUE THREAD

**Issue by KrishnaPG** [sahat/hackathon-starter#537]
Any info on which component is using this particular package: `secp256k1`

It is having node-gyp build problems (has [hard coded paths](https://github.com/cryptocoinjs/secp256k1-node/issues/92) inside it), and I am not able to see this package listed in the package.json.

Because of this single package, unable to build this whole library on windows. Any info on how to remove this dependency would be helpful.

**Comment by sahat** [comment]
@KrishnaPG Could you remove bitgo library from package.json and try again?

**Comment by KrishnaPG** [comment]
Yes, thank you. BitGo was using it.

**Comment by sahat** [comment]
There have been a few reports about this issue recently, so I think it's best to remove BitGo until if and when this issue is resolved.
