### ISSUE TITLE
Deprecated sub packages and ReDOS vulnerability

### ISSUE THREAD

**Issue by kaatt** [sahat/hackathon-starter#541]
When I do `npm i`:
```
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
```
Is it safe to ignore the warnings or should I do something?

**Comment by sahat** [comment]
Yes you can safely ignore them. Other than the first jade warning, there is not much I can do about sub-dependencies of Hackathon Stater's dependencies.

**Comment by kaatt** [comment]
Can you remove/replace the packages that need those insecure sub-dependencies?

Maybe we can create issues for those packages.

**Comment by sahat** [comment]
I cannot remove these packages, even if I track them down somehow, I still need them for this project to function correctly. 

Really, there is no need to worry, it's just a warning. When and if things break, those packages will be updated.
