### ISSUE TITLE
SyntaxError connecting to mongodb with nodemon

### ISSUE THREAD

**Issue by Dejital** [sahat/hackathon-starter#544]
The app will not run out of the box, as I receive the following error. 

    > nodemon app.js 
    [nodemon] 1.9.2
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    [nodemon] starting `node app.js`
    /Users/Serge/Dropbox/Developer/hackathon-starter/app.js:49
    mongoose.connection.on('error', () => {
                                     ^
    SyntaxError: Unexpected token )
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3
    [nodemon] app crashed - waiting for file changes before starting...

Note that Mongodb is running locally with `mongod`. I am using OS X 10.11.5 El Capitan.

**Comment by khanghoang** [comment]
@Dejital can you paste here you node version? it required Node.js 6.0+ to run.

**Comment by Dejital** [comment]
@khanghoang 

    > node -v
    v0.12.2

**Comment by KevinBusse** [comment]
You could still use the `es5` branch then...

**Comment by Dejital** [comment]
Thank you, this should satisfy my question. Thank you @khanghoang and @KevinBusse .
