### ISSUE TITLE
NSP (Node Security Project) issues - 7/28/2016

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#546]
NSP is identifying 9 vulnerabilities in the dependencies.  This Issue is to track and resolve them:

(+) 9 vulnerabilities found

1. Regular Expression Denial of Service
Package:uglify-js
Installed: 2.2.5
Vulnerable: <2.6.0
Patched: >=2.6.0
Path: hackathon-starter@4.0.1 > jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5
More Info: https://nodesecurity.io/advisories/48

2. Incorrect Handling of Non-Boolean Comparisons During.
Package:uglify-js
Installed: 2.2.5
Vulnerable: <= 2.4.23
Patched: >= 2.4.24
Path: hackathon-starter@4.0.1 > jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5
More Info: https://nodesecurity.io/advisories/39

3. Denial-of-Service Extended Event Loop Blocking
Package:qs
Installed: 0.6.6
Vulnerable: <1.0.0
Patched: >= 1.x
Path: hackathon-starter@4.0.1 > node-linkedin@0.5.3 > request@2.31.0 > qs@0.6.6
More Info: https://nodesecurity.io/advisories/28

4. Denial-of-Service Memory Exhaustion
Package:qs
Installed: 0.6.6
Vulnerable: <1.0.0
Patched: >= 1.x
Path: hackathon-starter@4.0.1 > node-linkedin@0.5.3 > request@2.31.0 > qs@0.6.6
More Info: https://nodesecurity.io/advisories/29

5. Regular Expression Denial of Service
Package:hawk
Installed: 1.0.0
Vulnerable: < 3.1.3  || >= 4.0.0 <4.1.1
Patched: >=3.1.3 < 4.0.0 || >=4.1.1
Path: hackathon-starter@4.0.1 > node-linkedin@0.5.3 > request@2.31.0 > hawk@1.0.0
More Info: https://nodesecurity.io/advisories/77

6. ReDoS via long string of semicolons
Package:tough-cookie
Installed: 0.9.15
Vulnerable: >=0.9.7 <=2.2.2
Patched: >=2.3.0
Path: hackathon-starter@4.0.1 > node-linkedin@0.5.3 > request@2.31.0 > tough-cookie@0.9.15
More Info: https://nodesecurity.io/advisories/130

7. Regular Expression Denial of Service
Package:hawk
Installed: 2.3.1
Vulnerable: < 3.1.3  || >= 4.0.0 <4.1.1
Patched: >=3.1.3 < 4.0.0 || >=4.1.1
Path: hackathon-starter@4.0.1 > twilio@3.3.0-edge > request@2.55.0 > hawk@2.3.1
More Info: https://nodesecurity.io/advisories/77

8. Regular Expression Denial of Service
Package:hawk
Installed: 2.3.1
Vulnerable: < 3.1.3  || >= 4.0.0 <4.1.1
Patched: >=3.1.3 < 4.0.0 || >=4.1.1
Path: hackathon-starter@4.0.1 > twit@2.2.4 > request@2.58.0 > hawk@2.3.1
More Info: https://nodesecurity.io/advisories/77

9. Regular Expression Denial of Service
Package:hawk
Installed: 1.1.1
Vulnerable: < 3.1.3  || >= 4.0.0 <4.1.1
Patched: >=3.1.3 < 4.0.0 || >=4.1.1
Path: hackathon-starter@4.0.1 > yui@3.18.1 > request@2.40.0 > hawk@1.1.1
More Info: https://nodesecurity.io/advisories/77

**Comment by YasharF** [comment]
1, 2:  It looks like the dependency needs to change from Jade to Pug.  If I understood it correctly, Jade got renamed to Pug and the dependencies for the old project are no longer being tracked ( https://david-dm.org/jadejs/jade ).  I don't see a direct dependency from Pug to transformers.  So, 1 and 2 are probably going to be resolved with moving to Pug.

3,4,5,6: Created Issue with dependency : https://github.com/ArkeologeN/node-linkedin/issues/67
7: Existing issue with twilio-node:  https://github.com/twilio/twilio-node/issues/170
8: Created Issue with dependency:  https://github.com/ttezel/twit/issues/288
9: Needs to be removed - It is a deprecated project and no longer maintained or patched: https://yahooeng.tumblr.com/post/96098168666/important-announcement-regarding-yui

**Comment by YasharF** [comment]
Can someone else work on  Jade -> Pug and YUI removal ?

I can drive getting the other issues resolved.

**Comment by sahat** [comment]
@YasharF I will switch over Jade  to Pug and remove YUI.

**Comment by YasharF** [comment]
Fix for 3,4,5,6 is merged in the github repo for node-linkedin : https://github.com/ArkeologeN/node-linkedin/commit/cef763ebb8ffc54f750ff57e8be5bf210c45792d

**Comment by sahat** [comment]
Thanks @YasharF!

**Comment by YasharF** [comment]
7 is almost fixed.  twilio-node-3.3.1-edge has the fix, but it looks like because of -edge npm isn't picking up the update in hackathon-starter.  I will submit a PR to update package.json.

**Comment by YasharF** [comment]
For 8, I also emailed tolgatezel11@gmail to see if he can accept the PR for his package.
After that is resolved, we are going to be only left with the Jade related issues (1 and 2).

**Comment by sahat** [comment]
@YasharF 1,2 should be resolved now in 4.2.0. You may close this issue.

**Comment by YasharF** [comment]
8 just got fixed up as well.  So all dependencies are cleared at this point.  

Existing users need to run "npm update" in their hackathon-starter package to pick up the patched version of twit dependency.
https://github.com/ttezel/twit/commit/fa4d346fd564220e5dc41e8866fad3abb74b6479

We can probably bump the twit version in hackathon-starter's package.json for a more clear line in the sand.  Let me know if you would like me to submit a PR for it.
