### ISSUE TITLE
Mongoose unit test enhancements

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#549]
- http://codeutopia.net/blog/2016/06/10/mongoose-models-and-unit-tests-the-definitive-guide
- https://semaphoreci.com/community/tutorials/a-tdd-approach-to-building-a-todo-api-using-node-js-and-mongodb

**Comment by andela-rekemezie** [comment]
@sahat Are there specific enhancement you foresee for the models? I'd like to step in

**Comment by sahat** [comment]
@andela-rekemezie The current tests implementation relies on having an active database connection. Just like you would do mock HTTP requests, the same should be done with database requests using sinon or such. I added those two resources above as they seemed like a step in the right direction glancing it over.

**Comment by niallobrien** [comment]
@andela-rekemezie Are you going to tackle this one? Shall we get a PR going? Thanks.

**Comment by andela-rekemezie** [comment]
@niallobrien PR in there already.
