### ISSUE TITLE
Add Charts Examples

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#551]
Candidates:
- [MetricsGraphics.js](http://metricsgraphicsjs.org/examples.htm)
- D3.js
- Mini Sparkline Charts
- Highcharts
- Chart.js

**Comment by fjcero** [comment]
For MVPs highcharts works really well, it have integration with all the major libraries and frameworks. For more specific charts, I will recommend D3, and also NVD3 as a wrapper works well (http://nvd3.org/).

**Comment by aedorado** [comment]
I have a beginner's experience in d3js. I'd like to make useful contributions to your  boilerplate. Can you please describe how to go about it in more detail.

**Comment by niallobrien** [comment]
@sahat What kind of chart examples would you like to see exactly?

**Comment by sahat** [comment]
@aedorado @niallobrien I don't have any particular ideas with this addition... something that would be useful in a hackathon environment? Visualizing some kind of API data? Line charts, bar charts, pie charts are all pretty nice to have.

No need to write a fully fledged API visualization example, even a "hello world" example with fake data will be sufficient. I just want to have some kind of easy-to-use charting library in this boilerplate if someone does need to use it.

We can pick one library and mention others on the example page. As for which charting library, I have no idea. I do know that D3.js is powerful, but very low-level. In the past I have used c3.js - a charting library built on d3.js. 

If someone could do a research and pick the simplest one, I would really appreciate that.

**Comment by niallobrien** [comment]
Hi @sahat - http://www.chartjs.org/ looks like a fantastic solution, Jeffrey Way covered [using ChartJS](https://laracasts.com/series/charting-and-you) in conjunction with Vue.js on Laracasts too, so it might give users a good starting point, especially if linked within the extensive Readme etc.

**Comment by girishpatil** [comment]
I would go with @niallobrien chartjs is the easiest among these perfect for a hackathon

**Comment by GabrielAmazonas** [comment]
Hey guys, it's kind of a old issue, but may I address this one?
Thanks in advance.

**Comment by YasharF** [comment]
@GabrielAmazonas PRs are still welcome :)

**Comment by YasharF** [comment]
Looking at the open source licenses, I would rather use an MIT license (ChartJS) over GPL3 (D3JS).

**Comment by YasharF** [comment]
A good beginners tutorial for D3.js:  https://scrimba.com/g/gd3js

**Comment by YasharF** [comment]
https://github.com/sahat/hackathon-starter/pull/942
