### ISSUE TITLE
CSRF mismatch React/Redux fetch

### ISSUE THREAD

**Issue by mmdonaldson** [sahat/hackathon-starter#552]
Working with Redux/React and I can't seem to get the csrf token to match.
For some reason the csrf token. Do I need to add the token to my body data as well as the header?

    fetch("/post", {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-CSRF-Token': document.getElementsByName('csrf-token')[0].getAttribute('content')
      },
      body: data
    })

**Comment by sahat** [comment]
@mmdonaldson Can you check if you are receiving X-CSRF-Token header on your server? The way you are reading CSRF token is correct, but I suspect this custom header you are using is not being sent.

**Comment by mmdonaldson** [comment]
@sahat The CSRF token in the header is two tokens behind the server. It updates on the server after the GET calls from the css etc. Very confusing as if I use a normal form it doesn't have this problem

**Comment by sahat** [comment]
@mmdonaldson Were you able to resolve it? I haven't used Hackathon Starter with React/Redux so can't comment on it.

**Comment by mmdonaldson** [comment]
@sahat nope ended up building a custom solution instead of using hackathon starter.

**Comment by sahat** [comment]
Alright, I will close this issue then.

**Comment by rbonomo** [comment]
I added the csrf token to the body of the post request and it worked fine. This issue is not really related to react/redux anyways.
