### ISSUE TITLE
Cloudinary API integration

### ISSUE THREAD

**Issue by HintikkaKimmo** [sahat/hackathon-starter#553]
I have used Cloudinary http://cloudinary.com/ image upload, Image enhancement, filters(like Instagram), storage, fast Akamai CDN, face recognition and image tagging API for a few projects and I have nothing but good to say about them. 

Is someone building in or would project accept Cloudinary pull request?

NodeJS integration documenation link below >

http://cloudinary.com/documentation/node_integration

**Comment by mmdonaldson** [comment]
@HintikkaKimmo I'm looking to use something like this, would definitely +1 you integrating

**Comment by hotwilson** [comment]
Just know that Cloudinary is a paid subscription beyond a 2GB limit
http://cloudinary.com/pricing

**Comment by wilsonmar** [comment]
Just know that Cloudinary is a paid subscription beyond a 2GB limit
http://cloudinary.com/pricing

**Comment by sahat** [comment]
If you can build a self-contained API example on a single page, similar to other included APIs, that works out of the box, I would love to merge that PR.

**Comment by sahat** [comment]
Hi @HintikkaKimmo @mmdonaldson, what's the status on this integration? I have no experience with Cloudinary API, but I would be willing to merge a PR. If you are busy at the moment, that is understandable. I am going to close this issue in the meantime, so it doesn't create noise with other reported bugs and issues.

**Comment by mmdonaldson** [comment]
Hey @sahat, could potentially look at this down the track but no time at the moment. Cheers
