### ISSUE TITLE
Configuring Email Settings

### ISSUE THREAD

**Issue by artforlife** [sahat/hackathon-starter#555]
Where does one do that? That is, out of the box, the app does not send any welcome emails to the user nor does it send emails using Forgot Password feature.

Lastly, is there a way to configure it with AWS's SES functionality?

**Comment by mmdonaldson** [comment]
@artforlife I've set up nodemailer using Mailgun. Very straightforward. There's compatibility for SES too.

If there's support for this, happy to create a PR

**Comment by artforlife** [comment]
I think this is a decent idea, if you can make a general and generic implementation. At the very least, it can probably be added into some config file where the admin can just specify email or AWS credentials.

**Comment by sahat** [comment]
@artforlife For sending welcome emails, you would have to that yourself in the signup controller. See contact controller for reference on how to do that using nodemailer.

Out of the box, it does send emails on Forgot Password request, however, included credentials have been suspended by both SendGrid and MailGun.

I think I have switched these API keys 3 or 4 times already, and they just end up getting blacklisted (and for a good reason!). 

For AWS SES, you can use this module https://github.com/andris9/nodemailer-ses-transport by replacing code below with the one provided in that README:

```js
const transporter = nodemailer.createTransport({
  service: 'SendGrid',
  auth: {
    user: process.env.SENDGRID_USER,
    pass: process.env.SENDGRID_PASSWORD
  }
});
```

**Comment by slidenerd** [comment]
Bonus Put this file called mail.js which uses Amazon SES to do emails and call it from wherever you want to send an email
```

"use strict";

const
    nodemailer = require('nodemailer'),
    aws = require('aws-sdk'),
    debug = require('debug')('whateverman:mail')


// configure AWS SDK
const credentials = new aws.Credentials();
credentials.accessKeyId = process.env.AWS_ACCESS_KEY_ID;
credentials.secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
credentials.region = process.env.AWS_REGION;

// create Nodemailer SES transporter
const transporter = nodemailer.createTransport({
    SES: new aws.SES({
        apiVersion: '2010-12-01'
    })
});

module.exports = (from, to, subject, text) => {
    return new Promise((resolve, reject) => {
        // send some mail
        transporter.sendMail({
            from,
            to,
            subject,
            text
        }, (error, info) => {
            if (error) {
                debug.enabled && debug("mail(): sendEmail: from %s to %s subject %s text %s error %O", from, to, subject, JSON.stringify(text), error);
                reject(error);
                return;
            }
            debug.enabled && debug("mail(): sendEmail: from %s to %s subject %s text %s success %s", from, to, subject, JSON.stringify(text), JSON.stringify(info));
            resolve(info);
        });
    })

};



```

**Comment by YasharF** [comment]
For Amazon SES, you can also use its SMTP interface without adding the additional aws-sdk dependency: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-an-email-using-smtp.html
