### ISSUE TITLE
Tag releases as Github releases

### ISSUE THREAD

**Issue by tobiasge** [sahat/hackathon-starter#558]
Hello,

I think it would be nice if you could tag your releases in git and mark them als releases on Github. That way it would be easier to find a specific release.

Kind regards
Tobias

**Comment by sahat** [comment]
Sure, I can start tagging new releases moving forward. What's your particular use-case if you don't mind me asking? @tobiasge

**Comment by tobiasge** [comment]
I wanted to start an app from the latest release. So I had to look through the commit history to find the corresponding commit.
If they are tagged it's easier to find them.

Thanks.
