### ISSUE TITLE
Should we have a /status page?

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#559]
### https://github.com/RafalWilinski/express-status-monitor
A Realtime Self-Hosted Monitor for Express Apps.

It's a plug-and-play solution using one-line of code.

![687474703a2f2f692e696d6775722e636f6d2f4148697a4557712e676966](https://cloud.githubusercontent.com/assets/544954/17830478/8d31c3d0-6681-11e6-9666-1421f2af1f99.gif)

**Comment by wilsonmar** [comment]
Very cool not just for show, but for debugging.
