### ISSUE TITLE
Pug template issue on master branch

### ISSUE THREAD

**Issue by tomkaos** [sahat/hackathon-starter#561]
Hi,

I experienced the following issue: many of expressions in pug templates are not exchanged with their values. for example in the navbar (rendered source html): 
<a class="dropdown-toggle" href="#" data-toggle="dropdown"><img src="#{user.profile.picture}">Tamas Konya&nbsp;<i class="caret"></i></a>

Do you have any solution for this?

Thx,
Tamas

**Comment by sahat** [comment]
@tomkaos What did you end up doing? This seems like a jade 11.0 > pug 2.0-beta5 breaking change.

**Comment by sahat** [comment]
Ah, I see, they have switched to ES6 template strings: https://github.com/pugjs/pug/issues/2305

> We removed support for interpolation in attributes since it was unnecessarily complex in implementation and tended to delay users learning that they can just use any JavaScript value in place of attributes
