### ISSUE TITLE
displaying facebook avatar in navbar

### ISSUE THREAD

**Issue by josebrwn** [sahat/hackathon-starter#563]
Thanks for the fantastic framework; it has helped us so much. It is a great timesaver, and I am learning so much.

When I run the application at 127.0.0.1:3000, the user's avatar doesn't appear next to the name, after logging in through Facebook.

However, the record in the mongodb looks fine, at first: there is a username, image, and so on.  The record looks like this:

```
{
        "_id" : ObjectId("57bc9f71cf9c78642abfe952"),
        "updatedAt" : ISODate("2016-08-23T19:09:37.817Z"),
        "createdAt" : ISODate("2016-08-23T19:09:37.817Z"),
        "facebook" : "10155111808542786",
        "email" : "josebrwn@yahoo.com",
        "profile" : {
                "picture" : "https://graph.facebook.com/10155111808542786/picture?type=large",
                "website" : "",
                "location" : "",
                "name" : "Joseph Brown"
        },
        "tokens" : [
                {
                        "accessToken" : "xxx",
                        "kind" : "facebook"
                }
        ],
        "__v" : 0
}
```

Here I noticed the profile - picture url, it's not the same as on the application's site, where it looks like this:

https://scontent.xx.fbcdn.net/v/t1.0-1/p200x200/13669671_10155029735732786_5967413750339219441_n.jpg?oh=f4b707baf8355df83c10bcabe1e71893&oe=5844AADE

So I'm wondering, did the application read the Facebook JSON incorrectly?

Ps. On the profile page, none of these fields populates, initially. If you click into the email field, the name field will populate, as will the location. The (gr)avatar never does on either site..

Any help greatly appreciated, and again, thank you very much.
Regards.

Pps. by "application's site" I meant the demo at http://hackathonstarter-sahat.rhcloud.com/

**Comment by sahat** [comment]
The JSON is correct, it's an issue with Pug.js 2.0 not supporting Jade's string expression. This doesn't work:

```jade
img(src='#{user.gravatar(60)}')
```

But this works:
```jade
img(src=user.gravatar(60))
```

**Comment by sahat** [comment]
Found the issue.

They have switched to ES6 template strings: [Breaking Changes](https://github.com/pugjs/pug/issues/2305)

> We removed support for interpolation in attributes since it was unnecessarily complex in implementation and tended to delay users learning that they can just use any JavaScript value in place of attributes
