### ISSUE TITLE
Misc Console.log statements in userSchema

### ISSUE THREAD

**Issue by HellerCommaA** [sahat/hackathon-starter#564]
83a4241d models/User.js (Sahat Yalkabov 2016-09-06 23:32:08 -0700 57) userSchema.methods.gravatar = function (size = 200) {

83a4241d models/User.js (Sahat Yalkabov 2016-09-06 23:32:08 -0700 58)   console.log('size', size);

is the git blame @sahat line 58, ./models/User.js

**Comment by sahat** [comment]
Thanks. I've removed it.
