### ISSUE TITLE
REST Version

### ISSUE THREAD

**Issue by asifsaho** [sahat/hackathon-starter#581]
Hi,

I'm seeking for this kind of boilerplate with REST API ready. Is there any?

Thank you

**Comment by sahat** [comment]
Not that I know of. The closest thing is a project generated by http://megaboilerplate.com/ when you choose **React** or **Angular** framework.

**Comment by niallobrien** [comment]
@asifsaho To be honest, most of this boilerplate wouldn't really apply in such a scenario. You'd be just as productive building from scratch and just incrementally adding what you need to build your REST API. Personally, I highly recommend [FeathersJS](http://feathersjs.com/) for building a backend API; REST or Websockets - having an easy to use realtime backend for your SPA is quite awesome. :)

**Comment by sahat** [comment]
Closing as non-issue.
