### ISSUE TITLE
Move routes

### ISSUE THREAD

**Issue by niallobrien** [sahat/hackathon-starter#584]
I know you like having everything in the one place @sahat but would you be opposed to a PR to move just the routes into their own file? It would really make it easier when rapidly developing. For example, CMD+P in Sublime, start typing 'routes', enter - bam - your routes are right there. Happy to implement.

**Comment by niallobrien** [comment]
Please see https://github.com/niallobrien/hackathon-starter/commit/d955e4326e2c4b80b0ea810a68c4ff5eda7e99ac for proposed changes, thanks.

**Comment by macleodsawyer** [comment]
+1 for this, it just makes it easier - even for beginners.

**Comment by niallobrien** [comment]
I've submitted a PR for this.
