### ISSUE TITLE
Move assets

### ISSUE THREAD

**Issue by niallobrien** [sahat/hackathon-starter#585]
Hi, proposing that we move all assets out of the `public`directory and instead place them somewhere sensible such as `assets`. I'd happy to take up this PR.

**Comment by sahat** [comment]
Hi @niallobrien, what is the advantage of that? Not strongly opposed, but wanted to hear your thoughts on why you would want to move it assets?

It would make sense if there was a build system in place to have all your source files outside the public folder. The only "source files" I would consider there are Sass stylesheets that are compiled into `main.css`. But `main.js` on the other hand is used directly as-is without any processing, so don't see much point in moving it outside into `assets` folder.

**Comment by niallobrien** [comment]
@sahat Agreed with regards to the JS without a build system in place. The main reason for moving the styles is simply not to expose your source styles and only expose a minified css file.

**Comment by niallobrien** [comment]
@sahat Also, I could happily open a PR to add a build process if you were open to it? I know this takes away from the simplicity of what's in place at the minute, but it would better align the project with how things are currently done within the JS ecosystem. Also, I've no personal preference, I'm happy to contribute a Webpack or Gulp asset pipeline. Thanks in advance.

**Comment by niallobrien** [comment]
@YasharF I'm going to close this with the intention of writing some documentation so that people can add an asset pipeline themselves if they want to. We've seen some other instances of people wanting to do different things, so perhaps putting all of this into a wiki wouldn't be so bad. Eg. Adding socket.io, changing templating language, adding internationalisation support etc. What do you think?

**Comment by YasharF** [comment]
Sounds good.
