### ISSUE TITLE
Exception thrown on first build

### ISSUE THREAD

**Issue by blakeprobinson** [sahat/hackathon-starter#597]
When running the project for the first time, I encountered the error below.  Since I will not be using gravatars I simply commented out the function, but I thought I would let you know.

![screen shot 2016-10-13 at 7 30 44 am](https://cloud.githubusercontent.com/assets/10137025/19347506/1d0e7aa6-9117-11e6-8897-24a143cf2f59.png)

**Comment by ivancho98** [comment]
Same problem here.

**Comment by ashokkumar24** [comment]
Just remove size=200 in User.js. It works for me. I don't know  why they are kept there. Need to analyse. :)

**Comment by andersrydman** [comment]
Just ran in to the same issue.

**Comment by ivancho98** [comment]
I solved it. You are probably not using the right node version. After switching node v5 to node v6 it works.

**Comment by blakeprobinson** [comment]
@ivancho98, that was it.
