### ISSUE TITLE
Steam OAuth

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#600]
I am getting failed logins with Steam, and I suspect there is a potential bug in the passportjs config https://github.com/sahat/hackathon-starter/blob/master/config/passport.js#L457 :
It looks like that localhost is hardcoded as the returnURL for Steam OpenIDStrategy is set to localhost.  I think the mismatch between this and the domain for the API key are part of the problem, and the requests not coming from the localhost (aka when deployed to Heroku, etc) is probably the other part of the problem.

If my suspicion is correct, then probably  the two lines in passportjs config need to be modified so they are using some environment variable config that is the deployment domain/steam app registration domain, instead of the hardcoded `localhost:3000`

**Comment by niallobrien** [comment]
@YasharF Is there any chance you could open a PR with a failing test-case and if possible, a fix? Thanks in advance.

**Comment by YasharF** [comment]
It might be a little while before I could get to this.  I like to see it fixed, but probably won't be able to do so right away.

**Comment by YasharF** [comment]
Fix in PR https://github.com/sahat/hackathon-starter/pull/797

**Comment by YasharF** [comment]
Fixed with the release of v4.4.0
