### ISSUE TITLE
howto es6 modules

### ISSUE THREAD

**Issue by hanskoff** [sahat/hackathon-starter#606]
Hi, I'm happy hackathon-starter user. I run a project basing on this setup.
I have a question how can I use this modules you are writing about in the cheat sheet? https://github.com/sahat/hackathon-starter#modules I mean on backend side node doesn't support it and on the frontend there is no gulp/webpack with babel so... please tell me how? :) cheers

**Comment by sahat** [comment]
Hi @hanskoff, that cheatsheet was copy & paste from https://github.com/sahat/megaboilerplate/ which contains everything you mentioned. 

At the moment, even the latest Node.js 7 does not support `import/export` ES6 modules. I could remove that section, but it doesn't really hurt to have it in the README in case someone decides to add React or Angular on top of Hackathon Starter.

**Comment by hanskoff** [comment]
cool, thx for quick reply ;) make sense
