### ISSUE TITLE
Unexpected token error on startup

### ISSUE THREAD

**Issue by teogenesmoura** [sahat/hackathon-starter#607]
In a fresh install (right after cloned && npm install), an error is thrown:
```
hackathon-starter/models/User.js:57
userSchema.methods.gravatar = function (size = 200) {
                                             ^

SyntaxError: Unexpected token =
```
I've fixed it by leaving only function(size){...} and inside the function declaring size = 200. Not sure if its a proper solution though.

**Comment by sahat** [comment]
There are 3 duplicate issues. You are using Node.js 5 or lower. Node.js 6 and later has proper ES6 support.

**Comment by sahat** [comment]
I am going to add this code back for a few months until everyone is migrated to the new Node.js 6.9.1 LTS, especially if it's the only failing point of the app.

```js
if (!size) {
    size = 200;
}
```
