### ISSUE TITLE
Add moment-equivalent date formatting to JS Date Cheatsheet in README

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#608]
Instead of just:

``` js
Math.floor(Date.now() / 1000);
```

Show both variations using vanilla JS and moment:

``` js
// Moment
moment().unix()

// JavaScript
Math.floor(Date.now() / 1000);
```

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/6995d0a10cb94fcde88c41f8ce4d9815a00a5cb6
