### ISSUE TITLE
Ask for login appropriate to the API selected

### ISSUE THREAD

**Issue by hotwilson** [sahat/hackathon-starter#610]
Running locally, after I log in (via Facebook),
on the /api page, I click "Twillio".
I fillout the number and a message "Hello".
Click Send. I get:

Connect
500 Authenticate

The log reports:
GET /api/twilio 200 189.969 ms - -
Authenticate
POST /api/twilio 500 364.286 ms - -

**Comment by matheuschimelli** [comment]
@hotwilson Do you have updated the env config variables for twilio?

**Comment by YasharF** [comment]
I suspect the problem was resolved in the particular case since the requester hasn't got back here in a while.  Closing the issue.
