### ISSUE TITLE
Express status monitor interferes with socket.io

### ISSUE THREAD

**Issue by nordfjord** [sahat/hackathon-starter#614]
The Readme contains information on how to use socket.io with the project.

However one of the dependencies of the project is express-status-monitor which itself uses socket.io .

This leads to the unfortunate situation that any socket.io code written by a developer will not execute.

**Comment by sascha1337** [comment]
had this today, please update readme / access to the socket instance?

**Comment by niallobrien** [comment]
I tried adding socket.io and I get handshake errors, does that happen for you too?

**Comment by RafalWilinski** [comment]
I've investigated this issue and here's what I came with:
```
const socketIoPort = 3001;
const app = express();
const io = require('socket.io')(socketIoPort);

app.set('port', process.env.PORT || 3000);
app.use(expressStatusMonitor({ websocket: io, port: socketIoPort }));
```

You have to create `socket.io` instance using port parameter, not `HttpServer`. Also, you cannot use the same port because of `EADDRINUSE`.

Hope that helps.

**Comment by niallobrien** [comment]
Thanks, I got this working in my fork a good while back thanks to the comments here. Closing this issue.
