### ISSUE TITLE
graph api V2.1 is no longer available after october 30th, 2016

### ISSUE THREAD

**Issue by BabbagesCabbages** [sahat/hackathon-starter#615]
![screen shot 2016-11-01 at 5 14 53 pm](https://cloud.githubusercontent.com/assets/5490129/19912321/d8bc7c64-a056-11e6-96c9-eebc74ce7b18.png)
just updating this as an issue. I'll look into a fix this weekend if its not solved already. ref: https://developers.facebook.com/docs/apps/changelog

**Comment by sahat** [comment]
Hey @BabbagesCabbages, for any potential breaking changes the issue should be opened with the respective libraries which in this case is passport-facebook that handles Facebook authentication and fbgraph that handles Facebook API.
