### ISSUE TITLE
Hackathon starter using Python

### ISSUE THREAD

**Issue by slidenerd** [sahat/hackathon-starter#620]
What an awesome project you guys have!!! I have been using it for a while and this suddenly popped up in my mind. What if someone wants to use Python instead of JavaScript for all backend stuff. Do you guys have a Python version of hackathon starter that uses Django or Flask? Any ideas on building one? If no, any projects that you guys are aware of

**Comment by YasharF** [comment]
Have you looked at https://github.com/DrkSephy/django-hackathon-starter
