### ISSUE TITLE
Socket.io issue

### ISSUE THREAD

**Issue by niallobrien** [sahat/hackathon-starter#621]
Hi all, I've added Socket.io support as instructed by the Readme, however, I receive the following error when running locally:
`WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=3&transport=websocket&sid=RudqlRVo0UEUk_PxAAAB' failed: Connection closed before receiving a handshake response`

The socket.io client-side JS is available for me at `http://localhost:3000/socket.io/socket.io.js`.

Anyone else have this issue?

Thanks in advance.

**Comment by hakatashi** [comment]
I've also had the exactly same issue. From my investigation the express-status-monitor is conflicting about WebSocket listening. I simply removed the line `app.use(expressStatusMonitor());` from app.js and it worked. (Of course the status monitor went not to work.)

Hope this help. 😃

**Comment by niallobrien** [comment]
Hi @hakatashi - thank you for your comment, that does indeed resolve the issue, however as you mentioned, Status Monitor will then stop working. I see that their Readme mentions this, but doesn't seem to provide a solid example, so I've opened an issue over there: https://github.com/RafalWilinski/express-status-monitor/issues/64

**Comment by kuriakinzeng** [comment]
This works fine for me:
```
const server = require('http').Server(app);
const io = require('socket.io')(server);
...
app.use(expressStatusMonitor({ websocket: io, port: app.get('port') })); 
```

**Comment by niallobrien** [comment]
Working example can be found at https://github.com/niallobrien/hackathon-starter-plus/blob/replace-asset-pipeline-with-laravel-mix/app.js

**Comment by cschar** [comment]
Hi @niallobrien , I had the same issue and followed this post
https://stackoverflow.com/questions/41381444/websocket-connection-failed-error-during-websocket-handshake-unexpected-respon

my main.js looks like this now and it works locally:

```
$(document).ready(function() {
 var socket = io.connect(window.location.href, {transports: ['websocket']})
 
 socket.on('greet', function (data) {
    console.log(data);
    socket.emit('respond', { message: 'Hello to you too, Mr.Server!' });
  });

});
```
