### ISSUE TITLE
Pug/Jade  variable in attribute no longer supported

### ISSUE THREAD

**Issue by leesander1** [sahat/hackathon-starter#622]
I ran into this when trying to get the linkedin view to display img correctly.
You can read more about it [here](https://pugjs.org/language/attributes.html).
To fix this issue
`          img.thumbnail(src='#{profile.pictureUrl}')`
can be replaced with
`          img.thumbnail(src='' + profile.pictureUrl)`
I think this occurs in several of the views other than the linkedin pug.

**Comment by YasharF** [comment]
@leesander1 , do you think if you can submit a pull request for this?  I did a quick check and these are the places that I found what you mentioned:

https://github.com/sahat/hackathon-starter/blob/b96713c62bd825015ad826d36e7d5c4804621d7b/views/api/foursquare.pug#L37

https://github.com/sahat/hackathon-starter/blob/b96713c62bd825015ad826d36e7d5c4804621d7b/views/api/github.pug#L28

https://github.com/sahat/hackathon-starter/blob/b96713c62bd825015ad826d36e7d5c4804621d7b/views/api/instagram.pug#L33  five other lines

https://github.com/sahat/hackathon-starter/blob/b96713c62bd825015ad826d36e7d5c4804621d7b/views/api/lastfm.pug and four other lines

https://github.com/sahat/hackathon-starter/blob/b96713c62bd825015ad826d36e7d5c4804621d7b/views/api/linkedin.pug#L26

https://github.com/sahat/hackathon-starter/blob/b96713c62bd825015ad826d36e7d5c4804621d7b/views/api/steam.pug#L22

https://github.com/sahat/hackathon-starter/blob/b96713c62bd825015ad826d36e7d5c4804621d7b/views/api/tumblr.pug#L26

https://github.com/sahat/hackathon-starter/blob/b96713c62bd825015ad826d36e7d5c4804621d7b/views/api/twitter.pug#L48

**Comment by leesander1** [comment]
@YasharF yes I will submit a pull request with the fixes when I have some time tomorrow

**Comment by YasharF** [comment]
The related PR has been merged; closing this issue.
