### ISSUE TITLE
401 Error: Read-only application cannot POST.

### ISSUE THREAD

**Issue by reachdevelopers** [sahat/hackathon-starter#623]
When I try to post a new tweet this error occurs. 401 Error: Read-only application cannot POST.
Log in using the twitter api.
<img width="945" alt="screen shot 2016-11-18 at 7 27 01 pm" src="https://cloud.githubusercontent.com/assets/8906338/20452695/0abb1d08-adc5-11e6-8425-93c318b8d697.png">
<img width="1018" alt="screen shot 2016-11-18 at 7 27 09 pm" src="https://cloud.githubusercontent.com/assets/8906338/20452696/0abd2f8a-adc5-11e6-9784-641a7a468e3c.png">

**Comment by mylastore** [comment]
I figure out how it works, only for the root user.

**Comment by mylastore** [comment]
By the way twitter images are not displaying see above image. This is what's been pass for that.
 tweet.user.profile_image_url.replace('_normal', '');

**Comment by YasharF** [comment]
I think the twitter image issue is because of this issue: https://github.com/sahat/hackathon-starter/issues/622

**Comment by YasharF** [comment]
The related PR has been merged.  Closing this issue.
