### ISSUE TITLE
Bluemix MongoDB environment variable is incorrect

### ISSUE THREAD

**Issue by wghilliard** [sahat/hackathon-starter#624]
> Then set it as an environment variable for your application by running cf set-env [your-app-name] MONGODB [your-mongodb-uri] 

should be changed to 

`cf set-env [your-app-name] MONGODB_URI [your-mongodb-uri]`

**Comment by YasharF** [comment]
Is this still the correct format?  If so, can you submit a PR for it?

Thanks

**Comment by YasharF** [comment]
It looks like that section of readme.md has already been update.  Thanks.
