### ISSUE TITLE
FE: Hide contact form Name/Email for authenticated users

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#626]
More of a Feature Enhancement request, I might be able to do a PR for this in the next few weeks.

For a user that is authenticated, if we know their name or email address, it is redundant to ask the same info again in the Contact Form.  I'm thinking it might be a better experience if we pre-fill and disable editing those fields.  Or just prefill them and not necessarily disable them.  Also, if an authenticated user is using the form, we may want to consider sending the user info with the (email) message.

**Comment by niallobrien** [comment]
This would be a nice addition, especially for beginners who like to see examples of how to achieve such functionality. I'm not sure about disabling the fields; perhaps disable them so that a beginner can see how it's done and can easily remove that functionality if needed.

**Comment by YasharF** [comment]
Fixed in v4.4.0 release
