### ISSUE TITLE
FE: Adding SEO/social share related fields

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#627]
For better SEO ranking and social shares, pages need to have the following fields in their header:

	Language used on the page, like:
	<html lang="en">

	Page description, which will show up in the search results of the search engine to users:
	<meta name="Description" content="Description about the page.">

	Open Graph data:
	<meta property="og:title" content="Title">
	<meta property="og:type" content="website">
	<meta property="og:url" content="http://www.example.com/article.html">
	<meta property="og:image" content="http://www.example.com/image.png">

	Defining the Google Plus page for the publisher of the website
	<link rel=”publisher” href=”https://plus.google.com/+your_business_google_plus_id”>

What are your thoughts about adding them?
Language can go in the layout file for now, I am guessing that is probably fairly straight forward.  Description needs to go in every page since it should describe the page/content.  Open Graph and Google Plus publisher might be a little too much for a starter project.  As an alternative to adding them all, we can just add a block to the headerContent stub in the layout.pug, and then add the description meta to the individual pages by extending the layout.pug in each page.  I am thinking, we can probably ignore the google plus publisher page.  At this state, if anyone is interested in social share stuff they have a place on each page (headerContent) to add the OG fields for that page to.

Thoughts?

**Comment by YasharF** [comment]
One thing to consider, if we are adding some generic descriptions, someone that is picking up the framework to start a project need to figure out where to go to scrub the generic stuff and add their own branding, etc.  So that may add some complexity for some novice users that intend to publish their site to a production instance.

**Comment by YasharF** [comment]
Thinking more about this, I think this adds more complexity than what most people are looking for during a hackathon weekend.  It may make sense for a Startup Weekend (if it has a goal of revenue in 48 hrs), where participants are trying to do customer acquisition and marketing in addition to the development during the event.

Feel free to close this issue.

**Comment by LachieKimber** [comment]
I do agree with this.

**Comment by niallobrien** [comment]
@YasharF Can you make a note of this to perhaps add to a wiki document. Ie. "Going to production" or something like that? I'd really like for us to have a centralised resource of enhancements that can be added to a project should a developer decide to continue working on it beyond a hackathon scenario. Thanks.
