### ISSUE TITLE
Enable login via browserid/mozilla persona

### ISSUE THREAD

**Issue by seafoodbuffet** [sahat/hackathon-starter#63]
Please support a way to login via [mozilla persona](https://login.persona.org) using the [BrowserID](https://developer.mozilla.org/en-US/Persona?redirectlocale=en-US&redirectslug=Persona) protocol. There's a plugin that does this. https://github.com/jaredhanson/passport-browserid

**Comment by BPopson** [comment]
Persona is no longer actively developed by Mozilla. Mozilla has committed to operational and security support of the persona.org services until November 30th, 2016.

On November 30th, 2016, Mozilla will shut down the persona.org services. Persona.org and related domains will be taken offline.

If you run a website that relies on Persona, you need to implement an alternative login solution for your users before this date.

Source: https://developer.mozilla.org/en-US/Persona
