### ISSUE TITLE
Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

### ISSUE THREAD

**Issue by iveretelnyk** [sahat/hackathon-starter#635]
Hello. 

Cloned project and trying to run it. 
Getting this error in console. 

Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

**Comment by fonzarely** [comment]
Same for me. it looks that we have to change /public/js/lib/jquery.XXX back to a previous version.

**Comment by fonzarely** [comment]
@sahat could you rollback your last Merge pull request #630 ? 
Bootstrap does not accept to work with jquery from version 3.

**Comment by guruganeshm** [comment]
+ 1

**Comment by InstanceOfMichael** [comment]
quick fix for anyone just arriving on the scene:
```
git revert 78922142169a89d15fa2fdf19bff566a1143b1e2
```

**Comment by pkopac** [comment]
Just update Bootstrap to version **3.3.7**, I've done it locally just by copying .scss and bootstrap.min.js from the new version.
BTW why don't you use `bower` or something like that for front-end libs? This way is much harder to update/add dependencies. Otherwise awesome project, **love it**!

**Comment by thejordanprice** [comment]
I got this error as well on initial clone, it was an easy fix... I used jquery-2.2.4 to fix the problem.

It would be great to see this or a similar version pushed into the master. "Above 1, Below 3." lol.

**Comment by muhilham** [comment]
i got it solved using this way :

1. download https://code.jquery.com/jquery-1.12.4.min.js and save into _public/js/lib folder_
2. on layout.pug change from script(src='/js/lib/jquery-3.1.1.min.js') into  script(src='/js/lib/jquery-1.12.4.min.js')

**Comment by grytrn** [comment]
Upgrading to Bootstrap v3.3.7 resolves the issue

**Comment by sahat** [comment]
This has been fixed by @ibasaran in https://github.com/sahat/hackathon-starter/pull/667. Thanks!
