### ISSUE TITLE
Do you think this project needs vagrant for development.

### ISSUE THREAD

**Issue by tanaydin** [sahat/hackathon-starter#640]
Hello,

You know it is possible to create and manage virtual machines with vagrant and an emulator software. What do you think about a vagrant file with provisioning? It could set up all packages, settings etc. and could give developer a good development environment.

I've made one at

https://github.com/tanaydin/hackathon-starter/blob/master/Vagrantfile

I can make it better if you found it useful...

**Comment by niallobrien** [comment]
Hi, don't think this is necessary as the only dependencies are Node (manage node versions withnvm) & Mongo, all the rest are installed via npm.
