### ISSUE TITLE
Update readMe for IBM Bluemix ***

### ISSUE THREAD

**Issue by Twanawebtech** [sahat/hackathon-starter#646]
Hi Guys, 

I am a Developer Advocate for IBM Bluemix, the Bluemix readMe area is out of date, I have made a pull request with the updates. 

Thanks.

**Comment by Twanawebtech** [comment]
Readme for the Bluemix section can also be found here: https://github.com/Twanawebtech/IBM-Bluemix-Deployment

**Comment by Twanawebtech** [comment]
@sahat

**Comment by sahat** [comment]
README has been updated.
