### ISSUE TITLE
Was cluster removed?

### ISSUE THREAD

**Issue by tharrington** [sahat/hackathon-starter#648]

**Comment by sahat** [comment]
Yes, It was removed years ago, but I don't remember why at this point. I think you can do everything and more with `PM2` module nowadays. I might add PM2 to Hackathon Starter in the near future.

**Comment by slidenerd** [comment]
Sounds awesome! I first saw the native code for clustering, then i saw someone use throng saying it takes away all the pain and now we have pm2 , i had a look at it, seems like a very extensive lib, hopefully you are able to add it with the existing project
