### ISSUE TITLE
Sendgrid is sending to junk / spam email

### ISSUE THREAD

**Issue by kacak9229** [sahat/hackathon-starter#653]
Why sendgrid keep sending to junk and spam email?

**Comment by YasharF** [comment]
See documentation from Sendgrid, starting from:
https://sendgrid.com/docs/Classroom/Deliver/Undeliverable_Email/my_emails_are_going_to_spam.html

SendGrid support is the right party to reach out to if you continue having the issue.

**Comment by agbilotia1998** [comment]
If proper labels of the sender are added to the mail, in that case mail is received in inbox instead of spam or junk. For example the name or some other details.
