### ISSUE TITLE
Dropdown Menu not working for account and login on header

### ISSUE THREAD

**Issue by ricksturgeon** [sahat/hackathon-starter#654]
Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

I assume it is due to this error shown in browser console. Does it make sense to go back to an older version of JQuery and if yes how do I do that?

**Comment by GianCastle** [comment]
Simple. 

- Go and download an older version of jQuery (http://code.jquery.com/jquery-2.2.4.min.js). Copy the raw content.
- In the project, go to /public/js/lib/jquery-x.x.x, open it, select everything in the file and paste the new script you copied before.

- Rename the file to the proper version of jQuery, and go to /views/layout.pug and also rename.

A simpler approach could be that you paste the link on you script tag in /views/layout.pug, but you will depend on internet connection.

**Comment by ricksturgeon** [comment]
Thanks fixed the problem, now drop downs work again :)

**Comment by phumberdroz** [comment]
Why are we not updating the bootstrap version instead?

**Comment by tomandersen** [comment]
How would I try bootstrap 4 with this project? Or is it really better to use jquery 2?

There is a version of bootstrap called https://github.com/twbs/bootstrap/tree/v4-npm - but maybe its still boiling a little too much?

**Comment by ibasaran** [comment]
Just download bootsrap 3.3.7+ and copy to boostrap.min.js to public/js.
