### ISSUE TITLE
failing when I tried to start it

### ISSUE THREAD

**Issue by iviamontes** [sahat/hackathon-starter#656]
Hi there, I just follow the step described to in the "Getting started" section but it's failing 

It's a fresh installation and I'm using 
 - node v6.10.0
 - npm v4.4.0

![image](https://cloud.githubusercontent.com/assets/5760842/23442073/6483b60e-fdf4-11e6-91ce-8189d6a469c8.png)

**Comment by anconina** [comment]
Hi @iviamontes, it seem that port 3000 already used with other process,

Thanks
Moshe

**Comment by iviamontes** [comment]
uppss that's right.
thank you @anconina
