### ISSUE TITLE
Huge slowdown in request/response time when using localhost

### ISSUE THREAD

**Issue by dzackgarza** [sahat/hackathon-starter#672]
I know this may not be directly related to this project, but I was hoping someone here might know where this bug should be filed.

Sometime during the past few months, the time it takes for a single page to load has increased dramatically - often upwards of 10-20s, even just to render and return a small page written in Jade. I've been able to reproduce this issue on both Windows and a few *nix variants in the following way:

```bash
git clone https://github.com/sahat/hackathon-starter
cd hackathon-starter
npm install
node app.js
```
and then opening `localhost:3000` in either Chrome, Chromium, or Firefox.

Here are some times I'm seeing for just clicking around the main pages on the site:

![slowtimes](https://cloud.githubusercontent.com/assets/1149853/24164427/ecc9e63c-0e2a-11e7-9243-48ec246d5b5d.png)

~~However, as I just found out today, this issue only happens when you use the `localhost` prefix in the browser; navigating through `127.0.0.1:3000` seems to work at reasonable speeds.~~

Edit: It appears that this is still an issue, even when using `127.0.0.1`. The response times are lower, but some still take over 4s.

Any idea what might be causing this? Is this specific to node, or perhaps one of this project's dependencies that has been changed/updated recently?

**Comment by YasharF** [comment]
I have not seen such latencies and suspect it is related to your specific hardware/OS setup.  With just doing the above clone/install/run that you mentioned, I get:

```
GET / 200 558.405 ms - -
GET /js/lib/jquery-3.1.1.min.js 200 328.044 ms - -
GET /js/lib/bootstrap.min.js 200 319.047 ms - -
GET /favicon.png 200 2.967 ms - 1594
GET /api 200 287.643 ms - -
GET /contact 200 121.879 ms - -
GET / 200 105.168 ms - -
GET /api 200 136.968 ms - -

```
I'm running WSL on Win10, with latest Windows and apt-get updates; NodeJS 8.x.


Are you still having problems, or have you been able to resolve it already?
