### ISSUE TITLE
http://hackathonstarter-sahat.rhcloud.com/ down

### ISSUE THREAD

**Issue by aamirsahmad** [sahat/hackathon-starter#673]
I am unable to open the demo website as it appears to be down. Following errors occur  if I visit the domain.

![screen shot 2017-03-22 at 11 08 45 am](https://cloud.githubusercontent.com/assets/8017805/24204883/35b905ce-0ef0-11e7-930d-7da14f985a3e.png)

And sometimes `ERR_INCOMPLETE_CHUNKED_ENCODING` on Chrome.

**Comment by lukeramsden** [comment]
Still dead...

**Comment by sahat** [comment]
Demo site is back online. It stopped working due to exceeding 100% of disk quota from file uploads.
