### ISSUE TITLE
Confirmation email

### ISSUE THREAD

**Issue by augnustin** [sahat/hackathon-starter#674]
Shouldn't there be some process for sending a confirmation email after registration, and prevent access to the app without confirmation?

**Comment by mbj36** [comment]
+1

**Comment by foaadnami** [comment]
+1

**Comment by jaribu** [comment]
+1

**Comment by YasharF** [comment]
For a full framework, yes.  For a hackathon starter project, if implemented, it needs to be disabled by default, which brings up the question: should it be in this project or not.  When doing a weekend development at a hackathon and trying to demo for the judges, etc. blocking access to the app pending email confirmation can slow down the development and potentially ruin the demo (aka the email provider delaying email delivery during the live demo).

I like to see this feature since I have had projects that started at a hackathon level but then ended up in production.  Perhaps, someone can contribute a diff that we can link in the documentation, without causing issues during hackathon events.

**Comment by YasharF** [comment]
I think the main problem is, after launching a project using hackathon-starter and publicizing it to see if it gets traction, most teams find out that there are bogus signups.  I have seen two types myself so far:

1. People using bogus email addresses (what I think you are concerned about)
2. People using disposable email addresses ( https://www.npmjs.com/package/disposable-email-domains can potentially help)

From one hand, I can see how anyone that ends up with a hackathon-starter based project in production will have to deal with these two problems.  From the other hand, I'm not sure what the best way to add these enhancements would be while keeping things simple for hackathon participants.  Perhaps some code additions that by default are disabled using a flag or env variable, to keep the flow simple during the hackathon weekend.  I am not sure.  I like to see what @sahat thinks about this.

**Comment by niallobrien** [comment]
Yeah, I agree - this would be a great feature to have. Perhaps utilising NODE_ENV === 'production' we could enable this functionality?

**Comment by YasharF** [comment]
In the last two hackathons that I was at, a recurring comment was "don't have the judges look at a login screen".  Adding an email confirmation workflow in the context of a hackathon is adding more complexity in that sense.  However, I think it would be beneficial if we have at least a diff or a sample code as part of the post-hackathon action item checklist that developers can use if they want to.

**Comment by BaptisteGarcin** [comment]
A diff or a sample code would be more than welcome and would help me (and others I'm sure) a lot

**Comment by monkeywithacupcake** [comment]
Regarding sample code @BaptisteGarcin  - do you think it makes sense just to have a gist with the Mailgun approach to validation baked into any email address use cases? - either as middle ware or part of a waterfall?

https://documentation.mailgun.com/en/latest/user_manual.html#email-validation

TBH - I'm not sure how to do this with SendGrid (the default in this repo) since I am more familiar with Mailgun

**Comment by YasharF** [comment]
> I'm not sure how to do this with SendGrid (the default in this repo)
You would  need to replicate most of the lost password token code, but instead of resetting the password the logic would need to set a (new) verified boolean field in the user profile data.

**Comment by geekything** [comment]
I would welcome a diff or gist on how to do this as it's beyond my skill level.

From a hackerthon perspective, I think it's not implausible that you might to demonstrate that you're capturing legitimate users rather than crud.

**Comment by YasharF** [comment]
I typically end up at a couple of hackathons every month either as a mentor, judge, or an attendee.  Unfortunately, the focus in most cases is the teams ability to deliver a unique value or solve a problem, and email verification ends up as a friction point in the demo.  In most cases attendees have 2-5 minutes to demo to the judges, and spending 30 sec to 1 min for an email confirmation that is not unique to the solution is taking time away from showing differentiating parts of the implementation. With that said, I am still planning to add something, but it would not be active on the mainline release and won't be supported in the long run here.

**Comment by geekything** [comment]
@YasharF Anything you could add as a starting point would be much appreciated.

**Comment by augnustin** [comment]
Indeed, this doesn't make sense for any hackathon project ...

But,

I reckon this project is the most advanced one in terms of fully featured node.js web app base, since there is no Rails/Django equivalent in this technology (or is there? Sails.js is not robust enough IMHO).

So in my opinion `hackathon-starter` is just a name (and a judicious one) for a project that has much larger usage for many of us. For this reason, I think this would make sense to have pluggable user-confirmation process (disabled by default no problem).

Also, I hope a hackathon project is not only about the 3/4 minute demo, and that it is meant to be published and accessible to real users afterwards. So this means all teams will have to implement it on their own after the event? This would save some time and clean some code!

I am not working with node.js currently so not available for this, but definitely :+1: :+1: :+1: for  me. :smile:

**Comment by niallobrien** [comment]
> since there is no Rails/Django equivalent in this technology (or is there? Sails.js is not robust enough IMHO).

Check out https://adonisjs.com :)

**Comment by YasharF** [comment]
Resolving with: https://github.com/sahat/hackathon-starter/commit/7528032446946d93592379adbc2409aff7917747

- Email verification in the user profile page.  The verification process also checks to make sure the email address is not on a disposable email domain.

A couple of screenshots:

---
![image](https://user-images.githubusercontent.com/6448697/62001491-9c02ce00-b0a6-11e9-8ee1-23f50c209832.png)

---

![image](https://user-images.githubusercontent.com/6448697/62001493-a1f8af00-b0a6-11e9-980c-518cba9c6dda.png)

---
