### ISSUE TITLE
how I can save several email templates for individual user via UI ? 

### ISSUE THREAD

**Issue by jpca999** [sahat/hackathon-starter#677]
It would be very helpful to know if someone else has implemented a functionality like this,

I want to give the users to have the ability to create their own email templates, and save them as templates, in each user's personal settings.

Here's how it would look like

![image](https://cloud.githubusercontent.com/assets/1026325/24621535/ce3941d2-186f-11e7-964c-af4e1c079ccf.png)

Following are the Issues I need help with :

With current implementation, we'd have to hard code/ write that each email template in the file,
How i can implement the variables like {{username}} {{agent_name}}
Thanks in advance :-)

**Comment by YasharF** [comment]
Besides hardcoding a template, the function is currently not in the project.  A couple of potential resource for doing this:

- https://stackoverflow.com/questions/37639037/how-to-use-template-engines-to-send-text-as-email-in-nodejs
- https://community.nodemailer.com/2-0-0-beta/templating/

There are also a few pre-existing npm modules such as email-templates and nodemailer-express-handlebars (listed at https://nodemailer.com/plugins )


Any thoughts on what could be a more desired way to do this?  What are the use cases that this can address during a hackathon weekend and help the teams get done quicker?

**Comment by niallobrien** [comment]
I honestly don't think this would be within the scope of this project.
