### ISSUE TITLE
Update Node support to 6.10.* (LTS)

### ISSUE THREAD

**Issue by peterblazejewicz** [sahat/hackathon-starter#682]
If version support is bumped up, there are some direct gains. For example after Docker files update to 6.10.* version the Yarn package will be available for quicker setup. The current 6.6.0 Docker image does not support Yarn (amongst other things).
https://github.com/nodejs/docker-node/blob/master/6.10/Dockerfile
Is this OK with to go with update?

Thanks!

**Comment by YasharF** [comment]
I can't find a place where the node engine is locked to any specific version.  Can you clarify what you are asking?

The following files don't have a mention such as "engines": {   "node": "6.8"  }", etc.  Let me know if there is something I missed.
https://github.com/sahat/hackathon-starter/blob/master/package.json
https://github.com/sahat/hackathon-starter/blob/master/docker-compose.yml
https://github.com/sahat/hackathon-starter/blob/master/Dockerfile

**Comment by peterblazejewicz** [comment]
@YasharF Hm, I can't find it either. I won't be able to find a correct reference now, so while I believe I have a valid intent, let me close this and 🙇 for a noice.
Thanks!
