### ISSUE TITLE
how can i swap out put with just html ?

### ISSUE THREAD

**Issue by jpca999** [sahat/hackathon-starter#687]

**Comment by komcal** [comment]
You can't do it because this app is rendered by pug.
And normal html can't send data from controller. If you want html syntax i recommend to use handlebar template https://github.com/ericf/express-handlebars instead pug.
you can change it in `app.js`

**Comment by YasharF** [comment]
What was the use case that made you want to use html?  Converting HTML to pug is fairly easy and there is even http://html2jade.org that can be used to get it done using a couple of copy-pastes.

**Comment by niallobrien** [comment]
Also, as @komcal stated, we need a dynamic templating system on the server to dynamically generate our html based on the data passed to each view (as well as being able to iterate and conditionally display content). Regular html does not facilitate this.
