### ISSUE TITLE
Adding i18n

### ISSUE THREAD

**Issue by starcharles** [sahat/hackathon-starter#690]
There is i18n internationalization library for node.js, express application.
Do you want to add this to hackatho-starter? 
From the point of view  top use of this boilerplate for production, not only for instant hackathon use.

**Comment by YasharF** [comment]
There is https://www.npmjs.com/package/i18n-express as a potential way to implement i18n in your project.  

As far as hackathon-starter goes, a concern as far as adding i18n goes would be the potential amount of complexity that it may add during hackathon weekends.  Considering that we want folks to get started and running in the least amount of time, it might be too much complexity for them to have to hackle their views, etc while keeping separate JSON files for all the strings for the views.

**Comment by niallobrien** [comment]
Unfortunately I agree. Yes, this functionality would be really nice, especially when progressing a Hackathon project from a weekend project to a full production app, however, it's at that point that the devs would introduce that functionality if their app really needed it. Introducing it from the start would unfortunately add extra, unnecessary complexity up-front to a weekend project which not all users would want and is against the goals of this project. Please feel free to fork this project and add this functionality if it's something you feel you personally need on a regular basis.
