### ISSUE TITLE
How to change theme?

### ISSUE THREAD

**Issue by maciej-w** [sahat/hackathon-starter#695]
How to change a theme to e.g. flatly in the newest release?

Is there a flag somewhere?

**Comment by aligajani** [comment]
Same issue

**Comment by itsafnat** [comment]
All you have to do is to modify the @import in public\css\main.scss:
@import "themes/flatly/variables";
@import "themes/flatly/ flatly";
Clear your browser cache or go incognito if you are using chrome.

**Comment by signaturr** [comment]
I did that, but the sass files are never compiled to *.css files - what am I missing? thanks, Rob

I do see things in app.js  like:
```
app.use(sass({
```

**Comment by radnor** [comment]
The [node-sass-middleware](https://github.com/sass/node-sass-middleware) module is responsible for recompiling `\public\css\main.scss` into `\public\css\main.css`. https://github.com/sahat/hackathon-starter/blob/bfaf67978460982ac5accc9b5835a257f1acf09c/app.js#L68-L71

Then change the theme on lines 1 and 6 as @itsafnat mentions above. https://github.com/sahat/hackathon-starter/blob/bfaf67978460982ac5accc9b5835a257f1acf09c/public/css/main.scss#L1-L6

If you don't see any changes then make sure your browser isn't caching the css.
