### ISSUE TITLE
Use async/await instead of promises (Node 7.6+)

### ISSUE THREAD

**Issue by plegner** [sahat/hackathon-starter#698]
ES6 [async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) is supported by Node 7.6+ with [V8 5.5+](https://v8project.blogspot.co.uk/2016/10/v8-release-55.html). This allows many of the promise-based functions to become much simpler and more readable.

For example, the [postReset](https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L242) function would simplify to:

```javascript
exports.postReset = async function(req, res, next) {
  // ...

  try {
    const user = await User.findOne({passwordResetToken: req.params.token})
        .where('passwordResetExpires').gt(Date.now());

    if (!user) { /* ... */ }

    user.password = req.body.password;
    user.passwordResetToken = undefined;
    user.passwordResetExpires = undefined;

    await user.save();
    await req.logIn(user);

    const transporter = // ...
    const mailOptions = // ...
    await transporter.sendMail(mailOptions);

    req.flash('success', {msg: 'Success! Your password has been changed.'});
    if (!res.finished) res.redirect('/');

  } catch (e) {
    next(e);
  }
}
```

**Comment by niallobrien** [comment]
Maybe we should get a PR together for this?

**Comment by niallobrien** [comment]
We'd most likely need a wrapper function which would do the try/catch so we wouldn't have to litter the entire codebase with such blocks.

**Comment by Kessir** [comment]
Hi Everyone, any update  on this?
I totally agree with the idea of using a wrapper.

**Comment by YasharF** [comment]
My 2 cents is to hold off on this since if I understood the original posting correctly, this will mean that the project will no longer be compatible with NodeJS versions prior to 7.6.

The current LTS version of NodeJS is Node 6; Node 7 will never be an LTS version, and Node 8 is slated to become LTS later this month.  Assuming we wait for NodeJS 8's LTS status, my other 2 cents would be to wait for a few months for the underlying dependencies and other parts of the ecosystem to have a chance to move from Node 6 to Node 8 at least, and then draw the line in the sand and migrate the project with a major version increment.

**Comment by Kessir** [comment]
@YasharF That's a fair point.

**Comment by YasharF** [comment]
NodeJS 8.x branch is now the latest LTS.  Has anyone done testing of HackatonStarter on NodeJS 8?

**Comment by niallobrien** [comment]
It'll run fine no doubt, but we're on about converting the app from
callbacks and promises to async/await, which so far not all dependencies
support.

**Comment by YasharF** [comment]
Has anyone done a dry run to see if which dependencies are still a blocker?

**Comment by niallobrien** [comment]
I don't think there are any blockers any more, but as I stated, we'd need to introduce a global error handler to write cleaner code as described here: https://www.google.ie/amp/s/blog.grossman.io/how-to-write-async-await-without-try-catch-blocks-in-javascript/amp/

However, I feel that this may be a better solution overall as it allows us to throw an error and still looks clean, what do you guys think? https://www.npmjs.com/package/express-async-errors

**Comment by plegner** [comment]
I don't think Passport.js supports promises yet (e.g. for `req.logIn()`). Also, Express is making some changes in [v5](https://github.com/expressjs/express/pull/2237), that would avoid needing a try/catch [inside every request handler](https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016).

In both cases, it is relatively easy to monkey-patch the dependencies until they are updated…

**Comment by niallobrien** [comment]
Thanks for the update @plegner. I haven't looked at v5 of Express yet, can you forsee us needing to make many changes to the existing code?

**Comment by YasharF** [comment]
Parking this here for now:

**Task item** - When migrating to async/wait make it easier to have custom messages to the user as part of the error handling, while still providing the developer the stack dump/error dump for troubleshooting.

In the current code, in some places the promise statements are supposed to return the error for the express error handler (which gives a 500 error in the browser - like when the DB write fails during a password reset), and in some other place the user gets a flash message about the error (like when the Contact form fails to send the email to the dev team).  A more unified error messaging probably makes more sense; most likely one that is not a 500 server error with a partial stack dump.


Related: https://github.com/sahat/hackathon-starter/issues/732

**Comment by niallobrien** [comment]
What do you think about using https://www.npmjs.com/package/express-async-errors ?

**Comment by plegner** [comment]
@niallobrien I'm using `express-async-errors` at the moment, and it works very well. I'm not sure if there are any other breaking changes in Express v5, but I assume they would be relatively easy to refactor…

**Comment by YasharF** [comment]
PR https://github.com/sahat/hackathon-starter/pull/814 needs review.

**Comment by YasharF** [comment]
PR https://github.com/sahat/hackathon-starter/pull/814 needs review.  There are a lot of changes across the entire project for moving to async/await, removal of bluebird, changes to error handling, and migrating from request to axio

**Comment by YasharF** [comment]
It looks like we have only three places left to change from promise to async/await at this point:

https://github.com/sahat/hackathon-starter/blob/c6e689c224228f78f5c4c2f6563d65eb4540946f/controllers/api.js#L178
https://github.com/sahat/hackathon-starter/blob/c6e689c224228f78f5c4c2f6563d65eb4540946f/controllers/api.js#L188
https://github.com/sahat/hackathon-starter/blob/0593913af42627699a27385065ee68cac6fc702f/controllers/user.js#L271

**Comment by YasharF** [comment]
Thanks to contributions from @nacimgoura It looks like we have only three places left to change from promise to async/await at this point:

https://github.com/sahat/hackathon-starter/blob/c6e689c224228f78f5c4c2f6563d65eb4540946f/controllers/api.js#L178
https://github.com/sahat/hackathon-starter/blob/c6e689c224228f78f5c4c2f6563d65eb4540946f/controllers/api.js#L188
https://github.com/sahat/hackathon-starter/blob/0593913af42627699a27385065ee68cac6fc702f/controllers/user.js#L271

**Comment by YasharF** [comment]
Closing this issue in favor of https://github.com/sahat/hackathon-starter/issues/720
