### ISSUE TITLE
Shouldn't errorhandler middleware be only active in development env?

### ISSUE THREAD

**Issue by giacomocerquone** [sahat/hackathon-starter#703]
Hi everyone, this starter is just awesome! Thank you for your work.
I'm opening this issue because I saw there is an always active error handler middleware in app.js.
I think it should be called just in env_mode as stated also on the github repo of the middleware: https://github.com/expressjs/errorhandler

**Comment by giacomocerquone** [comment]
Up?

**Comment by YasharF** [comment]
It looks like, https://github.com/sahat/hackathon-starter/blob/master/app.js#L220 needs to be modified to look like 
```
if (process.env.NODE_ENV === 'development') {
  // only use in development
  app.use(errorhandler({log: errorNotification}))
}
```

Is that right?

**Comment by giacomocerquone** [comment]
Exactly @YasharF

**Comment by niallobrien** [comment]
Where are the errors logged to in production so?

**Comment by giacomocerquone** [comment]
I believe it is considered a good pattern to allow the logger (a middleware in this case) to log different kind of errors in a production and in a development environment.

Anyway this middleware, as stated by the developer, doesn't work well in a production environment (maybe because it's too greedy, idk), so I would switch to something else at this point.

Have a look at https://stackoverflow.com/questions/41144288/nodejs-debug-errors-in-production and see if it helps

**Comment by YasharF** [comment]
I have https://www.npmjs.com/package/express-winston in most of my prod sites, but at the same time, I think diverting the errors to Winston (db) during a hackathon can create some confusion for new developers.

This makes me wonder if instead of changing https://github.com/sahat/hackathon-starter/blob/master/app.js#L220 and potentially adding Winston, if it might be a better idea to have some Wiki like documentation on "Post Hackathon" things to do, including changing error logging and other issues or features that has been brought up.

**Comment by niallobrien** [comment]
That's not a bad idea, as I usually implement my own asset pipeline too
(another often asked question) when taking a site to prod.

**Comment by giacomocerquone** [comment]
Post hackaton sounds like a great Idea, but in my opinion it's necessary somehow to not run the express errorhandler in prod mode.

**Comment by niallobrien** [comment]
Are you in a position to submit a PR @giacomocerquone as this seems like a sensible default to have in place.

**Comment by YasharF** [comment]
Do we have prod-devo conditions in any other place thou?
Here is a scenario I would be concerned about:  Hackathon team has been working on their idea for over a day and they are in the last stretch before demos and want to deploy to a server.  They deploy  to the server, something breaks, and the behaviour is different between what they have on their laptop and what they have in their desktop deployment.  Now they have to scratch their head to figure out why things are behaving differently, not realizing there is conditional code there.
Or that something else just breaks after their deployment and they are not getting enough data out about the issue to see why what they have is not working.

**Comment by niallobrien** [comment]
Yeah, that's a fair point. I'll try get started on some "Post-Hackathon" documentation this week and that would give us a good place to document such recommendations.

My only other suggestion for this particular scenario would be to modify the start script to set NODE_ENV=development. This would allow us to implement this change without disrupting the Hackathon development and deployment experience. I'd need to add cross-env as a dependency to ensure it works on Windows too, but it's a piece of cake. Then we could simply document this for when people want to go to production (as we're already assuming that users would rather  deploy the dev environment when in a Hackathon scenario).

**Comment by giacomocerquone** [comment]
Actually @YasharF the real question here is: do most people use this starter for a hackaton or not? Personally I always saw this project used as a starter for a real-world application scenario. I believe you should investigate more on how this code is used and only then decide what to do.

If this should stay as a hackaton project, I'd enable the errorhandler in dev mode too but I'd absolutely make sure to write everything down on a Post Hackaton doc

**Comment by niallobrien** [comment]
Also of note is that I maintain a fork of this project which I call Hackathon Starter+ in which I've added an asset pipeline with asset filenames hashed for production, socket.io support and any other production-ready functionality that fits more into a kind of framework as opposed to a boilerplate. I'll most likely add the above changes to the fork, which we can still document here. My fork will most likely include all "Post Hackathon" recommendations and am happy to add any collaborators if they really want to push things further than the scope of a Hackathon Starter project.

**Comment by giacomocerquone** [comment]
@niallobrien I did the same thing for a mean based app starter with angular 5... as you see @YasharF only in this discussion you found two people that didn't use this boilerplate with a hackaton mindset

**Comment by niallobrien** [comment]
While that's true, @sahat has been very adamant on keeping this project as simple as possible. The goals of this project are clearly spelled out in the Readme and while I'd certainly love to see a lot more advanced functionality added, I can understand and respect his perspective & goals for the project.

**Comment by giacomocerquone** [comment]
We always respect other's coiches :smiley: forks do exist for a reason.
He'll decide for this matter

**Comment by niallobrien** [comment]
What I proposed above is a reasonable solution imo; we make the change but set the env to always be dev when you run `npm start`. It would then be much easier to document the change the user has to make there if they wish to go to production.

**Comment by niallobrien** [comment]
Actually, it would be much easier to just flip the conditional to `process.env.NODE_ENV !== 'production'`

**Comment by YasharF** [comment]
Found this: https://github.com/sahat/hackathon-starter/issues/574#issuecomment-249408643

From Sahat: 

> I am against the idea of adding flags to the templates in this project.

**Comment by niallobrien** [comment]
This project doesn't seem to rely on any env vars so I think it wouldn't be a good idea to introduce them now. As the middleware's Readme says "the full error stack traces and internal details of any object passed to this module will be sent back to the client when an error occurs" which would be a concern in production but I think if you get this error when presenting your Hackathon project, then you've bigger concerns 😂
We can document this as a recommendation in a "Post Hackathon" document instead in keeping this project environment agnostic. If this were a more serious issue or if further scenarios present themselves which require that we introduce env vars, then perhaps we can revisit this issue then.

**Comment by marcospgp** [comment]
I thought "hackathon-starter" was just a name, I would risk guessing that over half of the people using this boilerplate are not participating in a hackathon.

**Comment by YasharF** [comment]
Fixed with  https://github.com/sahat/hackathon-starter/commit/e78e82d691cd7fa68a520241e778eb062df73445
