### ISSUE TITLE
is implementaton of RESTful API possible?

### ISSUE THREAD

**Issue by S2606** [sahat/hackathon-starter#708]
during hackathons,we need to fetch/post data from mobile application or other way. Is it possible through this because i am unable to figure it out??

**Comment by YasharF** [comment]
Are you doing a native Android or iOS app and need a RESTful backend?  Can you add a bit more about your use case?

**Comment by niallobrien** [comment]
Yes this is possible but this might not be the best boilerplate for your needs as this project is primarily focused on responsive web apps (server side views, scss, clientside JS etc.).
I'd recommend you fork this project and strip out all functionality that's not required and simply focus on building RESTful routes for your use case.
