### ISSUE TITLE
CSRF token missing on form submit in ng4.

### ISSUE THREAD

**Issue by gbrigens** [sahat/hackathon-starter#710]
@sahat thanks for this awesome project. I started working on a MEAN project hackathon-starter  as my authentication api and angular 4 as my frontend. First I got cross origin error searched online and I had to install a plugin to sort the issue on chrome. Is there any another way to fix CORS?

Lastly I can not submit a form for registration I get this error 403 "CSRF token missing"

Here is my code for service in angular4
`  registerUser(user) {
    let headers = new Headers();
    headers.append('Content-Type', 'application/json');
    return this.http.post('http://localhost:3000/signup', user, {headers: headers})
      .map(res => res.json()); 
  }`

I added this to my form but it did not save the issue as you have mention in the read me.
`<input type="hidden" name="_csrf"/>`

**Comment by YasharF** [comment]
<input type="hidden" name="_csrf"/> is missing the value.  See https://github.com/sahat/hackathon-starter/blob/master/views/account/signup.pug#L7
