### ISSUE TITLE
main.js isn't linked?

### ISSUE THREAD

**Issue by abwilf** [sahat/hackathon-starter#717]
Hi - love the boilerplate.  I'm just having one issue -  I've downloaded the boilerplate and put this code in main.js, but when I fire up the server and go to the home page, nothing console.log's.  Why is this?  I'd like to use main.js if possible, but it seems like it's not linked correctly.

```
$(document).ready(function() {

	console.log("HOLLA!");

});
```

**Comment by YasharF** [comment]
Quick question, where are you looking for the output of the console.log and it is missing?  main.js is for the client side JavaScript.

**Comment by Deamoner** [comment]
i've also put code in that location and nothing fires. Infact I notice that the file downloaded from the server does not have the new code in it.

**Comment by bassie1995** [comment]
The issue might be that your browser is loading the file from cache, try Shift + F5 or right-click the reload icon with Dev Tools open and do a hard reload with cache clear.
