### ISSUE TITLE
Any modelling of user role, ie admin? With perhaps a registered users overview?

### ISSUE THREAD

**Issue by mrmayfield** [sahat/hackathon-starter#719]
I'd like to see if there is any modelling of user roles [user, admin] etc

It would be great if a user admin could see an overview of all registered users via an /admin type path

Does this exist? (Doesn't look like it at first glance). IS it against your philosophy to add it?

**Comment by niallobrien** [comment]
This suggests the use of user roles etc. which is beyond the scope of this project. This is certainly something best left as an exercise to the end user and is a great learning process.

**Comment by mrmayfield** [comment]
Agreed leaving it vanilla is just fine, was just curious.

**Comment by niallobrien** [comment]
However, much like the Socket.io section in the the Readme; if you do add it, document how you can do it, what changes have to be made to the default boilerplate etc. so that someone can easily add such functionality if needed.

This would be a useful section in the Readme in my opinion and a PR would be welcome.

**Comment by mrmayfield** [comment]
Just working on a prototype app I want to get out the door, if it works out I'll pay it back by contributing to this project. :) Definitely a fun one.

**Comment by atonb117** [comment]
There was a closed issue that suggested roles as boolean values in the user model.  I did a quick search but could not find it.  You may have better luck/more time.

You can then reference one of the many dash board templates to create a view that displays users and their roles.
