### ISSUE TITLE
Refactor using ES6 promises & async/await

### ISSUE THREAD

**Issue by mayeaux** [sahat/hackathon-starter#720]
Promises are a lot more readable and fun to work with. Any plans to refactor with ES6 promises and async/await, would you be open to that for the project?

**Comment by niallobrien** [comment]
There's quite a difference between promises and async/await with regards to syntax and this projects is already utilising promises. Have you noticed somewhere where promises aren't being utilised? If so, it would make a great PR.
Regarding async/await - it would require a lot more changes and further consensus from the community as to whether most would want to use try/catch or use a general catch method in a wrapper and use that wrapper instead.

**Comment by mrmayfield** [comment]
Thanks for the response. Maybe I'm crazy but everything looks to be done using callbacks to me. For example: https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L36

I'm pretty sure Mongoose returns promises by default so they should be thenable. 

As for async/await, it's been shipped in native node for a while and makes code noticeably more readable & easy to interact with, especially for novices (who struggle with the callback concept, also there's no more callback spaghetti).

Am I really the first to have brought up using async/await? 😆

**Comment by niallobrien** [comment]
Please submit a PR for any code improvements you can contribute.
Have you seen this previous PR? https://github.com/sahat/hackathon-starter/pull/638

Regarding async/await, no you're not. See https://github.com/sahat/hackathon-starter/issues/698

**Comment by slidenerd** [comment]
You could always make another branch with async await :) and link the README.md to it, i didnt want to open a new issue, hence a comment here, the main.scss file is using an outdated layout it seems, would it be possible for you to add a gist on the same layout done with a flexbox/css grid instead Thanks

**Comment by YasharF** [comment]
If anyone is interested to help with PRs, an intermediate task in the backlog is also:

- Remove bluebird package since Node.js has supported promises for a while, and Node.js 8 now supports utils.promisify() to turn callbacks into promises.

This could be done independently before a larger refactoring, since bluebird is only used in a few places.

**Comment by nacimgoura** [comment]
@YasharF I can watch that this weekend. 😃
