### ISSUE TITLE
Error: CSRF token missing at checkCsrf 

### ISSUE THREAD

**Issue by SriramJothiswaran** [sahat/hackathon-starter#724]
I use angularjs with ejs instead of pug. when i include angular contoller js from public directory i get "Error: CSRF token missing at checkCsrf " and in the browser console i get "POST http://localhost:3000/ 403 (Forbidden)" error. Kindly help me in sorting this error

**Comment by YasharF** [comment]
Are you sending the CSRF token with your request?

**Comment by YasharF** [comment]
Closing this since it seems like the requester has been able to resolve the error in their case.
