### ISSUE TITLE
Twitter images broken.

### ISSUE THREAD

**Issue by shahzeb1** [sahat/hackathon-starter#728]
On the route `/api/twitter` the images aren't loading / appear broken.

![image](https://user-images.githubusercontent.com/1383831/29503884-6b409866-85f0-11e7-85f6-1ec20e3bbd3c.png)

I have checked with the chrome console, and the image's are never being retrieved. Will try to fix this.

**Comment by shahzeb1** [comment]
Looks like the image URL is being passed into the twitter.pug view, but instead of setting the image src to the image URL, it is being set to `src="#{image}"`

**Comment by shahzeb1** [comment]
![image](https://user-images.githubusercontent.com/1383831/29503979-19820702-85f1-11e7-88bf-5d18550fc9ab.png)
Figured it out

**Comment by YasharF** [comment]
PR merged.  Closing the issue.  Thank you.
