### ISSUE TITLE
"docker-compose up web" app starts, but not serving any requests

### ISSUE THREAD

**Issue by vak** [sahat/hackathon-starter#729]
I tried both `docker-compose up web` and `docker-compose up`. 
URL `http://localhost:8080` is suggested to be used during the console output on start of `docker-compose up web`, but this port isn't even listened. Instead, port 3000 is listened.
Attempt to open http://localhost:3000 leads to connection reset 
The port 8888 is mentioned in Dockerfile
All this tried on Ubuntu 16.04.1 LTS

It's funny but the app based on hackathon-starter from March'17 is running using docker-compose just fine. 

Any ideas?

**Comment by vak** [comment]
I've changed hardwired port to 3000 in app.js:63 and it worked:
`app.set('port', process.env.PORT || process.env.OPENSHIFT_NODEJS_PORT || 3000);`

**Comment by MaxToyberman** [comment]
another option would be to add `ENV PORT=3000`
in your Dockerfile

**Comment by YasharF** [comment]
Assuming that we don't want to modify [app.js#L63](https://github.com/sahat/hackathon-starter/blob/master/app.js#L63), is this a bug in the Docker related files?  I see two ports listed in the following two files, which are different than the default port 8080 in app.js#L63 :

1. https://github.com/sahat/hackathon-starter/blob/master/docker-compose.yml#L8
2. https://github.com/sahat/hackathon-starter/blob/master/Dockerfile#L14

**Comment by YasharF** [comment]
I did some testing, and the port mismatch was an issue.  Now fixed as part of https://docs.docker.com/compose/compose-file/compose-versioning
