### ISSUE TITLE
Mongo DB errorDb.prototype.authenticate method will no longer be available

### ISSUE THREAD

**Issue by signaturr** [sahat/hackathon-starter#744]
Should this be fixed?

## I got error in Terminal on Mac:
`Db.prototype.authenticate method will no longer be available`

## So I added
```js
,  { useMongoClient: true }
```

in app.js

```js
/**
 * Connect to MongoDB.
 */
mongoose.Promise = global.Promise;
// rob added , { useMongoClient: true } to get rid of error 
mongoose.connect(process.env.MONGODB_URI || process.env.MONGOLAB_URI,  { useMongoClient: true });

```

Thanks for a great starter tool

Rob

**Comment by YasharF** [comment]
https://github.com/sahat/hackathon-starter/pull/738/files

**Comment by YasharF** [comment]
https://github.com/sahat/hackathon-starter/pull/738

**Comment by YasharF** [comment]
Duplicate of https://github.com/sahat/hackathon-starter/issues/739 ; the issue is not resolved because of an update to connect-mongo
