### ISSUE TITLE
MongoError: Unknown modifier: $pushAll when linking Twitter account

### ISSUE THREAD

**Issue by alangibson** [sahat/hackathon-starter#745]
With Mongo 3.5.13, I'm getting the following error when trying to link a Twitter account:

```
500 MongoError: Unknown modifier: $pushAll
   at Function.MongoError.create (/home/alangibson/dev/content-freshener/gui/web/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
   at toError (/home/alangibson/dev/content-freshener/gui/web/node_modules/mongoose/node_modules/mongodb/lib/utils.js:139:22)
   at /home/alangibson/dev/content-freshener/gui/web/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1060:67
   at /home/alangibson/dev/content-freshener/gui/web/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickCallback (internal/process/next_tick.js:180:9)
```

Fix is to add 'usePushEach: true' option to User schema.

See https://github.com/Automattic/mongoose/issues/5574.

**Comment by DevJoseWeb** [comment]
'Unknown modifier: $pushAll'

**Comment by YasharF** [comment]
Per https://github.com/Automattic/mongoose/issues/5574#issuecomment-354609565 the issue has been resolved in Mongoose 5.x .  Hackathon-starter's version of mongoose npm package was upgraded from 4.11.7 to 5.0.9 with https://github.com/sahat/hackathon-starter/commit/11bb9a74ddaf1413a651d5856a9f55965917c6db

Have you tried the upgrade, or a rebase to pull in the latest changes?  Does the problem persist after the mongoose upgrade without changing the User schema?
