### ISSUE TITLE
CSRF fix

### ISSUE THREAD

**Issue by Andersama** [sahat/hackathon-starter#752]
Due to the number of issues that you've got about lusca and multer and that chaos I figured I'll overview the problem and how to fix it.

At the moment the repo has this bit of middleware to apply lusca to every route w/ some exceptions. 
```javascript
app.use((req, res, next) => {
  if (req.path === '/api/upload' ) {
    next();
  } else {
    lusca.csrf()(req, res, next);
  }
});
```
Here the repo is avoiding using lusca before multer, because without it (assuming we've injected and rendered lusca's csrf token into the form) we get an error that the CSRF token is missing...

Why? Well lusca is programmed to find the token from req.body or req.headers

```javascript
//from: https://github.com/krakenjs/lusca/blob/master/lib/csrf.js
        // Validate token
        _token = (req.body && req.body[key]) || req.headers[header.toLowerCase()];
```
and body-parser (the middleware which is setting req.body for post requests) specifically doesn't handle multi-part forms...the ones we'd like to use for file uploading. So lusca screams in our face because the csrf token is indeed missing...in fact...the entire req.body object is empty {} when lusca is called.

Well...hot damn

This is also why lusca works properly after multer*, because multer also sets req.body with post fields. That's not exactly helpful though because multer will have downloaded the files before a csrf check can be made. Unless we take advantage of multer's fileFilter and somehow run lusca with only the req object we're SOl...

But there's the problem as a whole, body-parser works on everything but mult-part encoded requests (and it doesn't appear they're planning on adding support)...and so req.body is not set.

But multer isn't the only middleware which can parse a multi-part request, in fact body-parser makes a few recommendations. 

Solution: Use other middleware(s) to make sure req.body is parsed and set BEFORE lusca is used.

One way to go around this is to require express-formidable and replace the original hackish work-around like this:
```javascript
//body-parser
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
//formiddable
app.use(formidable());
app.use(expressValidator());

...

app.use((req,res,next) => {
//formidable outputs to req.fields and req.files / req.file so we can get dirty here
  if(Object.keys(req.body).length == 0 && req.fields){
    //Object.assign(req.body,req.fields);
    req.body = req.fields;
   }
   //tada req.body is here (and so would be our csrf token)
  next();
});
app.use((req, res, next) => {
  if (req.path === '/api/upload') {
    lusca.csrf()(req, res, next);
  } else {
    lusca.csrf()(req, res, next);
  }
}
```
There's probably a way of running formidable only when needed...but that's some optimization that someone else can sort out.

**Comment by niallobrien** [comment]
Hey man, care to put together a PR? Thanks.

**Comment by jamesliudotcc** [comment]
According to the OWASP, putting CSRF tokens in the URL is not recommended. The explanation is about using GET, but the same applies when the URI is used for POST:

https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md

I think the better solution here is to assemble the body before calling lusca.

**Comment by YasharF** [comment]
If I am reading it correctly, it looks like even though it is not recommended, it might be a backup option, better than nothing that is there right now.

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/bc6f4bb783d9154e3e6448c50efbb50eecfc010f
