### ISSUE TITLE
Best practice to manage static assets per page/controller ?

### ISSUE THREAD

**Issue by yanisIk** [sahat/hackathon-starter#753]
Hi everyone,

I'm using a similar stack (in fact I started with this boilerplate years ago and modified it to my needs) but I still don't feel confident about how I manage my static assets and can't find any guidelines in the Readme.

For now, I have one folder per page in the public/css public/js folders containing the respective stylesheets and scripts.

Then this is how I import my static assets on each page (inside the layout.hbs template):

```
{{#each stylesheets}}
      <link rel="stylesheet" href="{{this.url}}?v={{../cacheBuster}}">
 {{/each}}

{{#each scripts}}
  <script src="{{this.url}}?v={{../cacheBuster}}"></script>
{{/each}}
```

`stylesheets` and `scripts` are arrays set inside each page controller that I pass inside the res.render().

This works well for now but I think there's a better way to do this. It doesn't feel natural to take care of the static assets inside the controller.

What are the best practices for static assets managements in a server side rendered website ?

Thanks.

**Comment by niallobrien** [comment]
@yanisIk How comfortable are you with JS build tools? The ideal solution is to bundle your JS, but split the app.js to be separate from vendor.js (jQuery etc.). Stylesheets should be pre-processed into a single stylesheet. These assets should then be fingerprinted (filename should contain a unique hash) for a production environment for caching & cache-busting purposes. You then need to devise a way to know what scripts and styles to dynamically insert into your Pug layout template for each environment (development vs production).

I've implemented all of the above in a fork of this project called [Hackathon Starter+](https://github.com/niallobrien/hackathon-starter-plus) utilising Laravel Mix for asset compilation. It also uses a manifest file to map the fingerprinted assets and are dynamically inserted using a middleware for Pug. Out of the box, it also has an example of how these assets should be used etc. Run the asset pipeline in another terminal session and watch for asset changes with `npm run watch`.
Also note that Socket.io and Pjax have been enabled in my fork by default.

All the best,
Niall.

**Comment by niallobrien** [comment]
I'll try update the Readme with an example of how you can implement a full
asset pipeline at some point.

**Comment by yanisIk** [comment]
@niallobrien Thanks for your detailed answer. I will check your repo, seems really interesting.

I thought about using build tools like gulp or webpack, but dont you think that bundling everything in the same JS file is quite heavy for a server side rendered website ?
I have pages that use a lot of different libraries and custom business logic. I don't want them included in all of the pages of the site. How is this managed ?

Thanks,

Yanis.

**Comment by yanisIk** [comment]
@niallobrien Thanks for your detailed answer. I will check your repo, seems really interesting.

I thought about using build tools like gulp or webpack, but dont you think that bundling everything in the same JS file is quite heavy for a server side rendered website ?
I have pages that use a lot of different libraries and custom business logic. I don't want them included in all of the pages of the site. How is this managed ?

Thanks,

Yanis.

**Comment by niallobrien** [comment]
Hi @yanislk I just published a repo called `asset-pipeline-bootstrap` which utilises Laravel Mix (a Webpack wrapper) and Bootstrap 4. In `webpwck.mix.js` you can specify your 3rd party dependencies to be extracted into a separate file called `vendor.js` and your custom application code remains in `app.js`. Compare this repo with Hackathon Starter+ to see how these things are being implemented.
