### ISSUE TITLE
(no password / passwordless) strategy 

### ISSUE THREAD

**Issue by mrmccormack** [sahat/hackathon-starter#755]
I was wondering the best way to implement a "passwordless" login.
It's the ONLY one I want to use for my web app.

I wondered if just modifying the "forgot your password" code would work fine, and be less complicated than the NPM versions, or coding in a separate method.

Thanks.

My detailed question at:
https://stackoverflow.com/questions/47003393/passwordless-no-password-in-node-express-app-use-token-from-forgot-password

**Comment by YasharF** [comment]
Can you describe your use case a bit more?
