### ISSUE TITLE
Passport not loggin out - known Passport problem.

### ISSUE THREAD

**Issue by mrmccormack** [sahat/hackathon-starter#758]
My hackathon-starter app was only SOMETIMES logging out the current user. Kind of serious issue..

Research seem to reveal the problem lies with Passportjs.
https://stackoverflow.com/questions/13758207/why-is-passportjs-in-node-not-removing-session-on-logout

So... I fixed it.
### Instead of:
https://github.com/sahat/hackathon-starter/blob/731ec259c3d17fbee8171f2d280cbdf283177b76/controllers/user.js

```js
/**
 * GET /logout
 * Log out.
 */
exports.logout = (req, res) => {
  req.logout();
  res.redirect('/');
};

```

### I used:

```js
app.get('/logout', function (req, res){
  req.session.destroy(function (err) {
    res.redirect('/'); //Inside a callback… bulletproof!
  });
});
```

**Comment by mrmccormack** [comment]
I'm working with a programmer, that suggests:

```
but we also need to remove user of req


app.get('/logout', function (req, res){
  req.session.destroy(function (err) {
    req.user = null;
    res.redirect('/'); //Inside a callback… bulletproof!
  });
});
```

**For these reasons:**

we need to remove from req(passportjs alos doing this but async way) because there is no use of user data after logout
even this will save memory and also might be passportjs found user data and may create new session and redirect(but not yet happen)
By the ways, this is our responsibility to remove irrelevant thing. PassportJS assign data into req.user after login and also remove if we use req.logout() but it may not works properly some times as NodeJS Asynchronous in nature

**Comment by niallobrien** [comment]
Hey man, can you open a PR for this fix?
Thanks.

**Comment by YasharF** [comment]
I have verified that when a user logs out, the current implementation removes the user from the session, but the session itself (identified by _id in the session table) persists.

Per https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Logout_Button when a user invokes Logout, the session needs to be invalidated at least on the server side, which is not occuring in the current implementation.

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/e9f0e8e673cbf9b0f8dd0aef808da14403ab3b4b
