### ISSUE TITLE
OAuth callback URL should be environment-specific variables 

### ISSUE THREAD

**Issue by git-issue** [sahat/hackathon-starter#762]
As said in my pr   #759 :

1. If production website supports https, It would be cause a redirect url mismatched problem, this would make user confused and spend time to debug，as shown in the following figures.
  - ![](https://user-images.githubusercontent.com/33217522/32986814-15bff9e2-cd15-11e7-826d-19d20c2c71c3.png)
  - ![](https://user-images.githubusercontent.com/33217522/32986877-53610cf4-cd16-11e7-8321-51682ae4cf7a.png)
  - ![](https://user-images.githubusercontent.com/33217522/32986830-7767abd6-cd15-11e7-897c-f491324a557b.png)
2.  I think the OAuth callback url, clientID, clientSecret and so on are all configurable. They may be changed in different environment. They should be keep consistent and save in the .env files.

**Comment by YasharF** [comment]
I have not been experiencing this problem in my https production environment.  I only use the Google account integration.  It is not for login but for linking under /account .  Everything stays on https, there are no errors, the google login window shows up, and the page redirects back to the https /account after ward with a flash message "Google account has been linked."

**Comment by YasharF** [comment]
I suspect the problem that you are encountering is that:
1. You had your application credentials with the callback URL set in Github during development
2. Everything worked fine in the dev environment, and the dev environment was using http
3. You deployed to production which was https, and then things longer worked and took a long time to troubleshoot the OAuth issue

Is that what happened?  If that is the case, perhaps the better solution would be figuring out either through documentation or other means a way to help developers with _http dev_ transition to _https prod_ for sites like Github which unlike Google only have the option for one callback URL.

**Comment by niallobrien** [comment]
I use environment variables for all oAuth callbacks, it just makes life easier - happy to submit a PR if needed?

**Comment by niallobrien** [comment]
Ah, sorry, I should've seen the PR for this. Regardless, I tend to agree that having the callback URLs in the .env file makes a lot of sense.

**Comment by YasharF** [comment]
Should it be full URL or just the host/domain part as an env variable. I haven't thought about this much, but if everything is going to be the existing paths with a protecol-domain prefix like http://mydomain.com/the/same/currently/hardcoded/callback/path  then perhaps just a single env variable using "http://mydomain.com" can solve it for all of the paths without adding a significant amount to the number of env variables.

**Comment by niallobrien** [comment]
What about ```callbackURL: process.env.GITHUB_CALLBACK || 'auth/github/callback',```

**Comment by YasharF** [comment]
There hasn't been any response from the requester.  Action item on this issue right now is to breakdown each case for each API/OAuth case and identifying what is working under what conditions and what is not working when following the instructions for localhost and when deploying to a host with SSL support.  I suspect we are dealing with ~20 cases.

**Comment by YasharF** [comment]
Closing this issue for now.  Will address them case by case when each one is identified.
