### ISSUE TITLE
Serving socket.io.js

### ISSUE THREAD

**Issue by nvlled** [sahat/hackathon-starter#765]
How does it serve socket.io/socket.io.js? I don't see any in the public directory, is it there middleware doing this? I'm asking this because I want to use libraries installed with npm in the client side, and I am unable to figure out the magic involved without using any bundler such as webpack.

**Comment by slidenerd** [comment]
A clone of this project has socket.io, check [THIS ](https://github.com/niallobrien/hackathon-starter-plus) out

**Comment by niallobrien** [comment]
Thanks for the recommendation @slidenerd 
We can close this issue.
