### ISSUE TITLE
Bootstrap 4 and Font Awesome 5

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#766]
Creating an issue to track these tasks.

- [x] Bootstrap 4 beta
- [x] Font Awesome 5

**Comment by slidenerd** [comment]
![image 1](https://user-images.githubusercontent.com/5139030/33883453-d5c8ca12-df61-11e7-82aa-b1d8cfe94a5a.png)
Looks like the UI classes in bootstrap 4 beta 2 have changed significantly :) and bootstrap social doesnt work either

**Comment by imcodingideas** [comment]
@slidenerd because scss is awesome.

**Comment by slidenerd** [comment]
@imcodingideas  the reason this feels weird is because the repo uses sass loader for scss which is pretty nice but has nothing on js, i see a bunch of js min files scattered and thats it, while i am not the greatest fan of webpack, i was wondering why the repo doesnt use cdnjs urls with a local fallback to load all js files plus babel loaders and presets, all we want in the end is cross browser es6 code that loads super fast from a cdn url with a local fallback and loads only 1 file

**Comment by niallobrien** [comment]
I implemented Laravel Mix for the front-end asset pipeline in my fork which does scss and js compilation. It also has a production option to serve optimised assets.

**Comment by YasharF** [comment]
PR for Font Awesome 5 upgrade: https://github.com/sahat/hackathon-starter/pull/799

**Comment by YasharF** [comment]
For Bootstrap 4 upgrade, I would suggest replacing the /public/css/lib/bootstrap with the npm distributed Bootstrap which includes the scss files.  In that way, we'll be dealing with less effort when there are minor version updates to Bootstrap 4, since an `npm update` would pick up the change.

For Bootstrap Social, since the current maintainer has not been able to update it for Bootstrap 4, another community member has created a fork with the updates `@ladjs/bootstrap-social`.  The following would be my suggested diffs for package.json and main.scss changes to pick up these distributions:


```
diff --git a/package.json b/package.json
index b0ee039..879cb60 100644
--- a/package.json
+++ b/package.json
@@ -9,16 +9,18 @@
   "author": "Sahat Yalkabov",
   "license": "MIT",
   "scripts": {
-    "postinstall": "npm rebuild node-sass",
+    "postinstall": "cp node_modules/bootstrap/dist/js/bootstrap.min.* public/js/lib && npm rebuild node-sass",
     "start": "node app.js",
     "test": "nyc mocha --timeout=3000 --exit",
     "lint": "eslint **/*.js"
   },
   "dependencies": {
+    "@ladjs/bootstrap-social": "^7.0.2",
     "@octokit/rest": "^15.2.5",
     "bcrypt-nodejs": "^0.0.3",
     "bluebird": "^3.5.1",
     "body-parser": "^1.18.2",
+    "bootstrap": "^4.0.0",
     "chalk": "^2.3.2",
     "cheerio": "^1.0.0-rc.2",
     "clockwork": "^0.1.4",
```

```
diff --git a/public/css/main.scss b/public/css/main.scss
index ca8693b..af2a838 100755
--- a/public/css/main.scss
+++ b/public/css/main.scss
@@ -1,6 +1,7 @@
 @import "themes/default/variables";

-@import "lib/bootstrap/bootstrap";
+@import "node_modules/bootstrap/scss/bootstrap";
+@import "node_modules/@ladjs/bootstrap-social/bootstrap-social.scss";
 @import "lib/font-awesome/fontawesome";
 @import "lib/font-awesome/fa-brands";
 @import "lib/font-awesome/fa-regular";
```

**Comment by BhaveshSGupta** [comment]
We might even need to update themes too, flatly has released a bootstrap 4 version

**Comment by YasharF** [comment]
We do need to update the themes.  I know in case of GSDK, they have posted on their website that they are working on a Bootstrap 4 release.

My first attempt for the upgrade was to use http://upgrade-bootstrap.bootply.com and just make changes to three views: footer, header, and home; there is more work to do for sure:  

![image](https://user-images.githubusercontent.com/6448697/38191692-abdc764a-361e-11e8-8141-03233235bc37.png)

**Comment by nacimgoura** [comment]
If you want, I can propose my modifications, I already use bootstrap 4 with this project personally. Not everything is perfect but it is fully functional. However I do not use any theme and I use cdn.

<img width="1182" alt="bs4" src="https://user-images.githubusercontent.com/9990521/38197377-14314590-3688-11e8-9ef9-78823547e1a0.png">

**Comment by YasharF** [comment]
I would be interested to see your changes, but I do recall that when I was attempting to use a CDN, the local Bootstrap 3 build was overwriting the Bootstrap 4 (cdn loaded) via main.css.

**Comment by nacimgoura** [comment]
@YasharF Why not create a branch in the bootstrap 4 project to share these changes without impacting the master branch?
After, I will push on this branch my modifications for bootstrap 4.

**Comment by YasharF** [comment]
I checked-in a work-in-progress branch at https://github.com/sahat/hackathon-starter/tree/bts4wip
Currently checked-in commit only swaps the libraries.  I would suggest tackling the default (theme) and the home view first:

public/css/themes/default/_default.scss
public/css/themes/default/_variables.scss
views/home.pug
views/partials/footer.pug
views/partials/header.pug

As is this is how everything renders.  Make sure to hard refresh the page to have the browser reload the css everytime that you are rebuilding the css (Shift+F5 in Chrome).

![image](https://user-images.githubusercontent.com/6448697/38208666-b1dde540-3666-11e8-98c2-ad391ef0ca94.png)

**Comment by nacimgoura** [comment]
@YasharF I just realized a pull request for bootstrap 4 #832

**Comment by mrtinkz** [comment]
@YasharF @nacimgoura Any idea when the #832 will be merged into master? thanks

**Comment by nacimgoura** [comment]
@mrtinkz Currently, I made a pull request to the bts4wip branch (temporary branch for bootstrap 4) which has not been merged yet. But I think the merge will only be done with the master branch once bootstrap 4 is properly integrated in all project pages.

**Comment by nacimgoura** [comment]
it's normal, rendering has not been handled for all pages. That's why I made my commit on the bootstrap special branch, so that other people could contribute to the bootstrap 4 support.

**Comment by YasharF** [comment]
An initial upgrade of the nav bar in the bts4wip branch:
https://github.com/sahat/hackathon-starter/commit/341bf6954347db6d055eb4e669d483924d814f7d

Known issues (PRs are welcome for fixing these):
1. There is a 15px indentation in front of the nav-brand.  In the prior version the responsive code was adding a -15px margin in some resolutions which was compensating for this.
![image](https://user-images.githubusercontent.com/6448697/39382248-bceced0c-4a19-11e8-8fa1-ce7bb595196a.png)

2. navbar-header is deprecated.  There changes in the git commit causes the horizontal line to disappear when the nav items drop down with the navbar-toggler class.
![image](https://user-images.githubusercontent.com/6448697/39382344-013b5462-4a1a-11e8-9b33-c94ee6232892.png)

3. There are some wrapping issues in the nav bar with some scree widths.
![image](https://user-images.githubusercontent.com/6448697/39382508-94243604-4a1a-11e8-90d3-97bfa28bfbb8.png)

**Comment by YasharF** [comment]
Pull request for Bootstrap 4 upgrade: https://github.com/sahat/hackathon-starter/pull/847

Known issues:

- Modern and GSDK themes have not been updated.
- Visual QA hasn't been done with flatly theme
- The issues listed in https://github.com/sahat/hackathon-starter/issues/766#issuecomment-385077977

Most likely I would need some help to fix these remaining issues. If there are no comments in the next ten days or so, I'll merge this as is, and we'll fix the remaining issues in future minor releases.

**Comment by YasharF** [comment]
Upgrade branch merged.
Known issues are now being tracked in https://github.com/sahat/hackathon-starter/issues/853
