### ISSUE TITLE
npm install gives 404 error for node-sass download

### ISSUE THREAD

**Issue by budda** [sahat/hackathon-starter#767]
I ran $npm install

```
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-59_binding.node":

HTTP error 404 Not Found
```

Confirmed it doesn't exist on the releases list, but there is a -57 version https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-57_binding.node

I don't know what the significance of that final number in the URL has though.

**Comment by YasharF** [comment]
Looks like https://github.com/sass/node-sass/issues/2035
Per comments there that is due to files left over by previous npm versions.  Try cleaning the environment and rerunning npm install:
```
rm -rf node_modules
rm package-lock.json
npm cache clean
npm install
```

Also, if you haven't done so already, make sure you are on the latest LTS of the node branch which you are using.

**Comment by OzanKurt** [comment]
I finally found out that it's about being at node's Current Release instead of LTS.

**Comment by cp1001** [comment]
same 404 error! what's your node version? better check node-sass@v4.5.3 's supported node versions https://github.com/sass/node-sass/releases/tag/v4.5.3

**Comment by YasharF** [comment]
@OzanKurt , @cp1001 are you experiencing an issue when using Hackathon Starter?  You are commenting on an issue that was marked as resolved over a year old in this repo; Hackathon Starter is no longer using node-sass@v4.5.3.

**Comment by YasharF** [comment]
If you are experiencing the node-sass issue when using a package/repo of another project, that project seems to have some very out of date dependencies.  I would suggest reaching out to the maintainer of that project to see if you can help them with maintenance, PRs, etc. to bring its dependencies up to date, or if not feasible look for an alternative package/repo that is actively maintained.

If the issue that you are experiencing is with Hackathon Starter.  Feel free to open a new issue :)

**Comment by OzanKurt** [comment]
@YasharF It's not about an issue, my comment was telling how to fix that error.

It really doesn't matter where the answer is since Google is linking people to here when searching the given error. 😃

**Comment by YasharF** [comment]
Awesome! I love it!  Thank you :)
