### ISSUE TITLE
Last.fm API Example contains broken images + incorrect data references

### ISSUE THREAD

**Issue by JonLim** [sahat/hackathon-starter#770]
It looks like the Last.fm API Example page has broken images, due to a deprecation of interpolation syntax with Pug/Jade, and is also listing the incorrect data for albums and tracks of the artist.

![screen shot 2017-12-16 at 4 43 57 pm](https://user-images.githubusercontent.com/82186/34074600-938b3fc8-e280-11e7-845d-3996392c53a1.png)

I will submit a PR with the fix!

**Comment by YasharF** [comment]
PR merged, closing the issue.  Thank you 👍
