### ISSUE TITLE
Dockerfile image layers not optimised

### ISSUE THREAD

**Issue by praveenweb** [sahat/hackathon-starter#779]
The Dockerfile that is part of this boilerplate works but can be optimised. 

A docker image consists of many layers which usually are generated from Dockerfile, each line in Dockerfile will create a new layer. 
In the current one, `COPY . /starter` comes before `npm install` -> which means every time source code changes, npm install will be executed again. So i have re-ordered the lines so that npm install can be **cached** and doesn't run every time (unless ofcourse package.json changes).

The PR is at #778

**Comment by niallobrien** [comment]
I don't personally use Docker to verify this change, but I assume it's okay based on your description. Does anyone else use Docker and would be willing to verify the mentioned PR before merging? Thanks.

**Comment by YasharF** [comment]
PR merged.  Thank you.
