### ISSUE TITLE
Need the css-files instead of the SASS-files

### ISSUE THREAD

**Issue by ANorseDude** [sahat/hackathon-starter#781]
Hello, 

Not really any issue, but i need the CSS-files of "modern" instead of SASS-files. Tried using converters online but with no luck. Is it possible to get my hands on these somewhere?

Thanks in advance.

**Comment by YasharF** [comment]
What is the reason that you need the CSS files? Is it that you want to apply it to another project like a blog so you have consistency?  If so, there are two ways:

1. Download the compiled CSS by running an instance of the project with the theme and download the combined CSS at runtime from /css/main.css
2. Using SCSS for your other project
3. Writing the CSS for your other site somewhat from scratch by importing what applies in your case.  The amount of SASS isn't actually that much, in the ballpark of 150 lines of properties, some of which may not apply to you, and you can even manually write the CSS for your project if you don't need to.

The structure for the SCSS is:

- Main.scss combines its own ~50 lines or so with the theme variables, theme, bootstrap, and font-awesome: https://github.com/sahat/hackathon-starter/blob/master/public/css/main.scss
- The modern variable and theme each add ~50 lines or so https://github.com/sahat/hackathon-starter/tree/master/public/css/themes/modern

If you don't have a whole lot of experience with writing CSS and need to learn it, I would recommend the free self-learn course at https://dash.generalassemb.ly .

**Comment by ANorseDude** [comment]
Thanks for your reply, @YasharF !

The reason I want the CSS is that I'm not really - believe it or not - a fan off SCSS. I like to stick with simple CSS as im somewhat of a hobbydeveloper and nothing more than that. I tried to convert the file trought differens SCCS to CSS - compilers and some parts worked fine, others not. I guess I´ll just do it by hand. If nothing else, I´ll learn about the structure of a SCSS-file. 

Thank you for the explation of how the structure it, it will surely help me manage get the results I'm aiming for. 

I´ll close the issue now as it is not really and issue.
