### ISSUE TITLE
DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0

### ISSUE THREAD

**Issue by LeonardoGentile** [sahat/hackathon-starter#784]
Just installed and started with `nodemon app.js` and node complained:

``` 
(node:31949) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
```

So after a bit of reading I've found this [solution](https://github.com/Automattic/mongoose/issues/5399#issuecomment-322041860).

Basically, in app.js change this:
```
mongoose.connect(process.env.MONGODB_URI || process.env.MONGOLAB_URI);
```
into this:

```
mongoose.connect(process.env.MONGODB_URI || process.env.MONGOLAB_URI, { useMongoClient: true});
```

and the warning should disappear

**Comment by YasharF** [comment]
Duplicate of https://github.com/sahat/hackathon-starter/issues/739
