### ISSUE TITLE
Any up to date alternatives?

### ISSUE THREAD

**Issue by AdityaAnand1** [sahat/hackathon-starter#788]
In JavaScript time, this project hasn't been updated in ~4 years and in the meantime a lot of issues have popped up.

So I was wondering if there are any other such projects?

**Comment by YasharF** [comment]
4 years?  I don't think if that is what the commit log is stating.

**Comment by niallobrien** [comment]
There's regular updates, I don't know where you're getting four years from.

**Comment by AdityaAnand1** [comment]
woosh
