### ISSUE TITLE
returnTo - does not work as expected for urls with query params

### ISSUE THREAD

**Issue by shreedharshetty** [sahat/hackathon-starter#789]
`req.session.returnTo = req.path;` will actually ignores the query params
can we change it to `req.session.returnTo = req.url;`? 

Ref: https://github.com/sahat/hackathon-starter/blob/master/app.js#L109

**Comment by niallobrien** [comment]
Can you submit a PR?

**Comment by shreedharshetty** [comment]
Sure will do.
