### ISSUE TITLE
Any plans to add telegram as a login?

### ISSUE THREAD

**Issue by mintyPT** [sahat/hackathon-starter#798]
If so, when? If not, will a pull request be welcome?

**Comment by YasharF** [comment]
Currently, it is not in the immediate backlog.  If you are thinking about adding a PR, would you be able to do some API examples for functionality other than login similar to some of the examples at https://hackathon-starter-2018.herokuapp.com/api ?

**Comment by YasharF** [comment]
Just checking to see if you are planning to submit a PR.

**Comment by mintyPT** [comment]
Sorry for the delay. I add a bunch of days off.

Anyway, after looking deeper into this, I realised I couldn't do much with telegram. So, instead of logging users through their method, I use a bot. I won't be working on this after all.
