### ISSUE TITLE
bug api steam

### ISSUE THREAD

**Issue by nacimgoura** [sahat/hackathon-starter#810]
Hello,
When trying to use the api steam, I encounter this error.
```
Connect
500 TypeError: Cannot read property 'playerstats' of undefined
   at Promise.all.then (/Users/nacim/Documents/project/hackathon-starter/controllers/api.js:338:49)
   at <anonymous>
   at process._tickCallback (internal/process/next_tick.js:188:7)
```

The problem comes from this part of the code.
```
Promise.all([
    playerAchievements(),
    playerSummaries(),
    ownedGames()
  ])
    .then(([playerAchievements, playerSummaries, ownedGames]) => {
      res.render('api/steam', {
        title: 'Steam Web API',
        ownedGames: ownedGames.response.games,
        playerAchievemments: playerAchievements.playerstats,
        playerSummary: playerSummaries.response.players[0]
      });
    })
    .catch(next);
```

**Comment by YasharF** [comment]
Good catch.  It looks like that there is a missing error handling.  If the player doesn't have any recently played game or achievements, the object is undef but pug still makes an attempt to render it causing it to crash.

**Comment by YasharF** [comment]
https://github.com/sahat/hackathon-starter/pull/811

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/525e089a053bfcfd4d5cdfce8008609f4724820f
