### ISSUE TITLE
Review API and example set

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#823]
I would like to suggest reviewing the current list of the APIs that are supported, and if there are new ones that need to be added or some that need to be removed.  Factors I suggest to use are:

- What are the most popular websites with APIs? https://www.alexa.com/topsites
- What were the themes and needed APIs for some of the popular hackathons last year?
- What APIs have an actively maintained npm package by the service provider?

**Comment by YasharF** [comment]
Other potential source could be top github projects: https://github.com/trending/javascript

It looks like https://github.com/tensorflow/tfjs and https://github.com/tensorflow/tfjs-examples are pretty high on the list, perhaps some tensorflow examples would be a good candidate to consider.

**Comment by YasharF** [comment]
https://www.programmableweb.com/news/which-are-developers-favorite-apis/research/2017/09/01

**Comment by niallobrien** [comment]
Not a bad idea. Personally I've tended to avoid D3js due to its complexity and gone for much simpler charting solutions if looking to get something out the door as quickly as possible, such as Chart.js. However, this would add a significant amount of weight to the front-end JS file-size, so we need to consider the pros/cons of which libs to include.

**Comment by YasharF** [comment]
Not enough reuse to put it in this project, but just for fun posting this here:

_The Marvel Comics API allows developers everywhere to access information about Marvel's vast library of comics—from what's coming up, to 70 years ago._ 
 https://developer.marvel.com

**Comment by YasharF** [comment]
Some finance related API might be useful.  I did a hackathon a few weeks ago sponsored by CapitalOne with some banking APIs and BlackRock has some APIs as well.  The CapitalOne API might not be the best candidate though since at the time of the Hackathon they told us they are only available for banking in the US.

https://developer.capitalone.com/
http://rockthecode.io/api/

**Comment by YasharF** [comment]
Bitly's API can come handy:
https://dev.bitly.com

**Comment by YasharF** [comment]
Integration with a financial data reporting service.  That could potentially hit the mark for D3Js or another charting example.

I did a quick search and some candidates are:
https://blog.quandl.com/api-for-stock-data
https://iextrading.com/developer

Between the two quandl seems to be a better candidate.

**Comment by YasharF** [comment]
Examples with:
- PhaserJS:  https://phaser.io
- 3JS:  https://threejs.org

**Comment by YasharF** [comment]
Machine learning examples

**Comment by YasharF** [comment]
Creating a seperate issue for quickbooks: https://github.com/sahat/hackathon-starter/issues/886

**Comment by YasharF** [comment]
Created a separate issue for video call/conferencing: https://github.com/sahat/hackathon-starter/issues/891

**Comment by YasharF** [comment]
https://developer.visa.com/apibrowser/#segment=ISV

**Comment by YasharF** [comment]
FB Messenger's chat plugin: https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin

**Comment by YasharF** [comment]
An example using a rich text editor (i.e. ckeditor, ...):

**Comment by rishiCS** [comment]
@YasharF What exactly we're trying to do here?
Can you assign this to me?
