### ISSUE TITLE
Does the starter has SSR support?

### ISSUE THREAD

**Issue by mrtinkz** [sahat/hackathon-starter#838]
Wanted to know if the starter has the SSR support?

**Comment by niallobrien** [comment]
By "SSR support" I'm going to assume you mean server-side rendering. If so, then yes.
To elaborate, I'm assuming you're asking from a React perspective and this seems to have beginners confused. Prior to JavaScript frameworks for the client, most websites were rendered on the server and jQuery would have been used to sprinkle some clientside interaction on top. This was true regardless of the language or framework you were using. The introduction of single page applications that can be initially rendered and hydrated on the server prior to the single page application being loaded is a relatively new concept best demonstrated by Next.js and Nuxt.js for example. This starter project is not like them whatsoever and more resembles how sites/applications were traditionally built and how a lot of projects still are if you opt to use a framework for your backend eg. Rails, Laravel or Adonis. Of course you can use all of these frameworks (or this project) to build a REST API and build a SPA etc. but then you're going down a different route and is not what this project aims for out of the box.

**Comment by mrtinkz** [comment]
Thanks for the quick response, I'll take an Yes! will close this one now.
