### ISSUE TITLE
How to send post with CSRF token without adding a form or whitelisting/blacklisting.

### ISSUE THREAD

**Issue by djaffer** [sahat/hackathon-starter#840]
app.post('/hello', test.postHello);

exports.postHello = (req, res,next) => {
//res.local = req,local no success
res.send("hello");
};

I am testing through postman. I The documentation for lusca seems very obscure and useless. For the get method everything is working fine and I print the res it has the res.locals. If a user wants to do post without get then how to make it work. I certainly want to use the lusca.

**Comment by YasharF** [comment]
I am not sure if I understand your question or the usecase.  What is the use case that would require an HTTP POST without a prior HTTP GET?

For reference: "Cross-Site Request Forgery (CSRF) is an attack that forces an end user to execute unwanted actions on a web application in which they're currently authenticated."  https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

**Comment by djaffer** [comment]
Thanks Yashar there is a use case. There must be a way to use csrf in post. Even in a get response on postman I don't see the csrf as part of response sent. 
It is in the req.locals of the controller but not in the response.

**Comment by YasharF** [comment]
It doesn't look like if this is a specific issue with Hackathon Starter.  It seems like a question more fit for the Lusca project:  https://github.com/krakenjs/lusca/issues
