### ISSUE TITLE
How to pass data back to front end after authentication

### ISSUE THREAD

**Issue by harishankards** [sahat/hackathon-starter#841]
First of all, thanks for the great boilerplate.
Here, you have used pug as the rendering engine. In my project, I'm using Vue Js for frontend and vue-axios as the HTTP client.

Let's take one use case. `Linkedin oauth`.
I know how and when to call the '/auth/linkedin/' but when it is successful, how do I send the success/error message to the front end? I don't see any `req, res` in the `'auth/linkedin'` function.

Thanks in advance.

**Comment by YasharF** [comment]
If I understood your question correctly, when LinkedIn sends the user back to the callback path in hackathon-starter, it gets routed in this line: https://github.com/sahat/hackathon-starter/blob/master/app.js#L196
There you can have a different path than `/login`  or  `(req.session.returnTo || '/')` in case if the login was successful or not.

Does that answer your question?
