### ISSUE TITLE
NoSQL Injection

### ISSUE THREAD

**Issue by razchen** [sahat/hackathon-starter#851]
First of all allow me to say that this is a great boilerplate for NodeJS. Loving it!

I have been running some tests and without proper validation it's very easy to inject to mongoDB. There are a few packages that deal with this threat and I was wondering if you could add any solution to hackathon-starter.

Here is some info on the issue:
https://blog.websecurify.com/2014/08/hacking-nodejs-and-mongodb.html

**Comment by YasharF** [comment]
The project already addresses this.  See https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L86 where the email field (which a query is going to be ran on a few lines forther down) gets santized first.
