### ISSUE TITLE
Bootstrap 4 upgrade issues

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#853]
The following are known issues from the Bootstrap 4 upgrade, to be revisited:

- [x]  There is a 15px indentation in front of the nav-brand.  In the prior version, the responsive code was adding a -15px margin in some resolutions which was compensating for this.
![image](https://user-images.githubusercontent.com/6448697/39382248-bceced0c-4a19-11e8-8fa1-ce7bb595196a.png)

- [x]  navbar-header is deprecated.  The changes in the git commit causes the horizontal line to disappear when the nav items drop down with the navbar-toggler class.
![image](https://user-images.githubusercontent.com/6448697/39382344-013b5462-4a1a-11e8-9b33-c94ee6232892.png)

- [x]  There are some wrapping issues in the nav bar with some screen widths.
![image](https://user-images.githubusercontent.com/6448697/39382594-dd4657e0-4a1a-11e8-9721-09fe76753d23.png)

- [x] Fix navbar's theme issues (https://github.com/sahat/hackathon-starter/issues/853#issuecomment-475932533 and https://github.com/sahat/hackathon-starter/issues/853#issuecomment-475934766)
- [x] Modern theme upgrade or removal
- [x] GSDK upgrade or removal
- [x] Visual QA of flatly theme

**Comment by estevanmaito** [comment]
Hi!
I would like to help you address these issues, but I don't know from where to start building the project. Would you mind pointing me the direction, as this is my first issue?
Thank you

**Comment by estevanmaito** [comment]
@YasharF, thanks! I've already fixed points 1 and 3. 

Regarding point 2, what is the expected behavior? The collapsed bar is functioning as the examples from Bootstrap's site (take this as an example https://getbootstrap.com/docs/4.1/examples/album/), where the navbar expands and the bottom shadow follows.

And about the themes (points 4, 5 and 6), is there any discussion going on? I just changed the theme imports and there are some inconsistencies among them, like the navbar background being completely transparent and mixing with the text behind it. I don't know if I'm missing some import or what

```scss
/* imports that i've changed in order to change themes */
@import "themes/default/variables";
@import "themes/default/default";
```

**Comment by YasharF** [comment]
I think the best way to do this would be to have two instances of the project running concurrently on two different ports. One using the Bootstrap 3 libraries as prior to the upgrade merge, and one as the current version which is using the Bootstrap 4 libraries.  You can create a clone of the repo with the state before BS4 changes by:
```
git clone git@github.com:sahat/hackathon-starter.git hackstart_bs3
cd hackstart_bs3/
git reset --hard 6995d0a10cb94fcde88c41f8ce4d9815a00a5cb6
npm install
```
Then change the port to something other than 8080 at https://github.com/sahat/hackathon-starter/blob/master/app.js#L65 and https://github.com/sahat/hackathon-starter/blob/master/.env.example#L1 and run the pre-bootstrap 4 stack with `nodemon `, `npm start`, or `node app.js`.  Also note that you may have to do hard refresh on pages wiht every load to make sure that the browser is not loading the page from cache and potentially ending up with a hybrid bootstrap 3-4 render.  Hard refresh in Chrome can be done using Shift+F5.

On point 2, are you asking what the following picture is?
![image](https://user-images.githubusercontent.com/6448697/39382344-013b5462-4a1a-11e8-9b33-c94ee6232892.png)  
The old UI had a faint horizontal line appear when the nav items drop down was activated.  We can potentially just call what we have righ tnow good enough, and not try to do anything about it.  It would be visually nice if a line is added though.

On the GSDK upgrade or removal, that has been pending the update of the theme by @alexandru-paduraru , @conacelelena or someone else on their team.  So it is on hold at least until next year before removing the theme if it hasn't been updated.  The one-year anniversary of Bootstrap 4 upgrade will be on January 18.

On flatly or modern themes, the QA would be doing a side-by-side comparasion of how the views render using pre-bootstrap 4 upgrade and post-bootstrap 4 upgrade states.

**Comment by laurenquinn5924** [comment]
PR to remove GSDK: https://github.com/sahat/hackathon-starter/pull/938

**Comment by YasharF** [comment]
Just finished manual check of flatly theme and so far there is one issue that needs to be fixed:
When the nav bar has to render on top of the page (lower screen widths), it looks like that it renders under the page content with flatly:
![image](https://user-images.githubusercontent.com/6448697/54875852-6b8ee880-4dc3-11e9-9abc-9308f3e4523f.png)

---------------------------------------
The same section with the current default theme renders as:

![image](https://user-images.githubusercontent.com/6448697/54875856-7c3f5e80-4dc3-11e9-8718-3f8ae3ebb974.png)

**Comment by YasharF** [comment]
The nav bar rendering issue is also present when using the modern theme.

**Comment by YasharF** [comment]
I recehcked with Flatly 4.3.1 and the problem did not get resolved.
It looks like that in both cases, the navbar isn't picking up the theme's colors either.  For comparasion, the following is how the navbar looked with the flatly theme prior to the Bootstrap 4 upgrade:

![image](https://user-images.githubusercontent.com/6448697/54876277-4d78b680-4dca-11e9-8275-39a4374f293b.png)

**Comment by slidenerd** [comment]
Since we are on the topic of Bootstrap, what I am going to suggest is going to become controversial but since Hackathon Starter is all about being UNBIASED, it makes sense if you think about it

We have several front end frameworks

1. Bootstrap
2. Tailwind
3. Bulma
4. Materialize
and many more

**It is best if you stay unbiased and remove support for Jquery, Popper and Bootstrap**
Have the login signup contact, home pages made in full custom CSS with flexbox or grid and remove dependence on libraries

**Comment by niallobrien** [comment]
Who said it is unbiased?! It's clearly biased towards being the best and
easiest project to use in the context of a Hackathon - the clue is in the
name...
What's the point of removing Bootstrap and using 100% custom CSS and JS?
That would only slow you down at a Hackathon and is completely
counter-productive.

**Comment by YasharF** [comment]
I'm resolving this since now all of the issues in the original post seem to be addressed.  Thank you all!
