### ISSUE TITLE
Create a glitch.com version of this repo, which can be remixed instantly

### ISSUE THREAD

**Issue by jschiarizzi** [sahat/hackathon-starter#857]
Glitch.com is a service created by FogCreek that lets anyone fork and deploy node servers instantly.  This project would be even more accessible and easier to get started with if there was a version of it on glitch.

**Comment by YasharF** [comment]
It looks like that someone else has already done a clone of hackathon-starter there: https://glitch.com/~hackathon-starter 
It is an out of date version.  I'm  not sure if I currently have bandwidth to try to get the ownership of that clone transferred and to constantly keep it up to date.  Perhaps if glitch would come with some type of continuous deployment so it would always automatically pick up the latest version of this git repo.

**Comment by YasharF** [comment]
It would be ideal if whoever that has done the initial clone to glitch, can continuously maintain it by replicating this github repo.  Would you be able to reach out to them?

**Comment by jschiarizzi** [comment]
Oh cool, I didn't see that before. Looks like it was made by https://twitter.com/jennschiffer who is an employee of Fog Creek

**Comment by YasharF** [comment]
It looks like they had to do some minor customization to get it work on their stack, so they would probably be the best folks to help keep it up to date.
