### ISSUE TITLE
Failed to push! Failed to compile python

### ISSUE THREAD

**Issue by Pingusate** [sahat/hackathon-starter#859]
I wanted to setup a discord selfbot for myself. I deploy it with "rewrite" branch, It always gives me this message

`       Collecting git+https://github.com/fourjr/discord.py@rewrite (from -r /tmp/build_4bc9adf499992b2285952772483cd560/requirements.txt (line 1))
         Cloning https://github.com/fourjr/discord.py (to rewrite) to /tmp/pip-_vdj4jjk-build
       fatal: could not read Username for 'https://github.com': No such device or address
       Command "git clone -q https://github.com/fourjr/discord.py /tmp/pip-_vdj4jjk-build" failed with error code 128 in None
 !     Push rejected, failed to compile Python app.
 !     Push failed`

Kindly send me a solution to solve please :) thanks

**Comment by YasharF** [comment]
Is this an issue with Hackathon-starter? Can you provide the git command that you used?
