### ISSUE TITLE
Twitter API Out Of Date

### ISSUE THREAD

**Issue by garretthogan** [sahat/hackathon-starter#862]
I pulled down the repo and got the app running and had to make some changes to the `search/tweets` endpoint before it worked. Seems like that the current API expects `statuses` to live at `data.statuses`, data being the object returned by

```
await T.get('search/tweets', {
      q: 'nodejs since:2013-01-01',
      geocode: '40.71448,-74.00598,5mi',
      count: 10
    });
```

but after doing some logging I finally found that statuses is nested one more layer deep. I had to update the code to `const { data: { statuses: tweets } }` instead of just `const { statues: tweets }` in order for the last 10 tweets view to render. I can open a PR with the change if you are cool with that. Just raising awareness because it's possible that other APIs and endpoints are out of date as well.

**Comment by YasharF** [comment]
It would be great if you can submit a PR!  Make sure to test your changes before submitting the PR thou :)

Thanks

**Comment by YasharF** [comment]
https://github.com/sahat/hackathon-starter/pull/863
