### ISSUE TITLE
Twilio API Keys Expired And API Out Of Date

### ISSUE THREAD

**Issue by garretthogan** [sahat/hackathon-starter#864]
In order to get the Twilio API example to work I had to change
```
  twilio.sendMessage(message, (err, responseData) => {
    if (err) { return next(err.message); }
    req.flash('success', { msg: `Text sent to ${responseData.to}.` });
    res.redirect('/api/twilio');
  });
```
to
```
  twilio.messages.create(message).then((sentMessage) => {
    req.flash('success', { msg: `Text send to ${sentMessage.to}` });
    res.redirect('/api/twilio');
  }).catch(next);
```
I also kept getting 401s with the Twilio account creds provided in the env file. I had to change the creds to my own for the text to successfully send. I will open a PR to update the API but you will need to update the credentials for the app yourself because I do not want to supply my personal Twilio trial keys.

**Comment by YasharF** [comment]
https://github.com/sahat/hackathon-starter/pull/865

**Comment by YasharF** [comment]
Thanks, the credentials in the env example file in this repo are somewhat dummpy/placeholder credentials.  It is expected that the developers would get their own credentials as stated in the readme:


- Go to https://www.twilio.com/try-twilio
- Sign up for an account.
- Once logged into the dashboard, expand the link 'show api credentials'
- Copy your Account Sid and Auth Token 


Thanks for the PR.  Will merge it shortly.
