### ISSUE TITLE
Linkedin strategy pushes data to User model instead of other defined model

### ISSUE THREAD

**Issue by harishankards** [sahat/hackathon-starter#867]
Hi,
Below is the code come up with the package but I modified the model from `User` to `Student` as per my database schema. But whenever I do OAuth, it's storing the data under `users` instead of `students`. What could be the reason?
```js
passport.use('student-linkedin', new LinkedInStrategy({
  clientID: process.env.LINKEDIN_ID,
  clientSecret: process.env.LINKEDIN_SECRET,
  callbackURL: process.env.LINKEDIN_CALLBACK_URL_STUDENT,
  scope: ['r_basicprofile', 'r_emailaddress'],
  passReqToCallback: true
}, (req, accessToken, refreshToken, profile, done) => {
  if (req.user) {
    Student.findOne({ linkedin: profile.id }, (err, existingUser) => {
      if (err) { return done(err); }
      if (existingUser) {
        req.flash('errors', { msg: 'There is already a LinkedIn account that belongs to you. Sign in with that account or delete it, then link it with your current account.' });
        done(err);
      } else {
        Student.findById(req.user.id, (err, user) => {
          if (err) { return done(err); }
          user.linkedin = profile.id;
          user.tokens.push({ kind: 'linkedin', accessToken });
          user.profile.name = user.profile.name || profile.displayName;
          user.profile.location = user.profile.location || profile._json.location.name;
          user.profile.picture = user.profile.picture || profile._json.pictureUrl;
          user.profile.website = user.profile.website || profile._json.publicProfileUrl;
          user.save((err) => {
            if (err) { 
              return done(err); 
            }
            req.flash('info', { msg: 'LinkedIn account has been linked.' });
            done(err, user);
          });
        });
      }
    });
  } else {
    Student.findOne({ linkedin: profile.id }, (err, existingUser) => {
      if (err) { return done(err); }
      if (existingUser) {
        return done(null, existingUser);
      }
      Student.findOne({ email: profile._json.emailAddress }, (err, existingEmailUser) => {
        if (err) { return done(err); }
        if (existingEmailUser) {
          req.flash('errors', { msg: 'There is already an account using this email address. Sign in to that account and link it with LinkedIn manually from Account Settings.' });
          done(err);
        } else {
          const user = new User();
          user.linkedin = profile.id;
          user.tokens.push({ kind: 'linkedin', accessToken });
          user.email = profile._json.emailAddress;
          user.profile.name = profile.displayName;
          user.profile.location = profile._json.location.name;
          user.profile.picture = profile._json.pictureUrl;
          user.profile.website = profile._json.publicProfileUrl;
          user.save((err) => {
            done(err, user);
          });
        }
      });
    });
  }
}));
```

**Comment by YasharF** [comment]
Did you specify a different collection name for your model like: http://mongoosejs.com/docs/guide.html#collection

**Comment by harishankards** [comment]
Hi @YasharF,
Below is my `Student` model 

```js
const studentSchema = new Schema({
  email: { type: String, unique: true },
  password: String,
  passwordResetToken: String,
  passwordResetExpires: Date,
  username: String,
  tags: Array,

  linkedin: String,
  tokens: Array

}, { timestamps: true });

const Student = mongoose.model('Student', studentSchema);

module.exports = Student;
```

**Comment by YasharF** [comment]
Are you mapping User to the Student model?  like by replacing https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L5 with `const User = require('../models/Student');`

**Comment by harishankards** [comment]
No @YasharF, I have another model. So I'm not using `User` model. I'm using `Student` model and `Teacher` model separately with its own functions.

**Comment by YasharF** [comment]
The project is currently a single user model design.  If you want to have multiple user models then you will need to modify it.  For a single usermodel, if you want to replace the existing model instead of modifying it, you would need to replace the schima, its binding, and related code.

**Comment by harishankards** [comment]
Oh! I understood @YasharF. What are all the things I need to modify if I'm using it for multiple users?

**Comment by YasharF** [comment]
I currently don't have the bandwidth to go through all of those details.  I would suggest doing just one model to being with and once you are comfortable decide on if you want to do a 2nd one or now.  In a personal implementation that I have, I actually deployed two seperate stacks each with a single user model, but for a different role (i.e. admins.mysite.com and portal.mysite.com)

**Comment by harishankards** [comment]
Understand @YasharF. But can you tell me where you have added code for creating a document to User after Linkedin Oauth success?

**Comment by harishankards** [comment]
Ok @YasharF . 
Here: https://github.com/sahat/hackathon-starter/blob/master/config/passport.js#L300

I see that `req.user` is returning the user which is stored already. I'm trying to found out on which line it's storing to the DB.

**Comment by harishankards** [comment]
Hey @YasharF,
Just wanted to check whether I have any update on this.

**Comment by YasharF** [comment]
I am not sure what the question for me is.  The code for setting up a user follow up with a LinkedIn Oauth is starts at https://github.com/sahat/hackathon-starter/blob/master/config/passport.js#L299 which I mentioned a few days ago.  Besides pointing you there, I don't have the bandwidth to help modify forks of this project for application specific workflows at the moment.  I have already marked this issue as closed.  I suggest using other resources such as stackexchange, passportjs or mongo documents for further help on troubleshooting your specific issue.
