### ISSUE TITLE
Edit CSS files makes no effect

### ISSUE THREAD

**Issue by Archeane** [sahat/hackathon-starter#871]
When I add a new file in the static folder (/public/css), the new file is not served on my server. For instance, I added a file test.css in /public/css, but it doesn't show up on the static file directory when I inspect element on my localhost page.

I even deleted the whole 'public' folder from the project directory and changed the static references in app.js. The page still contains the static files when I look up 'sources' in 'inspect element'. 
My guesses is that the server has some access to the original files in 'public' folder and is not telling the webpage to load from the static folder in my computer. 

Thanks for any advice.

**Comment by YasharF** [comment]
When trying to access the content of `/public` from the web interface, you need to omit `/public` from the address.  For example if you create a `test.css` in `/public/css` , it will be accessible on localhost:8080 as `localhost:8080/css/test.css`
