### ISSUE TITLE
Home link in title bar is always active

### ISSUE THREAD

**Issue by dkimot** [sahat/hackathon-starter#872]
As the title says, the Home link in the title bar is always active. If you delete the default active class from the `header.pug` file it solves this.

I'm happy to submit a PR, unless this is on purpose.

**Comment by YasharF** [comment]
Is this what you are referring to?  If so, yes it looks like a bug that probably got introduced with the recent bootstrap 4 upgrade.  A PR would be awesome.  Thanks

![image](https://user-images.githubusercontent.com/6448697/41820825-8eecc9b8-778c-11e8-9df3-d5bb7da8b9f0.png)

**Comment by dkimot** [comment]
Created a pull request.
