### ISSUE TITLE
Suggestion: A barebones version without all the API/Auth examples

### ISSUE THREAD

**Issue by marcospgp** [sahat/hackathon-starter#876]
Whenever I start a project with this boilerplate (which happens with most of them, since hackathon-starter has easily 10x more stars than most other boilerplates), I find myself removing all the API and authentication examples as a first step.

I would consider maintaining a fork of this repo for myself, but it would not be worth the work if it were just for myself.

I was wondering if anyone else is interested in a minimal version which comes ready to roll, without any unnecessary packages.

That quote about perfection comes to mind: "Perfection is Achieved Not When There Is Nothing More to Add, But When There Is Nothing Left to Take Away" 😄

**Comment by YasharF** [comment]
Let's park this here for a week or two, but perhaps there might be a better place such as gitter for this data gathering.

**Comment by waqasnoor** [comment]
I would love such version minimal version.

**Comment by niallobrien** [comment]
Wouldn't a minimal version pretty much be the default Express boilerplate?

**Comment by monkeywithacupcake** [comment]
I've done the same thing a few times - maybe it is worth saving a minimal version...that is not quite the same as a default express

**Comment by marcospgp** [comment]
I would say simply removing all the API examples and most of the third party authentication options.

I would also like to remind you that the validation style being used for the endpoint parameters has been deprecated!

**Comment by YasharF** [comment]
We need a more precise definition of what _most of the third party authentication options_ is, and why would the particular subset be the right subset.


For the following, can you create a separate issue, and point to the related deprecation document?
> I would also like to remind you that the validation style being used for the endpoint parameters has been deprecated!

**Comment by monkeywithacupcake** [comment]
I think a minimal version would be Mongo Express Node with local Passport like @YasharF  says but also with the mail still setup through contact form.

**Comment by YasharF** [comment]
I had to do this last night so here is the list of what typically get ripped out:

- Unused keys from .env file
- /controllers/api.js entirly
- app.js:
  - chalk usage
  - express-status-monitor
  - multer
  - apiController
  - Opensift env refrences
  - csrf check exception for /api/upload
  - All API example routes
  - OAuth routes for instagram, github, linkedin (kept Facebook, Twitter, and Google)
  - All OAuth authorization routes
- passport.js all references and functions related to:
  - request ( `require('request')` )
  - Instagram, Github, LinkedIn, OpenID, OAuth, OAuth2
- model/User.js
  - key pairs for github, instagram, linkedin, steam
- package.json
  - @octokit/rest, chalk, clockwork, express-status-monitor, instagram-node, lastfm, lob, multer, node-foursquare, node-linkedin, passport-github, passport-instagram, passport-linkedin-oauth2, passport-oauth, passport-openid, paypal-rest-sdk, stripe, tumbler.js, twilio
- /test/app.js
    - /api test case
- the entire /views/api
- views/account/login.pug
    - The last form-group set which is all of the social login choices
- views/account/profile.pug
    - Link/unlink buttons for instagram, github, linkedin, steam

**Comment by niallobrien** [comment]
I agree that if you're not doing a Hackathon, then you might want to rip
all of these things out. However, if you are doing a Hackathon, having all
of these APIs setup out of the box is a huge advantage in terms of moving
quickly.

**Comment by monkeywithacupcake** [comment]
Maybe it is a separate repo that comes off as "project-starter" and then is maintained separately?

**Comment by YasharF** [comment]
> then is maintained separately

The challenge is finding the dev resource for maintaining the project if it is maintained separately.  Just keeping hackathon-starter in a maintained state by itself requires contribution from many folks in the community, and it is usually challenging to make sure everything is up to date and bug free (there are currently a few long standing bug related issues in the queue here).  Instead of a project with a separate maintenance resourcing, I would rather see an automated process (like an automated triggered git rebase) that would handle the maintenance by pushing the changes from this repo to the repo for the stripped down variation.

**Comment by JurnW** [comment]
Maybe it's easier to write a guide on how to strip out all these things with all the filenames and code samples. 

This requires no changes to the code base which allows us to maintain just one version of the project, but still allows users to get to a more minimalistic version quickly. Even if they are less familiar with the code base.

**Comment by Rob-Rychs** [comment]
hmmm why not just do a git checkout minimal branch? keep it in the same repo, different branch and update the docs on how to switch to minimal branch

**Comment by YasharF** [comment]
> hmmm why not just do a git checkout minimal branch? keep it in the same repo, different branch and update the docs on how to switch to minimal branch

Because the minimal branch will need to be maintained as well.

**Comment by YasharF** [comment]
> Maybe it's easier to write a guide on how to strip out all these things with all the filenames and code samples.

If there was a way to pin a comment, I would say https://github.com/sahat/hackathon-starter/issues/876#issuecomment-414158548 is the condensed guide for stripping the extras to come up with a minimal code base.

**Comment by niallobrien** [comment]
I'll just say that I tried maintaining a fork of this project with a lot of additional features (JS & Sass asset pipeline, websockets, etc.) and it was a major pain to keep updated.

**Comment by brennhill** [comment]
I am planning a fork to be a "lean starter".  It will be SPA + Serverless using React.

**Comment by Sharlaan** [comment]
for auto-updating dependencies, maybe you can setup renovate bot ?
This would require strict e2e tests so updates don't break the boilerplate (preserve functionalities) XD

Regarding the full/minimal versions debate, how about setting up a CLI generator like Vue/Angular-CLI ?

Personnally i would love to see a Typescript version of this repo ;)

**Comment by Sharlaan** [comment]
@repo-owner: Would be nicer to leave a comment on why deleting my suggestions for this topic ...

**Comment by YasharF** [comment]
@Sharlaan your initial comment was removed partly due to an error from my end.   Sorry about that.

As far as this issue goes, there is no immediate plan and bandwidth to create and maintain a separate version.  I'm going to close this issue.
