### ISSUE TITLE
Code coverage improvements

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#882]
Can we improve the testing by increasing the code coverage?  The current status is:
```
-------------------------------|----------|----------|----------|----------|-------------------|
File                           |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------------------------|----------|----------|----------|----------|-------------------|
All files                      |    23.43 |     1.66 |     0.49 |     25.3 |                   |
 hackathon-starter             |    83.89 |    18.18 |     6.67 |    83.89 |                   |
  app.js                       |    83.89 |    18.18 |     6.67 |    83.89 |... 13,217,221,229 |
 hackathon-starter/config      |     8.48 |        0 |        0 |      9.4 |                   |
  passport.js                  |     8.48 |        0 |        0 |      9.4 |... 48,549,550,552 |
 hackathon-starter/controllers |    14.49 |        0 |        0 |    15.73 |                   |
  api.js                       |    17.44 |        0 |        0 |    18.91 |... 32,634,635,640 |
  contact.js                   |    15.38 |        0 |        0 |    15.38 |... 60,61,62,64,65 |
  home.js                      |       50 |      100 |        0 |       50 |                 6 |
  user.js                      |    10.15 |        0 |        0 |    11.17 |... 70,372,376,379 |
 hackathon-starter/models      |    32.14 |        0 |        0 |       36 |                   |
  User.js                      |    32.14 |        0 |        0 |       36 |... 59,61,62,64,65 |
-------------------------------|----------|----------|----------|----------|-------------------|
```

**Comment by sahat** [comment]
I will add some unit tests, hopefully sometime this weekend, depending on my photo shoot plans, if not then next week. Although it’s kind of pointless to have a high code coverage since this is a boilerplate and not a production app, it could serve as a guide for writing tests, so it’s worth adding them. 

To be honest, I haven’t done much Node.js testing since starting this project, but I did write thousands of test cases of various complexity using React/Redux/Redux-Saga/Jest/Enzyme apps for the past several years. I may end up refactoring some code though to make it more testable.

**Comment by YasharF** [comment]
One set of tests that I think as far as maintenance could really come handy would be for the API pages, which there are quite a few of them.  Right now I have been mostly manually testing changes, and if it could be automated it would be great.  Also, can we have Github to run the tests on pull requests when they are submitted?  I recall a couple of cases that PRs seem to be OK but they ended up breaking the boilerplate right out of the box.  Having the automated tests on pull requests can provide quick and cheap feedback to submitters to fix the issues.

**Comment by YasharF** [comment]
Probably what we need more of for the unit tests: https://mherman.org/blog/stubbing-http-requests-with-sinon.  My two cents would be to start from one of the OAuth or simpler API examples to try this.  Any kind of prerecorded http response is probably going to be sufficient.

**Comment by Sarvesh18** [comment]
Can I help u in increasing code coverage ?

**Comment by YasharF** [comment]
@Sarvesh18 sure  PRs are welcome

**Comment by zeeshanshamsuddeen** [comment]
Hey @YasharF , is this issue tagged for hacktoberfest 2021? And can I help in increasing the code coverage?
