### ISSUE TITLE
nor reading port from .env

### ISSUE THREAD

**Issue by reachdevelopers** [sahat/hackathon-starter#884]
I rename the .env.example to just .env added PORT:3000 in it, but the app always tries to open port 8080

**Comment by YasharF** [comment]
I can't replicate the issue.  Try to see if you can change the port from the shell.  The following is what I got in bash:

```
$ export PORT=3000
$ npm start

> hackathon-starter@5.1.1 start /mnt/c/temp/hackathon-starter
> node app.js

✓ App is running at http://localhost:3000 in development mode
  Press CTRL-C to stop
```

The port for the app is set at https://github.com/sahat/hackathon-starter/blob/master/app.js#L62

**Comment by reachdevelopers** [comment]
just downloaded again on my computer at home and still goes to port 8080.
<img width="701" alt="screen shot 2018-07-27 at 7 37 25 pm" src="https://user-images.githubusercontent.com/8906338/43352185-bc01f89e-91d4-11e8-80ba-c3d252767138.png">

I have this on the .env
<img width="385" alt="screen shot 2018-07-27 at 7 39 40 pm" src="https://user-images.githubusercontent.com/8906338/43352200-ec4d409e-91d4-11e8-99e6-1c8cfc7bab39.png">

**Comment by YasharF** [comment]
Use `PORT=3000` instead of `PORT:3000`

**Comment by reachdevelopers** [comment]
ay ay ay oops ok thanks
