### ISSUE TITLE
Installation fails on both Ubuntu 14.04 and 16.04

### ISSUE THREAD

**Issue by tanaydin** [sahat/hackathon-starter#885]
Hello, I've tried to install the project on both ubuntu 14.04 and 16.04. I got the following error.

	vagrant@vagrant-ubuntu-trusty-64:/vagrant/app$ npm install
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wordwrap@0.0.2 (node_modules/nyc/node_modules/cliui/node_modules/wordwrap):
	npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/vagrant/app/node_modules/nyc/node_modules/cliui/node_modules/wordwrap/package.json.42482033'

	npm ERR! path /vagrant/app/node_modules/nyc/node_modules/locate-path/node_modules/path-exists/package.json.371881922
	npm ERR! code ENOENT
	npm ERR! errno -2
	npm ERR! syscall open
	npm ERR! enoent ENOENT: no such file or directory, open '/vagrant/app/node_modules/nyc/node_modules/locate-path/node_modules/path-exists/package.json.371881922'
	npm ERR! enoent This is related to npm not being able to find a file.
	npm ERR! enoent 

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/vagrant/.npm/_logs/2018-07-29T09_42_18_918Z-debug.log

**Comment by YasharF** [comment]
What version of node and npm do you have installed when executing the following commands?

```
node -v
npm -v
```

**Comment by tanaydin** [comment]
Here is my Vagrant shell commands

        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse"
        tee /etc/apt/sources.list.d/mongodb-org-4.0.list
        curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        apt-get install -y mongodb-org build-essential nodejs
        curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        apt-get update
        apt-get install -y yarn

**Comment by tanaydin** [comment]
Here is for npm5.

	vagrant@ubuntu-xenial:~$ node -v
	v8.11.3
	vagrant@ubuntu-xenial:~$ npm -v
	5.6.0
	vagrant@ubuntu-xenial:~$ cd /vagrant/app_
	-bash: cd: /vagrant/app_: No such file or directory
	vagrant@ubuntu-xenial:~$ cd /vagrant/
	vagrant@ubuntu-xenial:/vagrant$ git clone https://github.com/sahat/hackathon-starter.git myproject
	Cloning into 'myproject'...
	remote: Counting objects: 10664, done.
	remote: Total 10664 (delta 0), reused 0 (delta 0), pack-reused 10664
	Receiving objects: 100% (10664/10664), 10.97 MiB | 2.06 MiB/s, done.
	Resolving deltas: 100% (6117/6117), done.
	Checking connectivity... done.
	vagrant@ubuntu-xenial:/vagrant$ cd myproject/
	vagrant@ubuntu-xenial:/vagrant/myproject$ npm install
	npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yargs@3.10.0 (node_modules/nyc/node_modules/uglify-js/node_modules/yargs):
	npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/vagrant/myproject/node_modules/nyc/node_modules/uglify-js/node_modules/yargs/package.json.2814539763'

	npm ERR! path /vagrant/myproject/node_modules/nyc/node_modules/yargs/node_modules/yargs-parser/package.json.1350342557
	npm ERR! code ENOENT
	npm ERR! errno -2
	npm ERR! syscall open
	npm ERR! enoent ENOENT: no such file or directory, open '/vagrant/myproject/node_modules/nyc/node_modules/yargs/node_modules/yargs-parser/package.json.1350342557'
	npm ERR! enoent This is related to npm not being able to find a file.
	npm ERR! enoent 

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/vagrant/.npm/_logs/2018-08-01T12_26_19_277Z-debug.log
	vagrant@ubuntu-xenial:/vagrant/myproject$ node app.js 
	fs.js:904
	  return binding.readdir(pathModule._makeLong(path), options.encoding);
	                 ^

	Error: ENOENT: no such file or directory, scandir '/vagrant/myproject/node_modules/node-sass/vendor'
	    at Object.fs.readdirSync (fs.js:904:18)
	    at Object.getInstalledBinaries (/vagrant/myproject/node_modules/node-sass/lib/extensions.js:129:13)
	    at foundBinariesList (/vagrant/myproject/node_modules/node-sass/lib/errors.js:20:15)
	    at foundBinaries (/vagrant/myproject/node_modules/node-sass/lib/errors.js:15:5)
	    at Object.module.exports.missingBinary (/vagrant/myproject/node_modules/node-sass/lib/errors.js:45:5)
	    at module.exports (/vagrant/myproject/node_modules/node-sass/lib/binding.js:15:30)
	    at Object.<anonymous> (/vagrant/myproject/node_modules/node-sass/lib/index.js:14:35)
	    at Module._compile (module.js:652:30)
	    at Object.Module._extensions..js (module.js:663:10)
	    at Module.load (module.js:565:32)
	    at tryModuleLoad (module.js:505:12)
	    at Function.Module._load (module.js:497:3)
	    at Module.require (module.js:596:17)
	    at require (internal/module.js:11:18)
	    at Object.<anonymous> (/vagrant/myproject/node_modules/node-sass-middleware/middleware.js:3:12)
	    at Module._compile (module.js:652:30)
	vagrant@ubuntu-xenial:/vagrant/myproject$

**Comment by tanaydin** [comment]
And another one with npm update, version 6

	vagrant@ubuntu-xenial:/vagrant/myproject$ sudo npm i npm@latest -g
	/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
	/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
	+ npm@6.2.0
	added 282 packages, removed 363 packages and updated 41 packages in 9.884s
	vagrant@ubuntu-xenial:/vagrant/myproject$ npm -v
	6.2.0
	vagrant@ubuntu-xenial:/vagrant/myproject$ npm install
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yargs@3.10.0 (node_modules/nyc/node_modules/uglify-js/node_modules/yargs):
	npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/vagrant/myproject/node_modules/nyc/node_modules/uglify-js/node_modules/yargs/package.json.2030096674'

	npm ERR! path /vagrant/myproject/node_modules/nyc/node_modules/yargs/node_modules/camelcase/package.json.1055702760
	npm ERR! code ENOENT
	npm ERR! errno -2
	npm ERR! syscall open
	npm ERR! enoent ENOENT: no such file or directory, open '/vagrant/myproject/node_modules/nyc/node_modules/yargs/node_modules/camelcase/package.json.1055702760'
	npm ERR! enoent This is related to npm not being able to find a file.
	npm ERR! enoent 

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/vagrant/.npm/_logs/2018-08-01T12_30_47_678Z-debug.log
	vagrant@ubuntu-xenial:/vagrant/myproject$ node app.js 
	fs.js:904
	  return binding.readdir(pathModule._makeLong(path), options.encoding);
	                 ^

	Error: ENOENT: no such file or directory, scandir '/vagrant/myproject/node_modules/node-sass/vendor'
	    at Object.fs.readdirSync (fs.js:904:18)
	    at Object.getInstalledBinaries (/vagrant/myproject/node_modules/node-sass/lib/extensions.js:129:13)
	    at foundBinariesList (/vagrant/myproject/node_modules/node-sass/lib/errors.js:20:15)
	    at foundBinaries (/vagrant/myproject/node_modules/node-sass/lib/errors.js:15:5)
	    at Object.module.exports.missingBinary (/vagrant/myproject/node_modules/node-sass/lib/errors.js:45:5)
	    at module.exports (/vagrant/myproject/node_modules/node-sass/lib/binding.js:15:30)
	    at Object.<anonymous> (/vagrant/myproject/node_modules/node-sass/lib/index.js:14:35)
	    at Module._compile (module.js:652:30)
	    at Object.Module._extensions..js (module.js:663:10)
	    at Module.load (module.js:565:32)
	    at tryModuleLoad (module.js:505:12)
	    at Function.Module._load (module.js:497:3)
	    at Module.require (module.js:596:17)
	    at require (internal/module.js:11:18)
	    at Object.<anonymous> (/vagrant/myproject/node_modules/node-sass-middleware/middleware.js:3:12)
	    at Module._compile (module.js:652:30)

**Comment by tanaydin** [comment]
I've installed node-sass to check... now I got...

	vagrant@ubuntu-xenial:/vagrant/myproject$ yarn
	yarn install v1.9.2
	info No lockfile found.
	warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
	[1/5] Validating package.json...
	[2/5] Resolving packages...
	[3/5] Fetching packages...
	[4/5] Linking dependencies...
	[5/5] Building fresh packages...
	success Saved lockfile.
	$ npm rebuild node-sass

	> node-sass@4.9.2 install /vagrant/myproject/node_modules/node-sass
	> node scripts/install.js

	node-sass build Binary found at /vagrant/myproject/node_modules/node-sass/vendor/linux-x64-57/binding.node

	> node-sass@4.9.2 postinstall /vagrant/myproject/node_modules/node-sass
	> node scripts/build.js

	Binary found at /vagrant/myproject/node_modules/node-sass/vendor/linux-x64-57/binding.node
	Testing binary
	Binary is fine
	node-sass@4.9.2 /vagrant/myproject/node_modules/node-sass
	Done in 117.18s.
	vagrant@ubuntu-xenial:/vagrant/myproject$ node app.js 
	✓ App is running at http://localhost:8080 in development mode
	  Press CTRL-C to stop

	GET / 200 1513.784 ms - -
	GET /js/main.js 200 27.049 ms - 67
	[sass]  error: File to import not found or unreadable: node_modules/@fortawesome/fontawesome-free/scss/fa-brands.

	in /vagrant/myproject/public/css/main.scss:6:1 
	Error: File to import not found or unreadable: node_modules/@fortawesome/fontawesome-free/scss/fa-brands.
	    at options.error (/vagrant/myproject/node_modules/node-sass/lib/index.js:291:26)
	GET /favicon.png 200 8.586 ms - 1594

**Comment by YasharF** [comment]
I see different issues in the different posts here.
- yarn isn't officially supported (removed with https://github.com/sahat/hackathon-starter/commit/2ef645f76526d48f8ca33b37f4aae4376e5d3eff )
- Before installing any packages with `apt-get` you should run BOTH `apt-get update` and `apt-get upgrade`. Note that they may require to be executed with `sudo` , aka `sudo apt-get upgrade`.
- This seems to be an issue with vagrant and not ubuntu.  vagrant tends to have issues with npm in general (not related to hackathon starter).  See https://github.com/Hashnode/mern-cli/issues/16 .  You may want to also see https://github.com/npm/npm/issues/17444
- node-sass is failing because `npm install` prior to its execution had failed and there are missing npm packages.

Is this an installation on Windows 10?  If so, I would recommend WSL over virts in most cases.  Also, if you are using a dev env such as WSL, you can move some services such as mongodb outside of the linux env and to their native windows version to simplify your virt/dev env and improve performance.

**Comment by tanaydin** [comment]
Hi again,

I'm using Mac as host and Ubuntu on vagrant as guest os, no windows at all. I'm using sync folders feature of vagrant. I'll try without it and update the issue.

**Comment by tanaydin** [comment]
I've installed it on a clean Ubuntu 16.04 with installation steps to a folder which wasn't watching by vagrant. And it worked, seems vagrant and node has some inconstancy...

**Comment by niallobrien** [comment]
And I can confirm that this installs fine on Windows also. 🙂
