### ISSUE TITLE
Google Drive & Google Doc Examples

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#887]
Need an API integration example for Google Drive & Google Doc.  These could be split into two seperate API examples.

In case of Google Drive, it is desired to be able to read or write a file to the drive.
In case of a Google Docs, it would be desired to be able to access content such as a spreadsheet data in a google spreadsheet.

**Comment by YasharF** [comment]
Typically it is OK to use npm packages given that they are actively maintained, used, and are free of security vulnerabilities.

- We are using another package that is maintained by niftylettuce, so I suspect he maintains this one as well.  It looks like there are some broken links in the Readme.md, so I would suggest starting with sending that project a PR to fix what seems to be broken first before adding it here or to any other project of yours.
- https://www.npmjs.com/package/google-drive is showing only about 550 downloads per week.  It is not very popular, but if this is the only package that gets the job done, then so be it.  That brings up the question though: what are other people using?  Is it just as easy to directly call the APIs, hence others bypassing the package, or is there a different reason?
- https://snyk.io/test/github/niftylettuce/node-google-drive is stating 0 volunerabilities.

**Comment by YasharF** [comment]
The other question to ask about integrating this particular package would be, Hackathon Starter already does OAuth authentication with Google.  Will that package be redundant in that sense, or is it only adding capabilities that are not there already.

**Comment by tanaydin** [comment]
Basically it works as expected, with some lines of code like this

```
exports.getGoogleDrive = (req, res) => {
  const gdrv = require('google-drive');
  const token = req.user.tokens.find(token => token.kind === 'google');
  gdrv(token.accessToken).files().list(function(err, fileList) {
    let files = JSON.parse(fileList.body);
    res.render('api/google-drive', {
        title: 'Google Drive API',
        files: files,
    });
  })
};
```

I can get my list of my files... I'll check it and improve if I can.

**Comment by YasharF** [comment]
I just did a manual check, and it looks like the npm dev dependency everyauth is problematic since it has been abandoned and is unmaintained.  Prior to integration of google-drive npm module, if that is the only choice, the dependency on everyauth needs to be removed. Created the issue: https://github.com/niftylettuce/node-google-drive/issues/30

```
$ npm install
npm WARN google-drive@0.0.8 No license field.

audited 655 packages in 2.243s
found 38 vulnerabilities (21 low, 3 moderate, 14 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by YasharF** [comment]
https://github.com/google/google-api-nodejs-client is the officially supported and activly maintained google API package with 270K of downloads per month.  We might be better off using the officially maintained package instead.

**Comment by tanaydin** [comment]
Yeah, seems better idea. I'll try to make same thing with that one too.

**Comment by tanaydin** [comment]
I converted them to official client. I'll polish them a bit then create PR (I hope)

**Comment by YasharF** [comment]
@tanaydin were you able to make any progress on your PR?

**Comment by tanaydin** [comment]
Hello I've some progress with https://github.com/sahat/hackathon-starter/pull/972 
I'll fix PR with comments and update it.

**Comment by YasharF** [comment]
Google Drive API example done: https://github.com/sahat/hackathon-starter/commit/e2871fde95b0871319353448e2fe84b923116ff7

Thank you @tanaydin 🙂

**Comment by YasharF** [comment]
Google Sheets Example: https://github.com/sahat/hackathon-starter/commit/36126f671a0c84a8012414ad855ecf206ecc6991
