### ISSUE TITLE
Video calling/conferencing

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#891]
**Update 10/5/2020:**
The scope of this issue is to add a video calling/conferencing example that can be easily used and modified by developers if needed.  The solution does NOT have to depend on Agora.io and could use any platform that has been established and is well maintained.

**Original Post:**
This is a rough scope definition for potentially integrating a video calling or a video conferencing service such as the service from Agora.io .  @sidsharma27 please comment if you think a different feature set would fit better:

- Create a new API example view: Agora.io example view.  Note that the integration will be using the Web SDK from Agora.
- In the Agora.io example view, the user can create a video channel. Their username (email address) will be the channel ID.
- In the Agora.io example view, the user can join an existing video channel and have a two-way video call, by entering the channel ID of another user that has initiated a channel.
- Add instructions on how to obtain an AppID to the readme.md

Ref: 

- https://docs.agora.io/en/2.3.1/product/Video/API%20Reference/communication_web_video?platform=Web
- https://docs.agora.io/en/2.3.1/download
- https://github.com/AgoraIO/Agora-Web-Tutorial-1to1

**Comment by benhalverson** [comment]
AgoraIO doesn't have a npm package 😞 
Twilio also supports video. https://github.com/twilio/video-quickstart-js

**Comment by YasharF** [comment]
@sidsharma27  can correct me, but from what I recall, AgoraIO's integration would be purely in the front end which would reduce help by not increasing the number of dependencies and the size of the server-side resource consumption.  From what I recall, Twilio doesn't have a free tier, the first 10,000 minutes per month for AgoraIO is free.

**Comment by saif-malik-01** [comment]
I want to work on it.
