### ISSUE TITLE
Login with Google fails

### ISSUE THREAD

**Issue by dok** [sahat/hackathon-starter#895]
Looks like there is a URI redirect mismatch in the configuration.

<img width="1430" alt="screen shot 2018-08-08 at 3 24 15 pm" src="https://user-images.githubusercontent.com/1214868/43868109-dbee770e-9b20-11e8-8e26-129d0708ae37.png">

**Comment by YasharF** [comment]
Sorry, the example deployment doesn't have valid API keys set since the env.example is just dummy key file.

I'm going to leave this github issue open, since the fix would be for one of the maintainers to manually add valid keys in heroku dashboard as env variables.

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/5287051dca6856f81981692b564666f831b9e188
