### ISSUE TITLE
Test file didn't do the test

### ISSUE THREAD

**Issue by Killea** [sahat/hackathon-starter#897]
If I change some test code to

`describe('GET /random-url', () => {
  it('should return null', (done) => {
    request(app)
      .get('/reset')
      .expect(null, done());
  });
});`
The test can still pass. I don't think this is correct. 
If it were correct, what's the meaning of this test script?

**Comment by YasharF** [comment]
Brackets?  Do you mean parentheses?  The parentheses in `done()` are consistant with the usage in https://github.com/visionmedia/supertest/blob/master/test/supertest.js#L359

**Comment by Killea** [comment]
I think they are different. For the code I posted, if you use `done()`, actually it's will always pass the test what  ever the expect it is. I mean, you cannot get the fail result. 
For example, if you expect 200, but the server returns 500, the test still pass because the `done()` parameter, it should be `done`.
English is my second language, maybe I didn't explain this clearly.
Just modify a expect function, change 200 to 300, the test will still pass.

**Comment by Killea** [comment]
https://github.com/visionmedia/supertest/blob/master/test/supertest.js#L26, in this line , they used `done` not `done()`. This is what I want to say, in hackathon-starter code it is `done()`, which makes the test always pass.

**Comment by Killea** [comment]
https://github.com/sahat/hackathon-starter/blob/master/test/app.js#L8  For this line it shoul be 
` .expect(200, done);`, otherwise even if the server returns 500 ,the test still pass.

**Comment by YasharF** [comment]
Thank you.

Fixed with https://github.com/sahat/hackathon-starter/commit/623c2a68a6e6c6db7b0f70737a75437f8cc103a8
