### ISSUE TITLE
RIP `node-sass`

### ISSUE THREAD

**Issue by itsjzt** [sahat/hackathon-starter#898]
It breaks on every new release of nodejs (at least for windows users) and every SCSS & SASS feature can be reproduced with [PostCSS](https://postcss.org/). 

It makes sense to use PostCSS as it also provides more flexibility.

Feel free to tell me PR's are always welcome. 😃

**Comment by YasharF** [comment]
Can you please describe what you mean by "It breaks on every new release of nodejs"?
