### ISSUE TITLE
node app.js breaks 

### ISSUE THREAD

**Issue by azimshaik** [sahat/hackathon-starter#903]
user.js:7
const randomBytesAsync = promisify(crytpo.randomBytes);

TypeError: promisify is not a function

**Comment by YasharF** [comment]
Can you please describe your issue and how you got that error?  The project is working as expected when I am testing it.

**Comment by azimshaik** [comment]
I clone the repo, did `npm install` and  when I run the app `node app.js`. I am getting this error 
```
user.js:7
const randomBytesAsync = promisify(crytpo.randomBytes);

TypeError: promisify is not a function
```

**Comment by YasharF** [comment]
What version of nodejs and npm do you have?  Try the following in the console:
```
node -v
npm -v
```

**Comment by azimshaik** [comment]
```
node v6.9.5
npm v3.10.10
```

**Comment by YasharF** [comment]
Node 8 or later is required for hackathon starter:
https://github.com/sahat/hackathon-starter#prerequisites

My suggestion is to uninstall node 6, and install the latest version of NodeJS (Node 10.9) instead: https://nodejs.org/en
