### ISSUE TITLE
Missing import on modern theme

### ISSUE THREAD

**Issue by slaveofcode** [sahat/hackathon-starter#906]
It looks like `@import "variables.scss"` was missing on `public/css/themes/modern/_modern.scss`

This make an error when I switch a theme to `modern`

**Comment by YasharF** [comment]
For switching to different themes from the default theme, you need to change two lines in main.scss:

- The variables: https://github.com/sahat/hackathon-starter/blob/master/public/css/main.scss#L1
- The scss: https://github.com/sahat/hackathon-starter/blob/master/public/css/main.scss#L10
