### ISSUE TITLE
it possible signup with facebook or twitter?

### ISSUE THREAD

**Issue by mohandex** [sahat/hackathon-starter#907]
hi
can i signup a user without register email and user?

**Comment by YasharF** [comment]
In addition to the local strategy (username and password) the following are the options:

![image](https://user-images.githubusercontent.com/6448697/44791930-a98e9b80-ab57-11e8-87b1-3c992d7f0978.png)

**Comment by mohandex** [comment]
sign in mean singup?
can add to signup page?
without need register email and password?
