### ISSUE TITLE
Update documentation for use of MongoDB Atlas

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#915]
Currently the documentation/readme has references to mlab, and they need to be updated for use of MongoDB Atlas instead.

===============
From: mLab
Sent: Tuesday, October 09, 2018 10:28 PM
Subject: mLab is becoming a part of MongoDB, Inc.

Hello from mLab, 
Today we are announcing that mLab is being acquired by MongoDB, Inc. 
....
What this means for you, our customer 
As part of combining the two companies we will be sunsetting the mLab service and migrating all customers to MongoDB Atlas. 

As a customer of mLab you know that we care deeply about your success. You have our commitment that this migration to MongoDB Atlas will be a smooth experience, and that you are migrating onto an excellent service. 

We will be providing you with specific details of the migration plan in forthcoming updates. In the meantime, here is what you should know: 

- You will be given plenty of time to migrate, and nothing will be required of you for at least 4 months. We expect to have all customers migrated to Atlas within the next 12 months. 
- Once migrated, your Atlas database will be hosted on similar hardware and cost the same or less than your original plan on mLab. 
- We will provide tools that allow you to migrate with either minimal downtime or no downtime to your application. 
- All of this applies to users with mLab Heroku add-ons as well. 

Thank you 
...

**Comment by mgautam98** [comment]
I want to work on this.

**Comment by YasharF** [comment]
I made an attempt to use Atlas and ended up with the following error, hence ended up reverting the merge:
```
(node:382) UnhandledPromiseRejectionWarning: MongoError: not authorized on admin to execute command { insert: "system.indexes", documents: [[{ns admin.sessions} {key [{expires 1}]} {name expires_1} {expireAfterSeconds 0} {unique false}]], ordered: true }
    at Function.MongoError.create (/mnt/c/temp/a/hackathon-starter/node_modules/mongodb-core/lib/error.js:31:11)
    at /mnt/c/temp/a/hackathon-starter/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/mnt/c/temp/a/hackathon-starter/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/mnt/c/temp/a/hackathon-starter/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at TLSSocket.<anonymous> (/mnt/c/temp/a/hackathon-starter/node_modules/mongodb-core/lib/connection/connection.js:333:22)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
It looks like this might be related to:
https://github.com/Automattic/mongoose/issues/6881
https://github.com/Automattic/mongoose/issues/6976

We'll switch once there is a new version of mongoose and we can verify that Atlas works.

I also ended up adding a few other steps since they seem to be needed:
```
<img src="https://docs.mongodb.com/images/mongodb-logo.svg" width="200">

- Go to [https://www.mongodb.com/cloud/atlas](https://www.mongodb.com/cloud/atlas)
- Click the green **Get started free** button
- Fill in your information then hit **Get started free**
- You will be redirected to Create New Cluster page
- Select a **Cloud Provider and Region** (such as AWS and a free tier region)
- Select cluster Tier to **Free Shared Clusters**
- Give Cluster a name (default: Cluster0)
- Click on green **:zap:Create Cluster button**
- Now, to access your database you need to create a DB user. To create a new MongoDB user, from the **Clusters view**, select the **Security tab**
- Then click **Users**, then **Add New User**
- Fill in a username and password and give it either **Atlas Admin** User Privilege
- Next, you will need to create an IP address whitelist and obtain the connection URI.  In the Clusters view, under the cluster details (i.e. SANDBOX - Cluster0), click on the **CONNECT** button.
- Under section **(1) Check the IP Whitelist**, click on **ALLOW ACCESS FROM ANYWHERE**. The form will add a field with `0.0.0.0/0`.  Click **SAVE** to save the `0.0.0.0/0` whitelist.
- Under section **(2) Choose a connection method**, click on **Connect Your Application**
- In the new screen, click on **SRV connection string (3.6+ driver)**
- Finally, copy the SRV string and replace the URI in MONGODB_URI of `.env.example` with this SRV string.  Make sure to replace the <PASSWORD> with the db User password that you created under the Security tab.
- Note that after some of the steps in the Atlas UI, you may see a banner stating `We are deploying your changes`.  You will need to wait for the deployment to finish before using the DB in your application.
```

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/54142e38566ad25224e3275c02f652b0b2759b16

Thank you @mgautam98 for your contribution.
