### ISSUE TITLE
I want to know how to create RESTFUL API for mobile

### ISSUE THREAD

**Issue by hungcv92** [sahat/hackathon-starter#917]
Thanks alot for create amazing kickstarter Nodejs web application.
Im a newbie in nodejs. I try to run this project and work perfect. But now i want create some api for mobile application. But in mobile application not has csrf then Restful api not work. 
So anyone has try to edite this project to work with mobile application can give me 1 solution?
Thanks so much for your help.
Have good work guys!

**Comment by YasharF** [comment]
In your mobile application when there is a form, just like a custom page, you will need to return the CSRF token during the HTTP POST after the HTTP GET similar to https://github.com/sahat/hackathon-starter/blob/master/views/account/profile.pug#L8 in the pug views.

**Comment by hungcv92** [comment]
> In your mobile application when there is a form for data submission (HTTP POST), just like a custom page, you will need to return the CSRF token during the HTTP POST after the HTTP GET similar to https://github.com/sahat/hackathon-starter/blob/master/views/account/profile.pug#L8 in the pug views.
> 
> Related reading about CSRF: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet

Thanks you so much
