### ISSUE TITLE
Supertest hangs unless app is explicitly closed

### ISSUE THREAD

**Issue by marcospgp** [sahat/hackathon-starter#926]
We ran into an issue where supertest would cause nodemon to hang because the test server wasn't being terminated by default. This is related to https://github.com/visionmedia/supertest/issues/437

This should be reproducible in the current repo, though I haven't tested because we have diverged quite a bit from the source at this point.

**Comment by YasharF** [comment]
I am not able to replicate it.  When attempting `npm test` which would invoke `supertest`, the 11 tests pass, and the process exits.  I also don't see any processes still running in the process manager.  I do recall seeing an issue at some point, but increasing the timeout for tests from 3 sec to 10 sec fixed it: https://github.com/sahat/hackathon-starter/commit/1cf3e385b442c15fed0bb7301ab5a666049e2ab5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R14
