### ISSUE TITLE
Planing to add admin panel

### ISSUE THREAD

**Issue by Sentinas** [sahat/hackathon-starter#928]
Good day.
Tell me please. Do you plan to add admin panel? Roles, permission to view content?
Sorry for my English, I use a translator.

**Comment by YasharF** [comment]
Currently, there isn't a plan to add an admin panel.  
If you have a single admin or a fixed list of admins that are not going to change, then you can potentially store them in an env variable and then check for authorization in the admin restricted controller/route with something like:

```
  if (req.user.email !== process.env.ADMIN_EMAIL) {
    req.flash('errors', 'Invalid Permissions');
    return res.redirect('/');
  }
```
