### ISSUE TITLE
 Alignment issue on sign in page

### ISSUE THREAD

**Issue by eric-sciberras** [sahat/hackathon-starter#931]
Hey, I noticed a minor alignment issue on the sign in page. When the browser width is approximately 730px (Bootstrap's medium size range) the login and sign in buttons become misaligned.
 
![screenshot](https://user-images.githubusercontent.com/37064634/52401265-6167a200-2b15-11e9-8f57-9fca47663258.png)
Note: This is taken straight from the Live Demo and tested on Firefox 65 and Chromium 71.

The issue seems to be on lines 17, 23 and 26 of login.pug
https://github.com/sahat/hackathon-starter/blob/3a4a639c0e9c2db606bf6eb08a80c44f2dd1d1c6/views/account/login.pug#L17-L26

changing `offset-sm-3` to `offset-md-3` fixes the alignment issue.

**Comment by YasharF** [comment]
PR merged;  Thank you.
