### ISSUE TITLE
is DDoS part of this starter kit?

### ISSUE THREAD

**Issue by mrtinkz** [sahat/hackathon-starter#936]
Found a new Configurable Denial-Of-Service prevention for http services library. Does this starter has something already for DDoS protection? if not, is it possible to integrate with node-ddos? https://github.com/rook2pawn/node-ddos.git

**Comment by YasharF** [comment]
Instead of application-level DDoS protection in production, I would recommend using a 3rd party service such as Cloudflare.  A service like Cloudflare does a much more comprehensive job of protecting the application from DDoS attacks.

**Comment by mrtinkz** [comment]
That's fair enough, I will go ahead and close this one.
