### ISSUE TITLE
How to configure forgot password in local auth and facbebook auth

### ISSUE THREAD

**Issue by tanmayiitk** [sahat/hackathon-starter#943]

**Comment by YasharF** [comment]
I am not sure if I understand your question.  What is it that you have tried and what is the error or unexpected behavior that you are doing.

A couple of quick notes:
- Make sure to replace the email addresses at https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L308 and https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L403 with your own email address.
- Make sure to follow the instructions at https://github.com/sahat/hackathon-starter#obtaining-api-keys for SendGrid and set SENDGRID_USER and SENDGRID_PASSWORD environment variables, or update the value in .env.example.
