### ISSUE TITLE
Trying to refactor routes

### ISSUE THREAD

**Issue by redlinecodes** [sahat/hackathon-starter#946]
So I'm trying to refactor the routes a bit but am having a bit or trouble:

I refactored the Controllers in app.js like this
```
/**
 * Controllers (router handlers)
 * Refactored
 */
const homeController = require('./controllers/home/index');
const userController = require('./controllers/users/index');
const apiController = require('./controllers/api/index');
const contactController = require('./controllers/contact/index');

With the index.js file just being the routes
```
```
const express = require('express');
const homeController = require('./homeController');

```
const app = express();
```
app.get('/', homeController.index);

module.exports = app;
```

And in app.js - where all the routes are I simply have:
```
app.use('/', homeController);
app.use('/user', userController);
app.use('/contact', contactController);
app.use('/api', apiController);
```

The home route works fine - but that's it. When I go to access /login or /contact - nothing works. I get the error Cannot GET /contact

**Comment by yanivm** [comment]
`homeController.index` is a legitimate [middleware](http://expressjs.com/en/guide/writing-middleware.html) (e.g. a function `(req, res) => { /* does something, like res.send('hi'); */ }`) so GET of `/` works.

In your other examples, you're just referring to the controllers themselves and not to middlewares inside them. How about instead of your `app.use('/contact', contactController)`, try `app.use('/contact', contactController.getContact)`.

(I hope I understood the situation + your question properly; if not, apologies in advance)

**Comment by redlinecodes** [comment]
@yanivm 
Basically all I'm trying to do is to create a separate routes file for all the different types of routes(e.g. /routes/users) and then include the controller files in those router files and then use the router files correctly in app.js

I've looked at various [articles](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes) and I seem to be doing it correctly but I'm probably missing something.

In app.js I now have
`const userRouter = require('./routes/users');
`
And in /routes/users.js I have
```
const express = require('express');
const userController = require('../controllers/user');

/**
 * API keys and Passport configuration.
 */
const passportConfig = require('../config/passport');

// USER ROUTES
const router = express.Router();

router.get('/login', userController.getLogin);
router.post('/login', userController.postLogin);
router.get('/logout', userController.logout);
router.get('/forgot', userController.getForgot);
router.post('/forgot', userController.postForgot);
router.get('/reset/:token', userController.getReset);
router.post('/reset/:token', userController.postReset);
router.get('/signup', userController.getSignup);
router.post('/signup', userController.postSignup);
router.get('/account', passportConfig.isAuthenticated, userController.getAccount);
router.post('/account/profile', passportConfig.isAuthenticated, userController.postUpdateProfile);
router.post('/account/password', passportConfig.isAuthenticated, userController.postUpdatePassword);
router.post('/account/delete', passportConfig.isAuthenticated, userController.postDeleteAccount);
router.get('/account/unlink/:provider', passportConfig.isAuthenticated, userController.getOauthUnlink);

module.exports = router;

```
And then finally in app.js again I have:
```
/**
 * Primary app routes.
 */
app.use('/', homeController);
// app.get('/', homeController.index);
app.use('/users', userRouter);
...
```

However, when I click on LOGIN in the header, I still get the dreaded can not GET /login

**Comment by yanivm** [comment]
(I terribly misread your original question, sorry)

Anyway... this worked for me:

In `app.js`:

    // const app = express(); // etc.
    app.use('/stuffWithRouter', require('./controllers/routerAttempt'));

In `controllers/routerAttempt.js`:

    const routerAttempt = require('express').Router();
    routerAttempt.get('/sayhi', (req, res) => { res.send('hi'); });
    module.exports = routerAttempt;

And now GET of `/stuffWithRouter/sayhi` works for me.

So all in all:
1. Maybe `/users/login` will work for you.
2. And if you want `/login` to do that login stuff, then simply replace your `app.use('/users', userRouter);` with `app.use('/', userRouter);`.

**Comment by redlinecodes** [comment]
@yanivm 
Np. Your example above works! Quick question - does it matter how where I put the `app.use('/stuffWithRouter', require('./controllers/routerAttempt'));`???

I know that it needs to go under the `const app = express();` line

Right now I have it after the last `app.use();`

Thanks for your help.

**Comment by yanivm** [comment]
I believe it matters, at least in the following sense: (quoting from [http://expressjs.com/en/api.html#app.use](http://expressjs.com/en/api.html#app.use))

> Middleware functions are executed sequentially, therefore the order of middleware inclusion is important.

    // this middleware will not allow the request to go beyond it
    app.use(function(req, res, next) {
      res.send('Hello World');
    });

    // requests will never reach this route
    app.get('/', function (req, res) {
      res.send('Welcome');
    });

**Comment by redlinecodes** [comment]
@yanivm - thank you so much for your help and efforts - I got it all working as desired!
