### ISSUE TITLE
Mongodb download link broken

### ISSUE THREAD

**Issue by elviric** [sahat/hackathon-starter#947]
Old link : https://mongodb.org/download is broken.
New Download Mongodb server link for local development [here](https://www.mongodb.com/download-center/community)

**Comment by YasharF** [comment]
Would you be able to create a PR to fix it?

Thanks

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/edb81a596d9dda87656f26d09ff28eae54c0f1bf
