### ISSUE TITLE
Use of Axios instead of request.js

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#952]
requestjs is used at a few places, and they can most likely be replaced with axios.  This issue is to investigate the usage and replace where applicable.

**Comment by FX-Wood** [comment]
Working on it! I aim to do it one file at a time, starting with api.js.

**Comment by YasharF** [comment]
Make sure to manually test the changes.  You may have to obtain the relevant API key(s) for testing.

Thanks

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/pull/954. Thank you @FX-Wood!
