### ISSUE TITLE
Hosted MongoDB Atlas instructions are broken/not clear

### ISSUE THREAD

**Issue by luckymurari** [sahat/hackathon-starter#955]
First off thanks a lot for the great README page. It is very thorough and making me get a headstart.

I just spent > 1 hour trying to figure out why my local installation was giving No response. Finally I stumbled upon [this](url) StackOverflow link that provided the answer to the error:

```
(node:87135) UnhandledPromiseRejectionWarning: MongoError: not authorized on admin to execute command { insert: "system.indexes", documents: [[{ns admin.sessions} {key [{expires 1}]} {name expires_1} {expireAfterSeconds 0} {unique false}]], ordered: true }
    at Function.MongoError.create 
.
.
.
.
.
(node:87135) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:87135) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The documentation for Hosted MongoDB Atlas mentions the following line : 

> In the new screen, click on Standard connection string (3.4+ driver). WARNING: Do not pick 3.6+ since there Express Session currently has a compatibility issue with it.

But there is no such option:

![image](https://user-images.githubusercontent.com/696147/56692914-d902a180-6700-11e9-88d9-34bedaeef1ae.png)

The instruction need to be updated to 

> In the new screen, select **Node.js** as Driver and version **2.2.12 or later**. WARNING: Do not pick **3.0 or later**  since connect-mongo can't handle mongodb+srv:// connection strings. Your connection string should look like `mongodb://<username>:<password>@cluster0-shard-00-00-ab2cd.mongodb.net:27017,cluster0-shard-00-01-ab2cd.mongodb.net:27017,cluster0-shard-00-02-ab2cd.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true` (Ensure it starts as mongodb and not mongodb+srv)

**Comment by YasharF** [comment]
It looks like the underlying issue is going to be resolved soon: https://github.com/jdesboeufs/connect-mongo/issues/292#issuecomment-481585027
