### ISSUE TITLE
Does it make sense to add PWA support?

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#959]
Does it make sense to add PWA support?

**Comment by matheuschimelli** [comment]
It would be nice

**Comment by jay51** [comment]
It would make it very large and difficult for those who just need basic things. Maybe create a separate branch only for that

**Comment by niallobrien** [comment]
Best left as an exercise to the user imo.

**Comment by redlinecodes** [comment]
@YasharF I do love the idea - maybe just for a React SSR app with basic auth features like it already has; Login, Signup, Profile, Password Reset and Forgot.
