### ISSUE TITLE
Alternatives to Google Maps API

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#965]
For any "presentable" use of Google Maps APIs, Google now requires the developer to enable billing.  There is no longer a free tier, but Google for now is applying $200 of credit for map API usage to the accounts that use the service.  The developers can set API usage limits in the GCP console to stay under the $200 cap, but the process takes more steps.

Since developers are under the clock and rather have less headaches for figuring out the details, let's explore and see if there are other alternatives for getting started with mapping, and potentially either replace the current map example or add a new case.

**Comment by mmbatha** [comment]
HERE Maps has potential: https://developer.here.com/

**Comment by YasharF** [comment]
I met @nraboy at a workshop (Amazon LEX+Lambda+Here APIs) which he was holding earlier this week and had a chat about replacing the Google Maps API example.  He might potentially be able to help with something interesting using HERE APIs example.

**Comment by YasharF** [comment]
https://github.com/sahat/hackathon-starter/commit/e2871fde95b0871319353448e2fe84b923116ff7 is a good example of most of what needs to be touched when adding a new API example.

**Comment by mmbatha** [comment]
Sounds great! Can't wait to see that something interesting

**Comment by nraboy** [comment]
Let me know how I can help. If you haven't already, check out our live-streams:

twitch.tv/heredev

Best,

**Comment by YasharF** [comment]
@nraboy 
I added a HERE map image API example to the project:
- Commit: https://github.com/sahat/hackathon-starter/commit/041f1f3f0f36c222f9982357dc2a8e7e071bbf50
- Demo: https://hackathon-starter.walcony.com/api/here-maps

Ideally, I like to see an interactive Here map example in the same view as well, and I did spend some time trying to figure out how to add it but all of the existing code examples that I found seem to be much more complex and heavy on adding custom (non-library) javascript to the view.  It would be great if we can have a simple interactive map example.  As far as complexity and code length, potentially similar to the image map example that is in the commit or the Google Maps example https://github.com/sahat/hackathon-starter/blob/master/views/api/google-maps.pug#L138

I'm OK if we need to add some libraries to the page header.

Is this something that you can potentially help with?  I would love a PR if you have time for it.

**Comment by YasharF** [comment]
We can also just leave the example as is and close this issue.  It is simple as is, which may make it more attractive for hackathon participants, or new developers that are using the project as a boilerplate to use.

**Comment by nraboy** [comment]
You might want to check the live-streams for a simple getting started snippet. Take https://github.com/heremaps/devrel-livestreams/blob/master/developer-waypoints/season-1/episode-1/index.html#L9-L22 for example.

**Comment by YasharF** [comment]
Thanks @nraboy .  Is there a quickway to change the color or add text to the markers without having to define an SVG?  I'm  trying to replicate the markers that the image service generated as in:
![image](https://user-images.githubusercontent.com/6448697/60544993-d73ff600-9cce-11e9-98c6-5899ed00d344.png)
```
poix0=47.6516216,-122.3498897;white;black;15;Troll&\
poix1=47.6123335,-122.3314332;white;black;15;Seattle Art Museum&\
poix2=47.6162956,-122.3555097;white;black;15;Olympic Sculpture Park&\
poix3=47.6205099,-122.3514661;white;black;15;Space Needle&\
```

**Comment by nraboy** [comment]
To use a marker beyond the default you'd have to use your own marker images. You don't have to work with SVG data.

For text, you might look at `InfoBubble` for the maps.

Best,

**Comment by YasharF** [comment]
Thanks,
I think it is good enough for now.
The two commits to close this issue: https://github.com/sahat/hackathon-starter/commit/041f1f3f0f36c222f9982357dc2a8e7e071bbf50 and https://github.com/sahat/hackathon-starter/commit/b90ebc97c7b1af5c66ccc8f0636bf4f26cae0aef
