### ISSUE TITLE
Missing await in controllers/api.js exports.getFoursquare 

### ISSUE THREAD

**Issue by arieltci** [sahat/hackathon-starter#975]
exports.getFoursquare = async (req, res, next) => {
  const token = **await** req.user.tokens.find(token => token.kind === 'foursquare');
  let trendingVenues;
......

**Comment by YasharF** [comment]
Can you submit a PR?
Please make sure to manually test the api example with the change.

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/7d17baf396a91b2939944870a0fe2735571b395f
