### ISSUE TITLE
AI/ML API Examples

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#984]
We have some documentation about using IBM Watson: https://github.com/sahat/hackathon-starter#ibm-watson

It would be great if we have one or more working API examples using Watson or ML/AI APIs that are provided by other companies such as Microsoft or AWS.

**Comment by mding5692** [comment]
What other ML/AI API companies would you consider valid and is there a criteria?

**Comment by YasharF** [comment]
In the context of integration with this project, historically I have considered a few factors including Alexa ranking and the company's involvement in the hackathon scene.

**Comment by mding5692** [comment]
Can probably use AWS AI/ML APIs as they have free tier and lots of different services as well:
https://aws.amazon.com/free/machine-learning/
https://aws.amazon.com/campaigns/free-machine-learning-on-AWS/

**Comment by mding5692** [comment]
Actually can just use Google Cloud-based AI/ML APIs as there is already an existing Google Cloud integration and can use below links as references:
https://cloud.google.com/ai-platform
https://cloud.google.com/products/ai
https://cloud.google.com/ai-platform/docs

**Comment by nadavlev** [comment]
Are you not assuming that this will interest ALL users of this project?
would you consider making this optional?

**Comment by jhashivam-2001** [comment]
Hey there , I am intrested in taking up the issue ! Any fixed deadline to submit the PR ?
