### ISSUE TITLE
Readme link to Node and Express tutorial is broken

### ISSUE THREAD

**Issue by Chaslav** [sahat/hackathon-starter#988]
The link from the Readme goes to a broken (removed by the user) video
https://www.youtube.com/watch?v=BN0JlMZCtNU

You can use something like this
https://www.youtube.com/watch?v=k_0ZzvHbNBQ&list=PLillGF-RfqbYRpji8t4SxUkMxfowG4Kqp

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/5df00c2f3471152ce5a3af8ba7f6417bd48ef49a
