### ISSUE TITLE
404 with sw.js

### ISSUE THREAD

**Issue by mayeaux** [sahat/hackathon-starter#990]
I keep having a request from the frontend being made to the backend for sw.js but it keeps 404'ing

Where is this request coming from? Can't seem to find it. Thanks!

**Comment by YasharF** [comment]
Is this on an unmodified clone of the hackathon-starter repo?

**Comment by mayeaux** [comment]
To the best of my knowledge it's been happening since the moment I cloned the repo.

**Comment by YasharF** [comment]
I don't see it.

It is a problem left from a prior project that you have worked on.  sw.js is a service worker javascript.  A project that you worked on previously with an address of localhost:8080 has installed a service worker in your browser probably for push notifications.  Your browser sees the URL and thinks that it is the same website as the one with the service worker and tries to reload/update the service worker's source.  See https://love2dev.com/blog/how-to-uninstall-a-service-worker

**Comment by mayeaux** [comment]
Okay you're totally right, I had set something up as a progressive web app, thanks for helping me figure that out.
