### ISSUE TITLE
npm security vulnerabilities and a possible fix

### ISSUE THREAD

**Issue by harismh** [sahat/hackathon-starter#991]
Running `npm install` on a fresh clone yields 47 high-level security vulnerabilities according to npm. All of these seem to be coming from the `lodash` package. 

Running `npm audit fix` ups the lodash version from `^4.17.11` to `^4.17.15`. This fixes the security issues and `npm test` shows no failed tests.

I think this a proper fix, and I can submit a PR if wanted.

**Comment by YasharF** [comment]
I'm looking into this.  All but one of them is from the dependencies.

**Comment by YasharF** [comment]
Regenerating package-lock.json seems to fix the problem as well.

```
$ npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 3742 scanned packages
```

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/0fc7bfa1bb439da1df022bd77c0b7923a34a6f01
