### ISSUE TITLE
Suggestion: Pug Bootstrap mixins

### ISSUE THREAD

**Issue by niallobrien** [sahat/hackathon-starter#994]
Hi all, just looking for some feedback. What do you all think of including some Bootstrap 4 Pug mixins?

I'm not suggesting that we change all of the views to utilise these mixins, but including them and documentation on how to use them would certainly make for quicker development in a hackathon scenario. Obviously if they were included via npm, it would be harder to customise the mixins, so I suggest keeping them within the view directory.

Let me know what you think.

**Comment by YasharF** [comment]
Assuming that you are referring to a library like https://www.npmjs.com/package/pug-bootstrap , it doesn't look like if it is being used much.
