### ISSUE TITLE
Use of --save flag when installing npm packages is unnecessary 

### ISSUE THREAD

**Issue by omar-dulaimi** [sahat/hackathon-starter#995]
Hey everybody
You know as of npm version 5 it's no longer necessary to use the --save flag when installing dependencies since it does that by default. The prerequisite node version for this repo is 8.0+ which comes with npm version 5.0+. Stating that, can I make a PR changing these notes in the Pro tips section?

Thank you!

**Comment by niallobrien** [comment]
But definitely important to know when to `--save` vs `--save-dev`.

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/2ff3ede07bf1385903b0719382c5f552c9551761

Thanks
