### ISSUE TITLE
'https://hackathon-starter-2018.herokuapp.com' is not working !

### ISSUE THREAD

**Issue by AaronNGray** [sahat/hackathon-starter#996]
'https://hackathon-starter-2018.herokuapp.com' is not working on Google, GitHub, LinkedIn, ...

**Comment by YasharF** [comment]
@sahat can we change the demo link in the description to the same one as in the readme ( https://hackathon-starter.walcony.com ), or remove the link from the repo description?  I created https://hackathon-starter.walcony.com and planning to maintain its credentials.  It is a Heroku deployment fronted by Cloudflare.

![image](https://user-images.githubusercontent.com/6448697/62380783-cd442980-b4fe-11e9-8345-2013af10f18f.png)


![image](https://user-images.githubusercontent.com/6448697/62380873-07153000-b4ff-11e9-9a99-d596cf331584.png)

**Comment by sahat** [comment]
Sure, done.
